### ISSUE TITLE
Response and "content-length" -header

### ISSUE THREAD

**Issue by k03n00b** [koseven/koseven#10]
This might be a PHP 7 issue https://github.com/kohana/kohana/issues/109

**Comment by neo22s** [comment]
I think is just a bug, not related to PHP7 

You can do a pull request and we will merge if works ;) thanks

**Comment by jstrobel** [comment]
@k03n00b Tried to reproduce it but cannot. Used more that 8000 chars. Can you provide me some code as an example? Thanks

**Comment by neo22s** [comment]
I can not reproduce it, just removed the issue from 3.3.7 for now...

**Comment by jstrobel** [comment]
@k03n00b We haven't heard a reply on this, 2 of us cannot reproduce it. So i will close the case so far. If you have still the issue, please reopen it with some example code and we will have a look into it. Thank you.
