### ISSUE TITLE
ORM: Update has_many relation

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#101]
I find it very annoying that you need to update has_many relations one by one in your own code. Typically I convert everything to primary key array, make 2 diffs (on for the new and another for the removed ones), and loop trough these arrays calling add and remove on the model.
I found that I was writing the same code over and over (okay copied and pasted stuff) so I added this feature to the ORM module itself.
Has anybody an other method? I can create a PR.

**Comment by neo22s** [comment]
not sure I understand can you show a piece of code?

**Comment by svenbw** [comment]
I tried to keep it brief, but the code example below shows the example for the user roles. It adds and removes only those entries in the database which are changed.
```
$current_ids = $user->roles->find_all()->as_array(NULL, 'id');

$new_ids = array_diff($posted_ids, $current_ids);
if (count($new_ids) > 0)
{
  $roles = ORM::factory('Role')->where('id', 'IN', $new_ids)->find_all();
  foreach ($roles as $role)
  {
    $user->add('roles', $role);
  }
}

$delete_ids = array_diff($current_ids, $posted_ids);
if (count($delete_ids) > 0)
{
  $roles = ORM::factory('Role')->where('id', 'IN', $delete_ids)->find_all();
  foreach ($roles as $role)
  {
    $user->remove('roles', $role);
  }
}
```
Maybe there's a better solution (which I didn't think of)...

**Comment by knbv** [comment]
You can pass an array of foreign keys:

```
$model->add('roles', array(1, 2, 3, 4));
// https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L1726

$model->remove('roles', array(1, 2, 3, 4));
// https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L1759
```
Or You want to check the links directly in the functions "add" and "remove"?

Now I'm doing like this:

                $user->remove('roles');

                if (Arr::get($data, 'roles')) {
                      $roles = ORM::factory('Role')
                         ->where('id', 'IN', $roles_ids)
                         ->find_all();

                      if ($roles->count() > 0)
                          $user->add('roles', $roles->as_array());

                   // OR $user->add('roles', $roles_ids);
                }

It helped You?

**Comment by svenbw** [comment]
That would do it but 2 things:
- Remove will remove all entries from the database and you will add them again afterwards.
- The same code is written over and over again in each class that has many relation

My proposal is to add some generic code to the ORM class itself that would do the same thing. One could add an extra key in the `$_has_many` definition `... ,'update' => TRUE, ...` which would run my or your code. Or a mix:

```
$current_ids = $user->roles->find_all()->as_array(NULL, 'id');

$new_ids = array_diff($posted_ids, $current_ids);
if (count($new_ids) > 0)
{
    $user->add('roles', $new_ids);
}

$delete_ids = array_diff($current_ids, $posted_ids);
if (count($delete_ids) > 0)
{
    $user->remove('roles', $delete_ids);
}
```
I added the additional roles query to be sure that only existing roles are added, which prevents a database exception.

**Comment by svenbw** [comment]
I noticed that the code already contained this feature: [See here](https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L785)

This means that when you create a relation you can add the `'update' => TRUE` to the relation definition array all relations will be updated.
