### ISSUE TITLE
Optimize all Routes in one

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#103]
I try to create registration function, first if have already good please link me...
So, I create controller **Registration**, where put all methods, also create routes, but think, can optimize all methods routes in one (think with **array()**), but how?

	// Registration
	Route::set('registration','registration')
		->defaults(array(
			'directory' => 'Pages/Registration',
			'controller' => 'Registration',
			'action' => 'Registration'
		));

	// Registration activate
	Route::set('registration/activate','registration/activate/<user_id>')
		->defaults(array(
			'directory' => 'Pages/Registration',
			'controller' => 'Registration',
			'action' => 'RegistrationActivate'
		));

	// Registration final
	Route::set('registration/final','registration/final')
		->defaults(array(
			'directory' => 'Pages/Registration',
			'controller' => 'Registration',
			'action' => 'RegistrationFinal'
		));

	// Recovery
	Route::set('recovery','recovery')
		->defaults(array(
			'directory' => 'Pages/Registration',
			'controller' => 'Registration',
			'action' => 'Recovery'
		));

	// Recovery final
	Route::set('recovery/final','recovery/final/<user_id>/<key>')
		->defaults(array(
			'directory' => 'Pages/Registration',
			'controller' => 'Registration',
			'action' => 'RecoveryFinal'
		));
And:

Thx.

**P.S.** Also maybe have same solution for generate/create routes from DB?

**Comment by neo22s** [comment]
Hello,

Here the docs https://docs.koseven.ga/guide/kohana/routing

Here you have many examples https://github.com/yclas/yclas/blob/master/oc/config/routes.php

You could have a table called routes where you store the route info and then loop on the query and add them ;)

**Comment by Samnan** [comment]
Here is a simple way to aggregate your registration routes in one definition (you will find that on the documentation also)


     Route::set('registration','registration(/</action>(/<user_id>))', 

      array('action' => 'index|activate|final'))

	->defaults(array(
		'directory' => 'Pages/Registration',
		'controller' => 'Registration',
		'action' => 'Registration'
	));
