### ISSUE TITLE
Adding new modules

### ISSUE THREAD

**Issue by Samnan** [koseven/koseven#104]
Hi,

   I have a few modules that I have created overtime for Kohana, they are pretty useful for development, and now that we have ko7, I would like to publish those modules into the new repo so others can find them.

  So I am thinking, should we put additional modules in the 'modules' folder? or create a 'thirdparty' folder inside module (not nice in my opinion). 

  So simply put it, just looking to find the best way to introduce new modules into kohana, but to keep the repo nice and managed as usual...

**Comment by knbv** [comment]
You can add compatible modules to this list:
Https://github.com/koseven/koseven/blob/gh-pages/modules.md
They are displayed here: https://koseven.ga/modules.html

**Comment by neo22s** [comment]
@knbv thanks! right answer!

**Comment by Samnan** [comment]
Understood, can close this issue.
