### ISSUE TITLE
Remove composer.json

### ISSUE THREAD

**Issue by Samnan** [koseven/koseven#105]
Why is it there anyway :)

**Comment by piotrgolasz** [comment]
It allows you to load external libraries in bootstrap.php
https://github.com/koseven/koseven/blob/devel/application/bootstrap.php#L62

**Comment by Samnan** [comment]
I would then suggest removing this dependency from bootstrap. 

The problem with this approach is that it breaks the modular structure of Kohana. bootstrap should not contain vendor/autoload.php at all. Even if the framework itself has dependencies, they should be moved to a module, and in that module this logic can be applied.

Similarly, all other functionality should be encapsulated in separate modules, where as each module can contain its vendor folder.

**Comment by neo22s** [comment]
can you suggest or do PR that will be better so we can evaluate? I see it fine how it is now. ;)

**Comment by Samnan** [comment]
will do!

**Comment by Samnan** [comment]
Hmm.. it seems to be commented out already...

https://github.com/koseven/koseven/commit/e39bea2eb3094e5e2ea6500aa3ed3a41f463551c

**Comment by neo22s** [comment]
yes it is commented. ;) thats what I do not understand what you are trying hehehe

**Comment by Samnan** [comment]
Haha, my bad. I guess I panicked when i saw composer.json in root folder. I have had really a bad experience with laravel because of composer dependency, so just wanted to make sure koseven remains clean as ever :)

Will close for now
