### ISSUE TITLE
Check before insert

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#109]
I have phone module, where need check row before insert in DB.
**1. I check
2. Write if
3. Get add data**

I understand is not good code way, very bad code, please fix me, I want to learn clear code...
Please show me example too.

Thx.

	public function addPhone($user_id, $phone) {
		$check_phones = DB::select('phone')
			->from($this->_table_name)
			->where('phone', '=', $phone)
			->and_where('phone', '!=', 0)
			->limit(1)
			->execute()
			->as_array();

		if(empty($check_phones)){
			$insert = DB::insert($this->_table_name,array(
					'user_id',
					'phone'
				))
				->values(array(
					$user_id,
					$phone
				))
				->execute();

			$phones = DB::select('id', 'phone')
				->from($this->_table_name)
				->where('id', '=', $insert[0])
				->limit(1)
				->execute()
				->as_array();
		}

		if (!empty($phones[0])) return $phones[0];
		return null;
	}

**Comment by knbv** [comment]
Are you using ORM in the project?

Here is a simple example:
```
class Model_User extends Model_Auth_User
{
    	public function labels()
    {
        return [
        //..
            'phone_number' => 'Phone Number',
        //..
        ];
    }
    
        public function rules()
    {
        return [
            //..
            'phone_number' => [
                ['phone', [':value', [7, 10, 11, 12, 13,],],],
                [[$this, 'unique',], ['phone_number', ':value',],], // 
            ],
            //..
        ];
    }
    
        public function filters()
    {
        return [
            //..
            'phone_number' => [
                ['trim',],
                ['preg_replace', ['/\D+/', '', ':value',],],
                [function ($v) {
                    return (strlen($v) > 0 ? $v : NULL);
                }, [':value']],
            ],
            //..
        ];
    }
}

$user = ORM::Factory('User')
    ->where('id', '=', 'YOUR_USER_ID')
    ->find();
    
    if ($user->loaded()){

    	if (!$user->phone_number){

    		$user->phone_number = 'YOUR_PHONE_NUMBER';
        
            try {
        		$user->save();
    
    		} catch (ORM_Validation_Exception $e) {
        		var_dump($e->errors('validation'));
    		}
    	}
    }
```

**Comment by svenbw** [comment]
You need to create a table containing the phone numbers and a user id. Create the table in such a way that there is a constraint that links the phone to your user in the database. If you delete the user the database will remove all phones by itself.
Something like this:
```
CREATE TABLE `userphones` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `phone` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `userphones_ibfk_1` (`investment_id`),
  CONSTRAINT `userphones_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
Next you need to create a model for your user phone, name it after you table so Kohana will figure out which table to use.

Add a relation to you user model:
```
protected $_has_many = array(  'items'        => array('model' => 'InvoiceItem', 'foreign_key' => 'invoice_id')
);

```

**Comment by Pantela777** [comment]
Thx, but i already have DB table and model, but I need optimize my code, but it's work fine too.

**Comment by jstrobel** [comment]
I think @svenbw answered your question? so if yes, can you please close this issue? Thanks.
