### ISSUE TITLE
Kohana DB builder, MariaDB and PHP7

### ISSUE THREAD

**Issue by k03n00b** [koseven/koseven#11]
UNION is behaving differently with newer MariaDB and PHP7.

Kohana's DB builder is using brackets
`(SELECT ...) UNION ALL (SELECT ...) ORDER BY id DESC`
With brackets result won't be ordered / sorted correctly. Brackets will break ORDER BY. 

Here's fix:
`SELECT ... UNION ALL SELECT ... ORDER BY id DESC`

/modules/database/classes/Kohana/Database/Query/Builder/Select.php

		if ( ! empty($this->_union))
		{
			$query = ''.$query.'';
			foreach ($this->_union as $u) {
				$query .= ' UNION ';
				if ($u['all'] === TRUE)
				{
					$query .= 'ALL ';
				}
				$query .= ''.$u['select']->compile($db).'';
			}
		}

**Comment by svenbw** [comment]
Looks like a bug in MariaDB and should be fixed in MariaDB version  10.2.1
(see [MDEV-10037 UNION with LIMIT ROWS EXAMINED does not require parentheses](https://jira.mariadb.org/browse/MDEV-10037))
