### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by mycroft84** [koseven/koseven#110]
Introduce namespace all part...

**Comment by neo22s** [comment]
this has been discussed before and will break the API for 3.x

I tihnk theres other forks of KO that are willing to make that step or have been done. I am not ready for such migration ;)

**Comment by Samnan** [comment]
Having a feature available does not mean it will always be convenient to
work with in all scenarios. I have seen large projects with namespaces and
it can get pretty ugly with all those namespaces.

If it is the requirement of your project, you can easily put all your own
code files in namespaces, kohana will not prevent you. You can also do
little work in extending autoloading logic to get what you want.

**Comment by jstrobel** [comment]
I go with @neo22s i am not ready to migrate too

**Comment by piotrgolasz** [comment]
Closing.
