### ISSUE TITLE
Client IP recorded incorrectly when client's behind a proxy

### ISSUE THREAD

**Issue by blckct** [koseven/koseven#111]
The code here:
https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Request.php#L109

It returns the first IP in the list and so it may be a privat subnet IP. Additionally it's easy to spoof it so it may be a security risk.

**Comment by neo22s** [comment]
thanks for reporting! please PR a change ;)

**Comment by jstrobel** [comment]
@blckct Just to give you a hint if you don't know how: https://help.github.com/articles/creating-a-pull-request/

**Comment by blckct** [comment]
@jstrobel It's a bit more complicated then that. It's more of an architecture decision rather than anything else, changing how XFF is interpreted may break a lot of things.

**Comment by jstrobel** [comment]
So i think, if you share some of your ideas we can discuss it in group

**Comment by blckct** [comment]
Well, the current code looks like this:

>				// Format: "X-Forwarded-For: client1, proxy1, proxy2"
> 				$client_ips = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);  
> 				Request::$client_ip = array_shift($client_ips);

It returns the leftmost IP supplied by the user, I suggest we should use the right most that stays after removing the trusted proxies.

In fact I did a quick check and it seems that's what happens in Symfony.

**Comment by satanch** [comment]
So it's fixed or not?

This is how I see our solution:
[https://repl.it/KU5e/1](https://repl.it/KU5e/1)

Is this what we want? :thinking:

**Comment by neo22s** [comment]
@satanch I am not sure if its correct lets be honest. I have not tried in a real scenario where theres multiple proxies or other complex things... 

What is 100% sure is that yo can never trust the request since its easy to spoof even in this casi you could do it...

**Comment by blckct** [comment]
We're already checking if the request comes from a trusted proxy so we should be pretty sure that right-most value is not spoofed if the proxy does support X-Forwarder-For

**Comment by neo22s** [comment]
@blckct so please make a suggestion or a PR and we close this ;)

**Comment by blckct** [comment]
I was saying @satanch solution should be working well.

**Comment by satanch** [comment]
Should I create PR with my solution. I'm afraid that we can break some things and get some new bugs. :confused: 
@blckct

**Comment by satanch** [comment]
Code is correct as I think.

[https://en.wikipedia.org/wiki/X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For)

> the left-most being the original client

Helper or smth should be developed for proxy check .

**Comment by blckct** [comment]
I think the solution is correct. There will most certainly be problems with breaking thins but I think it's better than having a problem with spoofing.

**Comment by jstrobel** [comment]
As of this discussion here and the sended links, i thought too the solution should work. So i merged it. If there are any tests or discussions leads to another solution, we roll it back.
