### ISSUE TITLE
facebook SDK

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#114]
Who can testing work this or not...
https://github.com/kosciCZ/FacebookAuth-for-Kohana-3.3

When I try to output login url, and link it, my website is just refresh with GET `?code=...` param, I think is  facebook token code.
`$fb = FacebookAuth::factory();`
`$fb->login_url();`

Thx.

**Comment by neo22s** [comment]
you should contact the developer of the module ;)

I use hybridauth. https://github.com/hybridauth/hybridauth

The Faecbook API is updated often, and probably what they are using in that module is not working anymore.

regards

**Comment by Pantela777** [comment]
It's official work module? https://github.com/tchemineau/kohana-hybridauth
Any step-by-step tutorial how can use it?

**Comment by neo22s** [comment]
The official packages are included in the repo of koseven.

here they explain how to install it https://github.com/hybridauth/hybridauth#installation its a composer package.

**Comment by Pantela777** [comment]
I see this, but how I use module after install? I think must to edit my route, user model...?
Sorry for noob questions, I am first do this... And want to learn...
Thx.
