### ISSUE TITLE
Change base url in default installation

### ISSUE THREAD

**Issue by Samnan** [koseven/koseven#115]
Currently the base_url is set to /kohana/ in bootstrap.php

     Kohana::init(array(
	   'base_url'   => '/kohana/',
    ));

My suggestion is to make it '/', for two reasons. One, by default php7 has a built in server, so testing the site quickly is very easy using `php -S localhost:3000`, in which case the default installation does not work because of the above url. Secondly, most projects would be using kohana framework on the main website instead of a 'kohana' subfolder, so it makes sense to make the default url to be the domain instead of a subfolder.

**Comment by piotrgolasz** [comment]
in old kohana, git clone downloads the repo into 'kohana' folder, so it was setup that way.
I think think we should include in the install tutorial to
```
git clone git@github.com:koseven/koseven.git .
```
and then we can set default url to '/'

**Comment by piotrgolasz** [comment]
I would put
`cd /var/www`
before cloning (so that we acknowledge that we're in the HTTP server default directory

**Comment by satanch** [comment]
@neo22s we can close it.

**Comment by satanch** [comment]
@piotrgolasz server directory can be different, clone command couldn't.

**Comment by jstrobel** [comment]
@piotrgolasz Yes, if we want to document this, i think we should document it for different system and so on.

**Comment by satanch** [comment]
User should have minimal knowledge about terminal, and how to use it. About his webserver too.

**Comment by piotrgolasz** [comment]
Readme should say that cloning should occur in webserver main directory.
