### ISSUE TITLE
Using link anchors + ASCII

### ISSUE THREAD

**Issue by knbv** [koseven/koseven#117]
Helper HTML::anchor generates a wrong link, if it uses the anchor (ID)

Tests:
```
echo HTML::anchor('http://google.com/#test', 'Test');
// <a href="http://google.com/#test">Test</a> - OK

echo HTML::anchor('http://google.com/#тест', 'Test');
// <a href="http://google.com/#тест">Test</a> - OK

---

echo HTML::anchor('/#test', 'Test');
// <a href="/kohana/index.php/#test">Test</a> - OK

echo HTML::anchor('/#тест', 'Test');
// <a href="/kohana/index.php/%23%D1%82%D0%B5%D1%81%D1%82">Test</a> - BAD

---

echo HTML::anchor('#test', 'Test');
// <a href="#test">Test</a> - OK

echo HTML::anchor('#тест', 'Test');
// <a href="#тест">Test</a> - OK
```

You can write that the identifier should consist exclusively of the characters a-Z, but look at this:

I'm using the correct ID

```
echo HTML::anchor('/тест#test', 'Test');
// <a href="/kohana/index.php/%D1%82%D0%B5%D1%81%D1%82%23test">Test</a> - BAD
```

It turns out you can not use the anchor in any link where ASCII is present? 

The lattice character must not be coded

https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/HTML.php#L129

https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/URL.php#L152

What do you think about it? We need to fix the regular expression here to avoid encoding the lattice character?
https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/URL.php#L155

If you replace the line:
`$path = preg_replace_callback('~([^/]+)~', 'URL::_rawurlencode_callback', $path);`

on this:
`$path = preg_replace_callback('~([^/#]+)~', 'URL::_rawurlencode_callback', $path);`

Links are generated correctly:
```
echo HTML::anchor('/#тест', 'Test');
// <a href="/kohana/index.php/#%D1%82%D0%B5%D1%81%D1%82">Test</a> - OK
```

Perhaps there are other suggestions?

**Comment by neo22s** [comment]
I honestly do not use the HTML helper functions, I started doing it using all the tags, but later swap and used it directly in HTML in the templates...

Just do a PR with the fix and the proper tests , thanks ;)
