### ISSUE TITLE
Cookie names cannot contain any of the following

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#118]
ErrorException [ 2 ]: Cookie names cannot contain any of the following '=,; \t\r\n\013\014' ~ SYSPATH/classes/Kohana/Cookie.php [ 184 ] 

https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Cookie.php#L184

Maybe we should clean $name before using it?
https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Cookie.php#L105

And then when reading it use the same function https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Cookie.php#L55

Strange, anyone else had this issue before?

**Comment by jstrobel** [comment]
Looks strange, haven't this issue before.

**Comment by knbv** [comment]
So it was always and this is quite the expected error. Cookie name must not contain any characters from the specified list.

Automatic cleaning of the variable $name can lead to unexpected consequences. Is not it?

**Comment by neo22s** [comment]
If we clean the $name on set and get should all work the same...

**Comment by knbv** [comment]
I understand, but the name will be different from what the user specifies

This is an expected error, the user should know that he allowed it, so it is conceived from the beginning. Otherwise, why not clear the variable directly in the [setcookie](http://php.net/manual/ru/function.setcookie.php) function? PHP developers do not do that ;)

**Comment by neo22s** [comment]
users do not set the cookie, I guess you mean devels.

We use generated cookies so I guess thats the issue, from our side, or something similar.

The API of PHP many times sucks... thats why frameworks do exist. To make devels life easier. So if I want to set the name of a cookie to "asdasd a sdasd asd " I should not worry about what the PHP parser does and fix the string to "asdasd-a-sdasd-asd".

**Comment by knbv** [comment]
> users do not set the cookie, I guess you mean devels.

Users of the framework are developers :)

>We use generated cookies so I guess thats the issue, from our side, or something similar.

If the developer uses the generated names for cookies, he must make sure that they are correct

>The API of PHP many times sucks... thats why frameworks do exist. To make devels life easier. So if I want to set the name of a cookie to "asdasd a sdasd asd " I should not worry about what the PHP parser does and fix the string to "asdasd-a-sdasd-asd".

Suppose I set cookies with Koseven, and then I want to get a value using JS, I will have to check the cookie from the browser to make sure its name has not changed?

**Comment by neo22s** [comment]
But that happens already, since you wont be able to read the content ;)

**Comment by knbv** [comment]
Why can not I?

**Comment by neo22s** [comment]
https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Cookie.php#L164

**Comment by knbv** [comment]
In fact, this does not prevent you from getting the necessary cookies:

```
Cookie::$httponly = FALSE;
Cookie::set('test', 'myCookie');
```

```
<script type="text/javascript">
    <!--

    function getCookie(name) {
        var matches = document.cookie.match(new RegExp(
            "(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + "=([^;]*)"
        ));
        return matches ? decodeURIComponent(matches[1]) : undefined;
    }

    var vars = getCookie('test').split('~');
        
    console.log('salt: ' +  vars[0]);
    console.log('test: ' +  vars[1]);
    -->
</script>
```

Result:
salt: 8834a76hb6f0715f0fa979dedda5c5b9b34991dd
test: myCookie

**Comment by neo22s** [comment]
I have not said reading the name, but you can not have the values.

**Comment by knbv** [comment]
Why do I need to change the value if I just want to get the cookie value by the name I set when I created the cookie?

**Comment by neo22s** [comment]
Not change the value, but you can not read the value either...... unless you have the same code in JS.

So at the end you have same issue, so thats why I am proposing to sanity the $name.

**Comment by knbv** [comment]
Why can not I read cookies? I gave the code above, try it.

Kohana does not encrypt cookies, but simply adds a hash to do the checking

**Comment by knbv** [comment]
Why can not I read cookies? I gave the code above, try it.

Kohana does not encrypt cookies, but simply adds a hash to do the checking

**Comment by neo22s** [comment]
you are right I read the code wrong and thought there was an extra ) in https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Cookie.php#L120

Anyway what I am proposing does not affect anything. Same as you did having a function to read the cookie anyway to clean the name ;)

**Comment by knbv** [comment]
Do not pay attention to my function, it can be replaced by any other, where cleaning is not provided, because in JS there is no convenient native function for working with cookies

I'm trying to explain that if a user sets up a cookie named "name", he will expect the cookie to be installed with this name.

So if I want to get a cookie with JS, or any other application, I do not need to check in the browser under what name the framework has saved my cookie.

**Comment by neo22s** [comment]
I am not saying to replace the name of the cookie I am saying to clean the name of the cookie from illegal characters so this error does not appear. I dont see the big deal. Imagine theres a user with name Thom Smith. I want a cookie called "Thom Smith" but I can not since will get an error, so we do the cleaning and will be thom-smith. and save the cookie. When reading will be transformed. End ;)

**Comment by knbv** [comment]
Option 1:
Cookie::set('Thom Smith', 'myCookie'); // Error, the user must specify the correct name

Option 2:
Cookie::set('Thom Smith', 'myCookie'); // Ok, cookie name - Thom-Smith, but the developer does not even suspect this

The developer tries to get a cookie called "Thom Smith" from another application and gets an error that such a cookie does not exist, the developer starts to understand and understands that the system substitutes the name. This is normal?

**Comment by knbv** [comment]
Option 1:
`Cookie::set('Thom Smith', 'myCookie'); // Error, the user must specify the correct name`

Option 2:
`Cookie::set('test', 'myCookie'); // Ok, cookieName - Thom-Smith, but the developer does not even suspect this`

The developer tries to get a cookie called "Thom Smith" from another application and gets an error about the fact that such a cookie does not exist, the developer starts to think and finds out that the system substitutes the name. This is normal?

**Comment by neo22s** [comment]
We do this with the cache system too.

**Comment by Come2Daddy** [comment]
What if `Cookie::set()` returns the sanitized name instead of boolean (we know if it failed with false value btw), so at the end we allways got it right...

**Comment by neo22s** [comment]
We need to check if by doing so we do not break anything.

I know its a stupid issue, but its the first time I get this error in the logs.... we have 100K page views per day so I guess is normal some stuff breaks thats why I check daily the logs.

**Comment by Come2Daddy** [comment]
`Session->write()` seems to be the only one which return directly `Cookie::set()` value. Should return a boolean, can't find anything using it in vanilla koseven. It's a minor change but maybe if will affect some third party modules.

**Comment by knbv** [comment]
It seems easier for me to see the real name of the cookie in the browser than to display the value of variables on the site and compare their names, in fact this does not completely solve the problem, do not waste time on it.

Another question, do you think this is a mistake in Kohana / Koseven?

**Comment by neo22s** [comment]
Not a mistake per se. I think is something we can easily control as we do in many other functions that natively do not do any validation or check, just found about it today. Thats all.

**Comment by Come2Daddy** [comment]
Symfony throw an exception in case there is illegal chars in name, Codeigniter and FuelPHP doesn't bother att all, like Ko7. Seems a bit more clean to let dev know he's missing something.

**Comment by neo22s** [comment]
What do we do we ignore it? I have added the code in my project to control it. Extended class and ready.
