### ISSUE TITLE
ORM column

### ISSUE THREAD

**Issue by piotrgolasz** [koseven/koseven#120]
Hi guys,
do you have any examples how can I declare a column for example as a JSON. This would imply that value of this field is automatically json_encode($data,$param) when saving to db and json_decode($data,$param) when fetching from DB ($param is true/false - fetching array/object).

TLDR: how do you setup custom ORM field?

**Comment by jstrobel** [comment]
I have looked in some Classes and think (but still untested) you need to add:
protected $_serialize_columns = array('data');
to your Model. Is that what you mean? Can you try it?

**Comment by piotrgolasz** [comment]
@jstrobel I have previously used Jelly ORM for Kohana,
That's an example of serialized class (it serializes the column before saving and unserializes when loading from DB) https://github.com/creatoro/jelly/blob/3.3/develop/classes/Jelly/Core/Field/Serialized.php

The fact is I never used native Kohana ORM and was wondering if this can be done.

Let's say my User_Model has field address that will be JSON. I don't want to manually json_encode/decode every time I load/save model. I need to setup the model in that way so it is done automatically.

So integer fields are cast to integer, json fields gets cast to json and so on.  Is Behavior the only way to do it, or is there another trick in ORM?

**Comment by svenbw** [comment]
@piotrgolasz I've added behavior support in the ORM class.
This feature might be suitable for your needs (although there's only support for [guid's](https://github.com/koseven/koseven/blob/devel/modules/orm/classes/ORM/Behavior/Guid.php) and [slugs](https://github.com/koseven/koseven/blob/devel/modules/orm/classes/ORM/Behavior/Slug.php) at the moment).

**Comment by knbv** [comment]
You just need to do this:

```
class Model_User extends ORM
{
        protected $_serialize_columns = [
            'your_column_name',
    ];
}
```

https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L166
https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L571
https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L602

By default, the CSF is used, however you can override this:
https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L1909
https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L1914

You can also use filters to apply field changes:

```
class Model_User extends ORM
{
        public function filters()
    {
        return [
            'user_id' => [['intval',],],
            'address' => [
                ['trim',],
                [function ($v) {
                    return (strlen($v) > 0 ? $v : NULL);
                }, [':value']],
            ],
        ];
    }
}
```
