### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by hotrush** [koseven/koseven#122]
https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Valid.php#L135

I think need to increase 2,6 to at elast 2,7 to accept .capital domains for example

**Comment by neo22s** [comment]
Will be much easier:

```PHP
//get the email to check up, clean it
$email = filter_var($email,FILTER_SANITIZE_STRING);

// check valid email format using RFC 822
if (filter_var($email, FILTER_VALIDATE_EMAIL)===FALSE)
```

**Comment by piotrgolasz** [comment]
so
`function email(string $email): boolean
{
return filter_var(filter_var($email,FILTER_SANITIZE_STRING),FILTER_VALIDATE_EMAIL) === FALSE;
}`

**Comment by piotrgolasz** [comment]
@neo22s How does strict mode relate to using filter_var. Should this switch be depreciated?

**Comment by neo22s** [comment]
@piotrgolasz look good to me... and yeah for me by default should be strict always... with filter_var but to keep the API... thanks a lot
