### ISSUE TITLE
Better "Helper" support

### ISSUE THREAD

**Issue by Daijobou** [koseven/koseven#124]
See https://docs.koseven.ga/guide/kohana/helpers
> You can make your own helpers by simply making a class and putting it in the classes directory

Thats not a fine solution. Is here a way to add custom helper-files in "classes/Helper" folder, instead directly in "classes"? So it make more sense for me, that helper-files put in a folder with name "helper".

classes/Helper/Myhelper.php
`class Helper_Myhelper {...}`

**Comment by jstrobel** [comment]
I think one way would be to write your own function or extend the existing one based on:
`public static function auto_load($class)`
in core.php
and load it in bootstrap.php
`spl_autoload_register(array('Kohana', 'auto_load'));`

**Comment by svenbw** [comment]
@Daijobou I always use the structure from your example, Kosevens will pick up the class name automatically.

Helpers are for me (small) common classes which can be used over different projects.
For project specific helpers I create my own folder under classes using the project name.

classes/Icecream/Myhelper.php:
`class Icecream_Myhelper {...}`

**Comment by neo22s** [comment]
thanks I tihnk can be closed ;)
