### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#125]
A while ago there was a discussion on Telegram on how to handle translations. I tried to explain how I handle my own translations and I promised to share the details. So here we go a gist with some comment how to use it.

[gist link](https://gist.github.com/svenbw/258fca0d25a632557e8c53ed9c0115b7)

**Comment by knbv** [comment]
Thanks!

Here is my version of the multilingual ORM model: https://gist.github.com/knbv/d7aab5b220a0954d415230bb4782df8f

**Comment by piotrgolasz** [comment]
Well, at least you can edit from your CMS. If you don't need editing, then the regular __() function will suffice.

**Comment by jstrobel** [comment]
What do you think about a "best practice" section or something like that in the docs?

**Comment by neo22s** [comment]
I will close this and put it in a milestone called code examples, ;)
