### ISSUE TITLE
Remove array

### ISSUE THREAD

**Issue by arkagod** [koseven/koseven#126]
In code replace **array** with **[...]**

**Comment by arkagod** [comment]
https://github.com/arkagod/koseven2 - removed array

**Comment by neo22s** [comment]
please do a PR

**Comment by piotrgolasz** [comment]
I took quite a while to look through all the PR changes, but it looks fine.

**Comment by neo22s** [comment]
not only array also coding standard! I have not look in deep but looks great!

Also all tests running too:
https://github.com/koseven/koseven/pull/127 ---> https://travis-ci.org/koseven/koseven/builds/255059705?utm_source=github_status&utm_medium=notification

**Comment by piotrgolasz** [comment]
So merge?
