### ISSUE TITLE
Improving ORM model relationships ($_has_many through)

### ISSUE THREAD

**Issue by knbv** [koseven/koseven#129]
Let's say I have a models (this just example):

```
User
User_Book
User_Book_Review
```

Tables in the database:

```
users
id, name, ...

user_books
id, user_id, name, ...

user_book_reviews
id, book_id, ...
```

I have a User object, I need to display all records from table "user_book_reviews" that belong to the records from the table "user_books" that belong to the User object.

I need has_many through

```
class Model_User extends Model_Auth_User
{
    protected $_table_name = 'users';

    protected $_has_many = [
        'book_reviews' => [
            'model' => 'Book_Review',
            'through' => 'user_books',
            'foreign_key' => 'user_id',
            'far_key' => 'book_id',
        ],
]

}
```

The error occurs because the SQL query is generated incorrectly:

`Database_Exception [ 1054 ]: Unknown column 'user_books.book_id' in 'on clause' [ SELECT COUNT(`book_review`.`id`) AS `records_found` FROM `book_reviews` AS `book_review` JOIN `user_books` ON (`user_books`.`book_id` = `book_review`.`id`) WHERE `user_books`.`user_id` = '{MY_USER_ID}' ]`

I'm doing something wrong, or Kohana ORM doesn't support the ability to add such relations?

A similar function in Laravel:
https://laravel.com/docs/5.4/eloquent-relationships#has-many-through **!!!**

Solution:

If these lines:

```
// Join on through model's target foreign key (far_key) and target model's primary key
$join_col1 = $through.'.'.$this->_has_many[$column]['far_key'];
$join_col2 = $model->_object_name.'.'.$model->_primary_key;
```

https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L691

Replaced by:

```
if (isset($this->_has_many[$column]['local_key']))
    {
        // Join on through model's target local key (local_key) and target model's far key
        $join_col1 = $through.'.'.$this->_has_many[$column]['local_key'];
        $join_col2 = $model->_object_name.'.'.$this->_has_many[$column]['far_key'];
    }
    else
    {
        // Join on through model's target foreign key (far_key) and target model's primary key
        $join_col1 = $through.'.'.$this->_has_many[$column]['far_key'];
        $join_col2 = $model->_object_name.'.'.$model->_primary_key;
    }
```

We can do this:

```
class Model_User extends Model_Auth_User
{
    protected $_table_name = 'users';

    protected $_has_many = [
        'book_reviews' => [
            'model' => 'Book_Review',
            'through' => 'user_books',
            'foreign_key' => 'user_id',
            'far_key' => 'book_id',
            'local_key' => 'id',
        ],
]

}
```

And get the correct SQL query:

`SELECT COUNT(`book_review`.`id`) AS `records_found` FROM `book_reviews` AS `book_review` JOIN `user_books` ON (`user_books`.`id` = `book_review`.`book_id`) WHERE `user_books`.`user_id` = '{MY_USER_ID}'`

What do you think of it?

**Comment by svenbw** [comment]
I never had any issues with that. I leave out to key specifications because Kohana figures it out by itself.
But only if the names are correct.

**Comment by knbv** [comment]
The question is not inclusive words, look at this example:

Https://laravel.com/docs/5.4/eloquent-relationships#has-many-through

Can you repeat this with Kohana ORM?

**Comment by svenbw** [comment]
I think i can look like this:
```
class Model_User extends Model_Auth_User
{
    protected $_has_many = [
        'book_reviews' => [
            'model' => 'Book_Review',
            'through' => 'user_books',
        ],
  ]
}
```
The table name can be left out because it matches your model name.

In my code I never use underscores betweeon model names, so I'm not sure if this might break thinks...

**Comment by knbv** [comment]
Do not pay attention to the fact that I explicitly indicate the names of tables and keys, this is just an example.

Your code will not work because it will generate an invalid query, but that's not the case, can you do the same with Kohana ORM?

https://laravel.com/docs/5.4/eloquent-relationships#has-many-through

**Comment by svenbw** [comment]
Yes I do, I just say that in my code Book_Review would be named BookReview. So if your real code would use also an underscore in the table names it _might_ fail.
Kohana uses the same setup for user and roles. A user has many roles and is linked to the role using a has_many relation.
```
protected $_has_many = array(
  'user_tokens' => array('model' => 'User_Token'),
  'roles' => array('model' => 'Role', 'through' => 'roles_users'),
);
```
In some of my code I have also an id-column on the table thank links the two tables (_users_roles_ or _users_ and _reviews_ in your example)

**Comment by knbv** [comment]
Do you read between the lines? :)

By the way:
Book_Review - correct model name
BookReview - wrong model name

https://docs.koseven.ga/guide/kohana/conventions#class-names-and-file-location

**Comment by etopian** [comment]
You can use Laravel's ORM instead: https://github.com/koseven/koseven/issues/460
