### ISSUE TITLE
Valid::phone length

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#130]
adding country code we need to increase the phone length.

Ex. Argentina: +54 11 1234-5678 -> 12 digits length.

Via
https://github.com/yclas/yclas/issues/2437

**Comment by knbv** [comment]
What's the problem? You can specify the desired number of characters as an optional parameter:

https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Valid.php#L347

A simple example:
```
class Model_User extends Model_Auth_User
{
    public function rules()
    {
        return [
            'phone_number' => [
                ['phone', [':value', [7, 10, 11, 12, 13,],],],
            ],
        ];
    }
}
```

**Comment by neo22s** [comment]
@knbv 100% correct! didnt see it thanks
