### ISSUE TITLE
PHP 7.2 deprecated functions

### ISSUE THREAD

**Issue by Gazoo** [koseven/koseven#131]
Lets make sure that koseven is PHP 7.2 compatible. I noticed that its still using "each" in system\classes\Kohana\Response.php (line 301) which has been deprecated. We can just convert this into a foreach loop.

https://wiki.php.net/rfc/deprecations_php_7_2

**Comment by neo22s** [comment]
We did remove mcrypt already, so great idea to take a look already and move it forward! ;)

https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/Response.php#L301

Also its a difficult to read line of code IMHO

I have not tested it but this should work right?

```
foreach ($key as $_key=>$_value)
    $this->cookie($_key, $_value);
```

@Gazoo can you do a PR and we test it? thanks!!
