### ISSUE TITLE
[Suggestion] Add Apache 2.4 .htaccess example

### ISSUE THREAD

**Issue by satanch** [koseven/koseven#135]
Current version of .htaccess **is not working** with Apache 2.4.
Can you add example for Apache 2.4?

**Correct .htaccess file for Apache 2.4:**
[https://gist.github.com/satanch/6333409d74c8333aebf92fdd331e1edc](https://gist.github.com/satanch/6333409d74c8333aebf92fdd331e1edc)

Thank you!

**Comment by neo22s** [comment]
Hello! please do a PR ;)
