### ISSUE TITLE
Readme images is not loading

### ISSUE THREAD

**Issue by satanch** [koseven/koseven#137]
[https://github.com/koseven/koseven/blob/devel/README.md](https://github.com/koseven/koseven/blob/devel/README.md)

"Latest Stable Version" and "License" images is not loading.

> Failed to load resource: the server responded with a status of 504 (Gateway Timeout)

**Comment by knbv** [comment]
Checked, all badges are displayed correctly.

Maybe the problem is on Your side, or is it a temporary problem?

**Comment by satanch** [comment]
Same with Opera VPN.

**Comment by satanch** [comment]
But [https://poser.pugx.org/koseven/koseven/v/stable](https://poser.pugx.org/koseven/koseven/v/stable) is working, maybe GitHub issue for me?

**Comment by satanch** [comment]
Closing this issue, because this is not an Kohana issue.
