### ISSUE TITLE
Broken https://docs.koseven.ga/guide-api/*

### ISSUE THREAD

**Issue by megazoid84** [koseven/koseven#142]
Couldn't find the working section of documentation on the https://docs.koseven.ga/guide-api/

Page throws an exception:
ErrorException [ Warning ]: Declaration of Kohana_Minion_Exception::handler(Exception $e) should be compatible with Kohana_Kohana_Exception::handler($e)

**Comment by satanch** [comment]
Working after [this](https://github.com/koseven/koseven/commit/e22368cc8050a5e650d6e1fd1bb7ae816b6fcc20) commit?

**Comment by satanch** [comment]
Userguide is working for me from devel branch. Should be website updated with this version?

**Comment by piotrgolasz** [comment]
Looks ok in the code. I guess the website needs a kohana update.
https://github.com/koseven/koseven/blob/devel/modules/minion/classes/Kohana/Minion/Exception.php

**Comment by neo22s** [comment]
Hello I have fixed this file only. as soon as we do new release I will upload all thanks.
