### ISSUE TITLE
The guide-api page throws an error if the unittest module is enabled

### ISSUE THREAD

**Issue by errotan** [koseven/koseven#145]
Reproduction steps:
1) Enable the userguide and unittest module
2) Access the /guide-api page

System:
Debian 9.1, PHP 7.0

The /guide page works without error. I installed the phpunit debian package. Tried to require the Autoload.php file in bootstrap.php, copied the PHPUnit folder to web root, application, vendor folder, but the problem persists. Attached the error page, Kodoc_Missing tries to make an invalid class.

[guide-api.zip](https://github.com/koseven/koseven/files/1255195/guide-api.zip)

**Comment by piotrgolasz** [comment]
I fixed it, but this
https://github.com/koseven/koseven/blob/devel/modules/userguide/classes/Kohana/Kodoc/Missing.php#L32

is a hack of some sort, and I don't like it.

**Comment by errotan** [comment]
Thank you! The attached patch (https://github.com/koseven/koseven/pull/146) fixes the issue.
