### ISSUE TITLE
short_open_tag required but not used

### ISSUE THREAD

**Issue by errotan** [koseven/koseven#147]
The install script halts if the short_open_tag is not enabled, but I can't find any file which uses the <? ?> syntax. Why it is required? This option may break vendor modules if they use the <?xml tag.

**Comment by neo22s** [comment]
You can do a PR and remove it. I personally use it absolutely everywhere but thats optional of course.

**Comment by satanch** [comment]
@errotan are you really shure?
I can do a PR with install.php fix, but if we really don't have short tags inside the framework.

**Comment by errotan** [comment]
Done a regexp search for the short tag in the project, but haven't found any file with it. Made a PR with the change.
