### ISSUE TITLE
Koseven site for new brand

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#148]
Lets make our site better https://koseven.ga/

Using new brand colors and logo

![29709312-878c941e-8994-11e7-8f2e-43ea4add52e8](https://user-images.githubusercontent.com/241725/29997164-bbcca04c-900c-11e7-9b97-74f037e8b41e.png)

In branch
https://github.com/koseven/koseven.ga
We can use a simple landing template like
https://blackrockdigital.github.io/startbootstrap-new-age/

Where we name the main features etc...

Related
https://github.com/koseven/koseven/issues/141

**Comment by evgenykoptelov** [comment]
Logos in .png and .eps in the first archive:
[koseven-1.zip](https://github.com/koseven/koseven/files/1272527/koseven-1.zip)

Originals in Sketch 3 format:
[koseven-2.zip](https://github.com/koseven/koseven/files/1272528/koseven-2.zip)

**Comment by satanch** [comment]
I will try to develop a new kodoc with our new logo and colors using Bootstrap 4.

**Comment by neo22s** [comment]
@evgenykoptelov thanks a lot!

@satanch  that would be truly awesome!!! :D

**Comment by satanch** [comment]
Waiting for review and fixes.
Repo: https://github.com/satanch/koseven-website
Demo: https://satanch.github.io/koseven-website/dist/

**Comment by satanch** [comment]
I can also fetch README data from repo.

**Comment by jstrobel** [comment]
I start a list with some ideas:
- [ ] Website and Doc should be included in the "design"
- [ ] Clean modern design
- [ ] Responsive
- [ ] Headlines/Categories: What is koseven, history, Migrate Kohana to Koseven, Docs & Community, Who we are
- [ ] Links to github and telegram-group
- [ ] Doc: Browsable documentation, examples

**Comment by neo22s** [comment]
We can use as base for the content https://web.archive.org/web/20160310080516/http://kohanaframework.org:80/

I will like to add links to live projects using koseven ;)

**Comment by jstrobel** [comment]
@neo22s ok. i will have a look.

**Comment by uBizzy** [comment]
I can use my "CSS team" to improve the layout of the website and docs, but that may only occur near the end of the year.

**Comment by toitzi** [comment]
> @neo22s ok. i will have a look.

@jstrobel any updates?

**Comment by jstrobel** [comment]
@toitzi Sorry. But not really. There are so many templates out there but most of them are with big images and headers etc. I am searching for a more "portal" like theme like the old page.
Other solution would be build a page from scratch.

**Comment by neo22s** [comment]
For me something like this https://blackrockdigital.github.io/startbootstrap-new-age/

removing images and put the correct links... sorry I am out for holidays until 1st january xD

**Comment by jstrobel** [comment]
What do you think about: http://themes.getbootstrap.com/preview/?theme_id=14341&show_new=
we could use it for website + doc?

**Comment by neo22s** [comment]
Issue I see is that is not open source, therefore we could not have it on
our github repo. But looks great yes.

**Comment by jstrobel** [comment]
If i would sponsor it and we use a private repo? 🤔

**Comment by jstrobel** [comment]
https://themes.3rdwavemedia.com/bootstrap-templates/startup/prettydocs-free-bootstrap-theme-for-developers-and-startups/

**Author & License**
This Bootstrap template is made by UX designer Xiaoying Riley for developers and is 100% FREE under the Creative Commons Attribution 3.0 License (CC BY 3.0)

**Commercial License Options**
If you’d like to use this template without the attribution link, you can buy the commercial license:
Single Application License ($16)
Multiple Applications License ($60)

**Comment by neo22s** [comment]
Good for me: https://github.com/xriley/PrettyDocs-Theme

**Comment by neo22s** [comment]
getting a server is no issue, actually using github pages it's possible ;)

**Comment by toitzi** [comment]
@neo22s @jstrobel Can we close this issue?
If a discussion is still needed i suggest to open an issue on [koseven.ga](https://github.com/koseven/koseven) repository. But think this is done.

**Comment by neo22s** [comment]
think so!
