### ISSUE TITLE
mcrypt not required in install.php still used in encrypt module

### ISSUE THREAD

**Issue by piotrgolasz** [koseven/koseven#154]

**Comment by neo22s** [comment]
What we should do is to put as default openssl but is not required to use mcrypt to work with koseven. And we should not.

**Comment by errotan** [comment]
There are mcrypt unit tests and they will fail when php 7.2 comes out.

**Comment by piotrgolasz** [comment]
Those tests need to be rewritten. By the way 7.2 will have native libsodium implementation.

**Comment by neo22s** [comment]
@piotrgolasz first time I hear about it! sounds cool "Libsodium is a modern cryptography library that offers authenticated encryption, high-speed elliptic curve cryptography, and much more."

**Comment by neo22s** [comment]
@piotrgolasz create another issue to implement ir?
