### ISSUE TITLE
Invalid SQL query in the IN condition selection using Query Builder

### ISSUE THREAD

**Issue by knbv** [koseven/koseven#160]
Suppose we want to list orders of all users who have been registered for some time:

```
$orders = ORM::factory('Order')
    ->where('client_id', 'IN', ORM::factory('Client')
        ->where('created', 'BETWEEN', [time() - Date::DAY, time()])
        ->find_all()
        ->as_array(NULL, 'id')
    )->find_all();
```

If users are found, it will generate approximately the condition: 

`... WHERE `client_id` IN ('1', '2', '3')`

However, if the users is not found, it will generate the following condition: 

`... WHERE `client_id` IN ()`

This will cause the following error: MYSQL: "You have an error in your SQL syntax; ..."

This condition will not cause the error:

`... WHERE `client_id` IN (NULL)`

Can we think that this is a bug? Do I need to fix Query Builder so that the correct condition is generated?

I think that it is acceptable because `... WHERE `client_id` IN (NULL)` will not allow you to select records where field is NULL because to select such recordings you need to use an explicit `... WHERE clause `client_id` IS NULL`.

What do you think about it?

**Comment by svenbw** [comment]
I always struggled with the same issue. I used to test if the array was empty, but adding something like this in Builder.php (after the `$op === 'BETWEEN'` test)
```
elseif (($op === 'IN') AND is_array($value) AND empty($value))
{
   $value = 'NULL';
}
```
should do it. So I'm in favor.

**Comment by knbv** [comment]
Yes, I have a ready solution to the problem, it works on production server, but before provisioning PR I decided to ask the opinion of other community members. Maybe it can cause any problems?

**Comment by neo22s** [comment]
same here, had same problem so I did a check before... I am in favor too!

**Comment by svenbw** [comment]
I don't think the `NULL` will cause an issue, I found another piece of code where I use the same trick. If the array is empty I assign it to NULL.
