### ISSUE TITLE
koseven on nginx

### ISSUE THREAD

**Issue by tomeroto** [koseven/koseven#165]
hello koseven team,

I have a problem using this framework.
I can't launch direct url to the controller and action, for example this url:
http://localhost/koseven/index.php/Welcome/list

Browser show result : 404 Not Found

Help me, what can I do for fix this issue.

For info: I use MAMP on mac for instant web server, php and mysql.

**Comment by errotan** [comment]
In your issue subject you mentioned nginx, but at the end you wrote MAMP which uses apache. Which one do you have problems nginx or apache?

**Comment by errotan** [comment]
Change these lines in nginx site conf:

fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
fastcgi_param PATH_INFO $fastcgi_script_name;

to something like this:

fastcgi_param SCRIPT_FILENAME $document_root/index.php;
fastcgi_param PATH_INFO $document_root/index.php;

**Comment by tomeroto** [comment]
MAMP have two options for web servers. I choose nginx in this case. Can you help me?

**Comment by errotan** [comment]
Have you tried the change that I suggested?

https://github.com/koseven/koseven/issues/165#issuecomment-336780164

**Comment by tomeroto** [comment]
I don't see the lines that you provide in nginx.conf.
Now, I back to use apache right now.

**Comment by errotan** [comment]
These lines are not in nginx.conf but in site configuration. Search in the sites-available directory.

**Comment by jstrobel** [comment]
@tomeroto Do you have it working now? If yes, i would be nice if you can document the changes and commit it to the documentation.

**Comment by tomeroto** [comment]
Yes, I just add several lines to nginx.conf in server context like this:

```
location /koseven/ {
	try_files $uri /koseven/public/index.php?$args;
}
```

From code above you must change **koseven** with folder name (base folder) where the koseven is installed.

And start the address http://localhost/koseven from your favorite browser.

# JUST IT :)
