### ISSUE TITLE
Missing important files in 3.3.7 tag, master branch and 3.3.7 download...

### ISSUE THREAD

**Issue by omicr0n** [koseven/koseven#166]
Guess not very many people running on this ko7 fork as this version has been out since April with apparently no one else reporting it... or I missed the memo on something :)

 The 3.3.7 tag, master branch, and 3.3.7 downloads are missing
```
example.htaccess
index.php
install.php
```

Note:  I grabbed those files from 3.3.6 so I don't need help on the issue just reporting it.

**Comment by farazilu** [comment]
That mean most users are old kohana users so they did no needed these files like me.. although i did one new install and copied these files from old project. we need these files for new users.

**Comment by jstrobel** [comment]
Can you do a PR so we can merge it? Thanks.

**Comment by piotrgolasz** [comment]
those files are now in /public folder

**Comment by jstrobel** [comment]
@piotrgasz You are right i forgot that for a second as i answered. So we can close this issue.
