### ISSUE TITLE
Composer with Koseven

### ISSUE THREAD

**Issue by edsonalanis** [koseven/koseven#167]
I'm developing an application where I started using Kohana and now Koseven, and I need to use an api that was available in the composer, I followed the steps to download the files I created a folder to sell inside the application, and put in the bootstrap.php code to call the autoload of the composer.
But after doing this when trying to use a class of this api error of "class not found" occurs.
I do not know what else to do, can you help me?

**Comment by edsonalanis** [comment]
I am not able to use the classes that should have been loaded by the composer autoload.
I do not know what else to do, can you help me?

**Comment by farazilu** [comment]
Can you share how you included composer autoload in your project?

**Comment by edsonalanis** [comment]
I followed the steps http://www.andrewault.net/2013/10/31/use-composer-with-kohana-3-3/
I also tried: require_once APPPATH. '/vendor/autoload.php';

**Comment by farazilu** [comment]
You can follow this official docs to include autoload
https://docs.koseven.ga/guide/kohana/files
add a init.php in you application add put this line in it. 
`require Kohana::find_file ( 'vendor', 'autoload' );`

**Comment by edsonalanis** [comment]
I already did this test and it also did not work

**Comment by edsonalanis** [comment]
I made the inclusion of this line in bootstrap.php, I have no init.php

**Comment by quincykwende** [comment]
Greetings,

I'm also new to Koseven but I have been using Kohana since 2010.

I have been fighting  with this same issue for the past few hours.. I tried
find_file and autoload no way.

I used required 'path/vendor/auto load.php';

It works

Regards

On Nov 1, 2017 2:15 PM, "Edson Alanis" <notifications@github.com> wrote:

I made the inclusion of this line in bootstrap.php, I have no init.php

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/koseven/koseven/issues/167#issuecomment-341090254>, or mute
the thread

**Comment by quincykwende** [comment]
Am using a windows server at the moment so I used the absolute path in the
string.C:\......

Please try to this ... it should work while we figure out why Kohana
find_file or auto load isn't working

**Comment by edsonalanis** [comment]
Sorry, I did not understand how to do it.

**Comment by quincykwende** [comment]
Sorry using Mobile to text... firewall for mail.

I included the autoload in my controller before using the package I
installed via compose

For instance:

  require 'C:\wamp\www\koseven\vendor\autoload.php';

$instance = new Package;

**Comment by knbv** [comment]
@edsonalanis, I think You just use it for the wrong bundle. Use a modern IDE with tips.

**Comment by edsonalanis** [comment]
I have done this too, as below, however it seems that the autoloader generated by the composer does not register the class

`require` 'C: \xampp\htdocs\esocial\application\vendor\autoload.php';

**Comment by knbv** [comment]
edsonalanis, Perhaps you are using the package incorrectly? What package are you connecting? How do you use it?

**Comment by edsonalanis** [comment]
I'm trying to use the code below:

$ certificate = Certificate::readPfx($content, $password);

This Certificate class is part of an API that I downloaded via composer, and as far as I understand the autoload of the composer registers the class.
But I have an error in this line: Error [0]: Class 'Certificate' not found.

**Comment by knbv** [comment]
Well, since you did not specify a link to the package ...

Here is an example of connecting another library:

https://packagist.org/packages/facebook/php-sdk-v4

```
$fb = new Facebook\Facebook([
    'app_id' => '{app-id}',
    'app_secret' => '{app-secret}',
    'default_graph_version' => 'v2.2',
    //'default_access_token' => '{access-token}', // optional
]);
```

**Comment by quincykwende** [comment]
Please check to see if the package uses namespace

Then add the namespace at the begining of the class

name/fffd/Certificate::readPfx($content, $password);

In your own files comment out use name/fffd

I have been able to use kohana find file

I moved my vendor directory to classes/vendor

Apparently I was getting it wrong ...  was assuming

Kohana::find_file('classes', 'vendor/autoload');

**Comment by edsonalanis** [comment]
It worked, it was exactly this problem, the namespace.
I did not know I needed to put it on.
Thanks a lot for the help.

**Comment by quincykwende** [comment]
Great

**Comment by xcorp1986** [comment]
the problem is simple to resolve，you just load the file “vendor/autoload.php”,which is generate by composer,for further information，you need to read documents at https://getcomposer.org/

**Comment by edsonalanis** [comment]
Hello xcord1986, I do not know if you read the entire thread, but it was not simply loading the autoload file, the framework uses NameSpace and in the documentation did not speak in these cases that would have to put the namespace up front.
