### ISSUE TITLE
[Critical] Broken changes

### ISSUE THREAD

**Issue by satanch** [koseven/koseven#168]
Hello!

I think I broke some older fixes with my PR.

List: https://github.com/koseven/koseven/commits/devel
This: https://github.com/koseven/koseven/commit/d4799f7f43fd54b67859d2204a1d7e9addf15e24

Maybe my repo **was not** synced with devel.

I think @knbv @neo22s know smth about this changes.

**Comment by satanch** [comment]
Everything is fine. Sry.

**Comment by quincykwende** [comment]
Good
