### ISSUE TITLE
Can't update user information

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#169]
I have form with can to change user password.
`<input type="password" name="user_pass" value="" />`

In model I have:
```$res = DB::update($this->_table_name)
->set(array(
  'password' =>  
))
->where('id','=',$user_id)
->limit(1)
->execute();
```

I have next problem... When user didn't fill any info to password field, and click form submit (he just try to change another info., I cut it from exp. code...), model try to update password with empty information `''`... I try `(isset($data['user_pass'])) ? Auth::instance()->hash($data['user_pass']) : NULL` but update with `null`...

So how I can check field is empty or not, and if empty didn't update it...

Thanks.

**Comment by andrej-tkachenko** [comment]
Try instead
`isset($data['user_pass'])`
use
`! empty($data['user_pass'])`
The following things are considered to be [empty](http://fi2.php.net/manual/en/function.empty.php#refsect1-function.empty-returnvalues):
- "" (an empty string)
- 0 (0 as an integer)
- 0.0 (0 as a float)
- "0" (0 as a string)
- NULL
- FALSE
- array() (an empty array)
- $var; (a variable declared, but without a value)

**Comment by Pantela777** [comment]
Thx.
Can't understand how can use, because output error `ParseError [ 0 ]: syntax error, unexpected if (T_IF)`
If can write me full code, and I learn it.

**Comment by Pantela777** [comment]
ParseError [ 0 ]: syntax error, unexpected variable (T_VARIABLE)
```
$res = DB::update($this->_table_name)
    ->set(array(
      'passport_number'     => (!empty($data['passport_number']) $data['passport_number'])
    ))
    ->where('id','=',$user_id)
    ->limit(1)
    ->execute();
```

ParseError [ 0 ]: syntax error, unexpected if (T_IF)
```
$res = DB::update($this->_table_name)
    ->set(array(
      'passport_number'     => (if(!empty($data['passport_number']))) $data['passport_number'])
    ))
    ->where('id','=',$user_id)
    ->limit(1)
    ->execute();
```

**Comment by knbv** [comment]
Sorry, but this question does not apply to Kohana/Koseven

1. Learn PHP syntax
2. Use a modern IDE
3. Profit!

Here to discuss serious issues

**Comment by Pantela777** [comment]
Thanks for all, but I need help to query builder where need check **if** syntax...
Please anybody write me solutions...

**Comment by knbv** [comment]
http://php.net/manual/en/language.control-structures.php
->
http://php.net/manual/en/control-structures.if.php

**Comment by jstrobel** [comment]
@Pantela777  It think https://davidwalsh.name/php-shorthand-if-else-ternary-operators this will lead you in the right direction.

**Comment by jstrobel** [comment]
No feedback until 18 days. I close this issue. If it isn't fixed or you have question please reopen it. Thanks.
