### ISSUE TITLE
400 Error redirect not work

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#170]
I have `application/classes/HTTP/Exception/404.php`, it's work
```
class HTTP_Exception_404 extends Kohana_HTTP_Exception_404 {
    public function get_response()
    {
        $response = Response::factory()
            ->status(404)
            ->headers('Location', URL::site('/'));

        return $response;
    }
}
```

Also I try to add similar error status `application/classes/HTTP/Exception/400.php` error, but code is not work, not redirect to **/** page

```
class HTTP_Exception_400 extends Kohana_HTTP_Exception_400 {
    public function get_response()
    {
        $response = Response::factory()
            ->status(400)
            ->headers('Location', URL::site('/'));

        return $response;
    }
}
```
`failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request`
Why...?
Also I know can use 1 controller, and with **switch/case** check status error...

**Comment by jstrobel** [comment]
Works for me if i throw a throw HTTP_Exception::factory(400, 'Error400'); in a Controller.

**Comment by jstrobel** [comment]
No feedback until 18 days. I close this issue. If it isn't fixed or you have question please reopen it. Thanks.
