### ISSUE TITLE
Can't disable exception messages in production mode

### ISSUE THREAD

**Issue by valtonia** [koseven/koseven#172]
Hi,

Setting _errors_ to false in the Konana::init call during bootstrap is meant to suppress exception traces being shown (e.g. in production environment) but it is not working.

I've tracked the problem to _system/clases/Kohana/Request/Client/Internal_ line 119. In versions of Kohana prior to 3.3.0 this line read:

`throw Exception($e)`

but has now been changed to:

`$response = Kohana_Exception::_handler($e);`

This seems to make the exception always show no matter the setting of _errors_ in Kohana::init.

Am I missing something in how this is supposed to work?

**Comment by errotan** [comment]
You can set an alternative view for production in bootstrap:

`if (Kohana::$environment === Kohana::PRODUCTION)`
`{`
`Kohana_Exception::$error_view = 'prod_error_page';`
`}`

**Comment by knbv** [comment]
Also you can override system methods, here is a simple example:

bootstrap.php

```
Kohana::$environment = Kohana::PRODUCTION; // PRODUCTION, STAGING, TESTING, DEVELOPMENT

Kohana::init([
   // ...
    'errors' => Kohana::$environment === Kohana::DEVELOPMENT ? TRUE : FALSE,
    'profile' => Kohana::$environment === Kohana::DEVELOPMENT ? TRUE : FALSE,
    'caching' => Kohana::$environment === Kohana::DEVELOPMENT ? FALSE : TRUE,
    // ...
]);
```

/application/classes/Kohana/Exception.php

```
<?php defined('SYSPATH') OR die('No direct script access.');

class Kohana_Exception extends Kohana_Kohana_Exception
{
    public static function _handler(Exception $e)
    {
        if (Kohana::$errors)
        {
            // Show the normal Kohana error page.
            $response = parent::_handler($e);
        }
        else
        {
            // Log the exception
            parent::log($e);

            // Generate a nicer looking "Oops" page.
            $response = Response::factory()
                ->status(500)
                ->headers('Content-Type', 'text/plain')
                ->body('Error Exception');
        }

        return $response;
    }

}
```

/application/classes/HTTP/Exception.php

```
<?php defined('SYSPATH') or die('No direct script access.');

class HTTP_Exception extends Kohana_HTTP_Exception
{
    public function get_response()
    {
        // Log the exception
        Kohana_Exception::log($this);

        if (Kohana::$errors) 
        {
            // Show the normal Kohana error page.
            return parent::get_response();
        }
        else 
        {
            // Generate a nicer looking "Oops" page.
            $response = Response::factory()
                ->status($this->getCode())
                ->headers('Content-Type', 'text/plain')
                ->body('HTTP Exception');

            return $response;
        }
    }
}
```

https://docs.koseven.ga/guide/kohana/errors

**Comment by jstrobel** [comment]
@valtonia Can we close this issue? Are you fine with the answers? Did it work for you?

**Comment by valtonia** [comment]
@jstrobel Yes you can close this issue, the suggested did work.  

Something to note though: I feel that this solution does rather miss the point of disaster recovery by relying on the framework.  If the exception is in the framework itself, or any of the modules involved in the production of a response page (e.g. mustache) then this won't work.  In the end, I opted to not use the code suggested here, but instead I patch the system to restore the old behaviour which allows me to catch any exceptions without any reliance on the framework or associated modules.

Thanks to everybody who helped with this though - I do appreciate you spending your time answering my question.

**Comment by jstrobel** [comment]
Thanks for the note. I will close the issue.
