### ISSUE TITLE
Wrong path for DOCROOT for minion tasks

### ISSUE THREAD

**Issue by Evoluty** [koseven/koseven#174]
Hey just a little fix to do with DOCROOT const.

The path is wrong when running minion tasks from the root directory :   
`./modules/minion/minion TaskToRun`   

The path is only right when running tasks from the module directory.
It needs to be absolute and not relative to be right everywhere.

I'll do a PR to fix this.

**Comment by knbv** [comment]
I have the following directory structure:

/var/www/username/data/www/example.com/

Let's write a small test:

/application/classes/Task/Test.php

```
class Task_Test extends Minion_Task
{
    protected function _execute(array $options)
    {
        Minion_CLI::write(DOCROOT);
    }
}
```
Results:
1)
index.php: 
`define('DOCROOT', realpath('../').DIRECTORY_SEPARATOR);`

result: 
`/var/www/username/data/www/`

2)
index.php: 
`define('DOCROOT', realpath(__DIR__.'/../').DIRECTORY_SEPARATOR)`

result: 
`/var/www/username/data/www/`

Both options work incorrectly, but there is one more option:

3)
index.php: 
`define('DOCROOT', realpath(dirname(__FILE__)).DIRECTORY_SEPARATOR)`

result: 
`/var/www/username/data/www/example.com/`

Check it out for yourself

Also, to run a task from the root directory, you can use this command:
`path/to/index.php --task=Test`
or copy the file `/modules/minion` to the root directory

**Comment by Evoluty** [comment]
Not really sure how and from where you are running the task.  

I just made a fresh clone, enabled minion tasks (in the application/bootstrap.php), created the same task as you in application/Task and I run with `./modules/minion/minion Test`

Here are the results that I have: 

1. With the current way `define('DOCROOT', realpath('../').DIRECTORY_SEPARATOR)` 
Result: `/Users/franck/Desktop/`

2. With my version `define('DOCROOT', realpath(__DIR__.'/../').DIRECTORY_SEPARATOR)`
Result: `/Users/franck/Desktop/koseven/`

3. With your version `define('DOCROOT', realpath(dirname(__FILE__)).DIRECTORY_SEPARATOR)`
Result: `/Users/franck/Desktop/koseven/public/`

I also tried with `php public/index.php --task=Test` from the root of the project and got the same results.

Don't know why we are getting different results.
What do you think about that ?

**Comment by knbv** [comment]
Sorry, there was an error, I do not use the public folder in the project where the tests were run. I approved your corrections.

**Comment by Evoluty** [comment]
Thanks for the feedbacks and the tests.  
Glad we sort that out 😄

**Comment by piotrgolasz** [comment]
@Evoluty I posted some info in the PR. Can you update it?

**Comment by errotan** [comment]
This has been fixed. Thanks guys!
