### ISSUE TITLE
Using DISTINCT with ORM

### ISSUE THREAD

**Issue by bkosun** [koseven/koseven#177]
A simple ORM query::
`ORM::factory('Order')->distinct(TRUE)->count_all();`

Will generate the following SQL query:
`SELECT DISTINCT COUNT(order.id) AS records_found FROM orders AS order`

At least, the correct query looks like this:
`SELECT COUNT(DISTINCT order.id) AS records_found FROM orders AS order`

Another request:
`$orders = ORM::factory('Order')->distinct(TRUE)->find_all();`

Will generate the following SQL query:
`SELECT DISTINCT order.id AS id, order.client_id AS client_id FROM orders AS order`

https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L2191
https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM.php#L1815

What if You want to make the sample unique records by a certain field?

For example:
`SELECT COUNT(DISTINCT order.client_id) AS records_found FROM orders AS order`
OR
`SELECT COUNT(DISTINCT order.client_id, order.method_id) AS records_found FROM orders AS order`

How to do it with ORM? What do You think? Should we fix it?

**Comment by piotrgolasz** [comment]
This can't be done with ORM, but you can do it with builder and DB::expr()

**Comment by knbv** [comment]
I know, but this can be done if we improve some of the ORM functions

**Comment by jstrobel** [comment]
@knbv I do not have this often so far, so i did it like @piotrgolasz with builder an DB::expr() too. If you want you can do a suggestion what you want to change and post it to the group i think. What do you mean?

**Comment by knbv** [comment]
However, the bug exists despite the fact that You did not notice, so there is a need to discuss this issue in the community before taking any decision.

**Comment by knbv** [comment]
@jstrobel However, the bug exists despite the fact that You did not notice, so there is a need to discuss this issue in the community before taking any decision.

**Comment by jstrobel** [comment]
@knbv No i am not afraid of open issues ;) And it wasn‘t my intention to move it to archive - i hope it didn‘t sounded like this.

**Comment by bato3** [comment]
@jstrobel Only one thing, what we can do in this case is throwing error in case when an ignorant programmer use: `distinct(TRUE)` and `count_all()` in the same time. ;-)

**Comment by knbv** [comment]
@bato3 And what method of generating the required SQL-query do you propose to use?

**Comment by bato3** [comment]
Add method to your model with content:
```
return DB::query(Database::SELECT, 'SELECT COUNT(DISTINCT order.id) AS records_found FROM orders AS order')
->execute($this->_db)
->get('records_found');
```

or query builder version

```
return DB::Select([DB::Expr('COUNT(DISTINCT id) '),'records_found'])
->from($this->_table_name)
->execute($this->_db)
->get('records_found');
```


BTW: don't use ORM::find_all() if you want only display results. Adding ORM is very slow. Change it to `DB::select()->execute()->as_array()` is faster

**Comment by knbv** [comment]
I know how to do this with the query builder, however I want to use ORM. This is easily fixed in the ORM module, why do I need these crutches?

To fix the count_all method, you need to do something like this:

/application/classes/ORM.php

```
    public function count_all()
    {
        $is_distinct = FALSE;

        $selects = array();

        foreach ($this->_db_pending as $key => $method)
        {
            if ($method['name'] == 'distinct')
            {
                $is_distinct = TRUE;

                // Ignore any selected columns for now
                $selects[$key] = $method;
                unset($this->_db_pending[$key]);
            }

            if ($method['name'] == 'select')
            {
                // Ignore any selected columns for now
                $selects[$key] = $method;
                unset($this->_db_pending[$key]);
            }
        }

        if ( ! empty($this->_load_with))
        {
            foreach ($this->_load_with as $alias)
            {
                // Bind relationship
                $this->with($alias);
            }
        }

        $this->_build(Database::SELECT);

        if ($is_distinct)
        {
            $fields = array();

            foreach ($selects as $key => $method)
            {
                if ($method['name'] == 'distinct')
                {
                    $fields += $method['args'];
                }
            }

            $fields = array_map(function($value){

                if (is_array($value))
                {
                    $value = array_shift($value);
                }

                return $this->_db->quote_column($this->_object_name.'.'.$value);

            }, $fields);

            $records = $this->_db_builder->from(array($this->_table_name, $this->_object_name))
                ->select(array(DB::expr('COUNT(DISTINCT '.implode(',', $fields).')'), 'records_found'))
                ->execute($this->_db)
                ->get('records_found');
        }
        else
        {
            $records = $this->_db_builder->from(array($this->_table_name, $this->_object_name))
                ->select(array(DB::expr('COUNT('.$this->_db->quote_column($this->_object_name.'.'.$this->_primary_key).')'), 'records_found'))
                ->execute($this->_db)
                ->get('records_found');
        }

        // Add back in selected columns
        $this->_db_pending += $selects;

        $this->reset();

        // Return the total number of records in a table
        return (int) $records;
    }
```

This function generates the correct SQL queries. By the way, this is not a new problem, the network has a lot of complaints. Unfortunately now there is no time to give a detailed report.

**Comment by bato3** [comment]
NO!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Query like `SELECT DISTINCT f1, f2 FROM tbl` is correct!

For one exception, you can not change the usual practice.

Next correct example:
`ORM::factory('tbl')->goup_by('field')->goup_by('field_2')->count_all();`

If you really want this behavior, then overwrite the method in APPLICATION. Why do not you notice that all other participants in the discussion are against this change?

BTW: Example `SELECT COUNT(DISTINCT order.client_id, order.method_id) AS records_found FROM orders AS order` is incorrect, `count()` allow only one argument.

# Know difference:

`SELECT count(*) FROM tbl` - count all rows
`SELECT count(col) FROM tbl` - count all rows where `col` IS NOT NULL
`SELECT count(DISTINCT col) FROM tbl` - counts the occurrence of different values from `col` (eg. client_id, as foreign key)
`SELECT DISTINCT col FROM tbl` - display different values from `col`
`SELECT DISTINCT count(col) FROM tbl`  - stupid, but still correct
`SELECT count(DISTINCT col, col_2) FROM tbl` - syntax error

**Comment by knbv** [comment]
Firstly - do not freak out!

`Query like SELECT DISTINCT f1, f2 FROM tbl is correct!`

I understand, but how does this relate to an existing problem?

```
Next correct example:
ORM::factory('tbl')->goup_by('field')->goup_by('field_2')->count_all();
```

How can this help? Do not you distinguish the functions group_by and distinct? Have you tried using such a query? You do not worry that it request will return multiple rows?

`If you really want this behavior, then overwrite the method in APPLICATION. Why do not you notice that all other participants in the discussion are against this change?`

Calm down, I already did, for this I do not need your advice.

Who exactly is against making corrections (except for you)? We discuss here everything that we consider necessary.

` SELECT DISTINCT count(col) FROM tbl - stupid, but still correct`

This DISTINCT does not affect anything

BTW: Example SELECT COUNT(DISTINCT order.client_id, order.method_id) AS records_found FROM orders AS order is incorrect, count() allow only one argument.

` SELECT count(DISTINCT col, col_2) FROM tbl - syntax error`

Sometimes it's better to chew than to talk. Read the documentation.
https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_count-distinct

Some other discussions on this problem:
https://github.com/kohana/orm/issues/128
http://forum.kohanaframework.su/viewtopic.php?p=4471

Sorry, but I do not have the desire to discuss this problem with you, if you do not understand its essence. Thank you!

**Comment by piotrbaczek** [comment]
To sum up this conversation:

- Last post is from Jan 17th

- I see no need to make such compilicated queries to ORM. Surely ORM is not for handling every possible purpose, but only to handle simple to medium hard queries. Of you want to create super compilicated query than you'll have to write some SQL
- I see no reason why you can't overwrite ORM class in your application by your needs thus solving your problem
- Since ORM and Kohana/Koseven is old and rather maintained for bugs than new features, I would recommend moving to something like zend-db or doctrine

Therefore after all those arguments this topic is closed.
