### ISSUE TITLE
Compatible with PHP 7.2?

### ISSUE THREAD

**Issue by Daijobou** [koseven/koseven#178]
PHP 7.2 is out of the box. http://php.net/archive/2017.php#id2017-11-30-1

Anyone tested it with kohana? :)

**Comment by errotan** [comment]
It passes unit tests. Created pull request #180

**Comment by piotrgolasz** [comment]
merged. Thank you @errotan

**Comment by Daijobou** [comment]
Is here somthing missing?

http://php.net/manual/de/function.mcrypt-create-iv.php => Warnung
This function was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0.

file: koseven\modules\encrypt\config\encrypt.php
Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP)

So the encrypt module is not working with php7.2. Default is mcrypt, see https://github.com/koseven/koseven/blob/devel/modules/encrypt/config/encrypt.php
