### ISSUE TITLE
Userguide module not compatible with PHP7.1

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#18]

**Comment by Hyaena** [comment]
Where is this bug? Is it “[] operator not supported for strings” as seen in attached screenshot?

![userguide-error](https://cloud.githubusercontent.com/assets/383428/22156417/6d3992a8-df33-11e6-8375-e9ca11b8e3c9.png)

**Comment by svenbw** [comment]
The error says that self::$_toc is a string and you can't push data on a string.
Initializing the variable as array should fix this... Or at least I think so

**Comment by neo22s** [comment]
Thanks @Hyaena  https://github.com/koseven/koseven/pull/25

I need to test on PHP7.1 in deep still xD then I will close the issue.

Anyone wants to test too?

**Comment by neo22s** [comment]
working!! https://docs.koseven.ga/

PHP7.1  thanks
