### ISSUE TITLE
System error page should be rewritten

### ISSUE THREAD

**Issue by satanch** [koseven/koseven#181]
https://github.com/koseven/koseven/blob/devel/system/views/kohana/error.php

* Why page does not contain html and body? This view can be embed?
* Koggle JavaScript code should be rewrited for modern browsers

**Comment by klunker** [comment]
As I know this template view only a little part _layer_ what used Controller_Template in base

**Comment by bato3** [comment]
This View is used always when error appear, so you can get almost normal page with one block replaced by error.

I never paid attention to what causes it, but it seems to be the case when I use `Vew::render()` in the Controller.
