### ISSUE TITLE
Create kodoc2 project and website project?

### ISSUE THREAD

**Issue by satanch** [koseven/koseven#182]
Shoud we create kodoc2 project and webiste project at koseven account for website and new documentation pages development?

**Comment by jstrobel** [comment]
I think this is a good idea. What do others think?

**Comment by WinterSilence** [comment]
Hosting = money - need find cash before, may be add link to donate service?  
I think the first priority - create roadmap.

**Comment by puchkovk** [comment]
May be, Github wiki? I'm ready to spent some time to help. Docs is really good thing.

**Comment by jstrobel** [comment]
@puchkovk What do you think? Shouldn't we update the userguide module? I had a look into that, we could do a doc-fork to start? Change design and update the docs?

**Comment by errotan** [comment]
Instead of userguide module we could use already working tools like sphinx. The userguide docs should be moved to a separate repo in this case. The current markdown based files can be easily rewritten to rst format. For API documentation sphinx can autogenerate static pages. readthedocs.io could be used for hosting these docs for free. Using separate docu repos with readthedocs localized translations of userguides can be made. Also on readthedocs you can download the whole documentation as PDF if you use sphinx.

**Comment by puchkovk** [comment]
Sphinx is exellent thing, and I use it in some projects. If community need it - i`ll will help. But, may be better thing to be focused for better content, and leave things simple? 

I mean - may be better to have good docs in old format.

@jstrobel - updating a userdocs module is right way, for this moment. You are right.

PS. Good docs is a thind I`m dream about. )))

**Comment by errotan** [comment]
I also agree to keep userguide module for the time being and maybe consider something else later.

**Comment by WinterSilence** [comment]
Need add generator for create docs in external modules.

**Comment by puchkovk** [comment]
@jstrobel Hello! 
>  we could do a doc-fork to start
May be, we should create docs branch?

And, what things are first to be coded? May be - to update all links in docs? 

Need some advices in case "how to begin" )))

**Comment by jstrobel** [comment]
@puchkovk Yes you are right i meant a branch too :)
Update all links and replace kohana with koseven would be great.
I will have a look in the design. What do you mean should we do the design more like koseven.ga?

**Comment by puchkovk** [comment]
> Update all links...

I`ll try to do it in some days.

> branch

Let`s create it :)

> What do you mean should we do the design more like koseven.ga?

Why not? Nice and clear. 

Also, docs [link](https://docs.koseven.ga/) is absent on koseven.ga. Is it because of mistakes?

**Comment by jstrobel** [comment]
Perfect. I will have a look these days too.

Right now there is a doc link in text of the page. We can add another at the top to make it more visible

**Comment by raelgc** [comment]
For the project website, why not just use a new repo with the free github pages?

**Comment by jstrobel** [comment]
Do you mean https://github.com/koseven/koseven.ga ?

**Comment by toitzi** [comment]
Idle for a time.
Current Status:

[Website](https://koseven.ga)- [GitHub](https://github.com/koseven/koseven.ga) for it
Documentation is done via userguide module - [Website](https://docs.koseven.ga)

Doc links are fixed and getting updated from time to time. I don't see a need for this issue anymore. If someone wants to maybe discuss this or wants to move to another solution, feel free to reopen.
