### ISSUE TITLE
realpath on hosting without executable permissions

### ISSUE THREAD

**Issue by klunker** [koseven/koseven#186]
Hi to anyone in index.php on line 103
```
define('APPPATH', realpath($application).DIRECTORY_SEPARATOR);
define('MODPATH', realpath($modules).DIRECTORY_SEPARATOR);
define('SYSPATH', realpath($system).DIRECTORY_SEPARATOR);
```

function **realpath** Returns canonicalized absolute pathname, but the running script must have executable permissions on all directories in the hierarchy, otherwise realpath() will return FALSE.

Where are many hosting whith non-executable repmissions on all hierarchy.

So I have proposition to remove or replece **realpath** function with **ko7_realpath**:
```
function ko7_realpath($path) {
        $path = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $path);
        $parts = array_filter(explode(DIRECTORY_SEPARATOR, $path), 'strlen');
        $absolutes = array();
        foreach ($parts as $part) {
            if ('.' == $part) continue;
            if ('..' == $part) {
                array_pop($absolutes);
            } else {
                $absolutes[] = $part;
            }
        }
        return implode(DIRECTORY_SEPARATOR, $absolutes);
    }
```

**Comment by piotrgolasz** [comment]
```
chmod +x -R ./
```

**Comment by piotrgolasz** [comment]
Also i believe this is something specific to your hosting, and not directly related to Kohana, so you could overwrite this in your software. I see no need to implement this functionality into Kohana.
