### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by piotrgolasz** [koseven/koseven#19]
During last almost 3 years of using Kohana i got into some issues with subdomains.
I can without problems create a multi-application system, where I have different "application" folder for frontend, api, user, backend

by using .htaccess
`#API
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{HTTP_HOST} (www\.)?api\.*
RewriteRule .* api.php/$0 [PT,L]

#FRONTEND
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php/$0 [PT,L]`

however there is no easy way to inject subdomains into URL::site(). This could be useful for example if being on my api.* subdomain I would like to refer to docs.*/issue/324 problem for the api.

**Comment by neo22s** [comment]
I use at yclas.com subdomains without issues, I am not sure if I understood your issue. The problem is building URLs?

**Comment by piotrgolasz** [comment]
yes, exactly

**Comment by roman-huliak** [comment]
Kohana has very poor subdomains support. Applications using subdomains is many times too dificult. Subdomain can be dynamic or static  (dynamic=locations,categories,usernames). This need smart route filters, better route matcher.
On github is subdomain module for kohana but only for basic usage.
