### ISSUE TITLE
Session Lifetime

### ISSUE THREAD

**Issue by quincykwende** [koseven/koseven#190]
For some weird reason my Auth session stopped expiring; However, I also notice the lifetime string in the auth.php config is not used;
``` 
'lifetime'     => 1209600,
```

Does the config handle this; or do i need to hard code it 

Thanks

**Comment by piotrgolasz** [comment]
When you login, what expiration date does your cookie have?

**Comment by quincykwende** [comment]
Sorry for the late reply. 

Thanks for your interesting in assisting; in turned out the weird reason was my auto logout function --- that is if you logout on one tab if should log you out/redirect on all other open tabs.

it keeps a live connection -->heart bits to the server and server response checking the user's session; therefore you are always active. I'm thinking on how to ignore this particular function or make it stop after 5minutes on a given page.

Thanks

**Comment by garbinmarcelo** [comment]
Hi,
Sorry to reply to this old topic. But I'm looking for material about Session Lifetime, I'm using Kohana v2.3.4.

I have a legacy project where the Auth module is not used, only sessions which are defined to use cookie as driver.

So I can't have the auto_login method, would there be a way to do this manually? If yes, what would be the best way? I would like to keep the user logged in without losing the sessions set.

Every help is welcome.

Thanks
