### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by quincykwende** [koseven/koseven#191]
assuming I want to create a route like this; 
http://example.com/dynamic_string/controller/action/param

What's the cleanest way to do it with routing.

NB: Can do it by playing with the system routing or extending it; not sure it is the best way; Will love any ideas on how to go about it with regex at the level of bootstrap.php/init.php

**Comment by bato3** [comment]
Um, why you don't read doc? 
https://docs.koseven.ga/guide/kohana/routing#creating-urls-and-links-using-routes

And remember all tutlrials for kohana 3 are valid. Before, read this: https://docs.koseven.ga/guide/kohana/upgrading-from-3-3-3-1 and this https://docs.koseven.ga/guide/kohana/upgrading
