### ISSUE TITLE
find_file taking long time to load files.

### ISSUE THREAD

**Issue by farazilu** [koseven/koseven#192]
`find_file` function is taking almost 1sec even when cache is enabled.

I debugged the system and noticed that when `Kohana::init` is called in bootstrap, `Kohana_Core` class can't find `Kohana_Cache` file so it use file_cache function and try to load .txt file on `Kohana_Core` line **892**.

But when shutdown_handler is called and it try to write file_cache it can find `Kohana_Cache` and it use it so a cache file is created `Kohana_Cache_File` class with .cache file.

This mean when `Kohan::init` is called it never use cached file and build files list every time. 
So my solution is to update Koahan_Core class change default extension 

I try to move Kohana::modules call before Kohana::init but userguide module init.php throw errors. 

both `Kohana_Core` and `Kohana_Cache_File` are using `sha1` function to hash file name but `Kohana_Cache` use $prefix so names does not match.

So even changing file extension in  `Kohana_Cache` to .cache is not working.

Any solutions?

**Comment by farazilu** [comment]
I noticed that there is big difference how `Kohana_Cache_File` and `Kohana_Core::file_cache` hash id name and read file contents.

`Kohana_Core::file_cache` just hash file name using sha1 but `Kohana_Cache_File` has 2 step approach. hash id name, find cache prefix, concatenate both and hash again.  

Than  `Kohana_Core::file_cache` just read file contents and unserialize contents but `Kohana_Cache_File` read 1st line check expire time and than read rest of file into variable and then unserialize that data. 

So we can replicate this functionality in `Kohana_Core::file_cache` but we can't read cache prefix that is set in config. 
and if user change default prefix it will not work.

**Comment by piotrgolasz** [comment]
Please provide a pull request. And unittests. Thank you.
