### ISSUE TITLE
Add info about ORM_Behavior

### ISSUE THREAD

**Issue by WinterSilence** [koseven/koseven#197]
Please add examples in guide and more comments for class. 
How use it?

**Comment by svenbw** [comment]
Details about the behaviours can be found in the [ORM documentation](https://github.com/koseven/koseven/blob/master/modules/orm/guide/orm/behaviors.md)

**Comment by WinterSilence** [comment]
@svenbw Thanks! 
Please update site, [https://docs.koseven.ga/guide/orm/] - old version.

**Comment by svenbw** [comment]
Updated info is available.
