### ISSUE TITLE
[php 7.2] replace `mcrypt` by `sodium`

### ISSUE THREAD

**Issue by bato3** [koseven/koseven#200]
http://php.net/manual/en/book.sodium.php

`sodium` is now default crypt library for PHP. I'm think, that we need encryption module, that use this library. 
http://php.net/manual/en/sodium.installation.php

**Comment by Daijobou** [comment]
I agree and for PHP 7.2 in meantime it should change https://github.com/koseven/koseven/blob/devel/modules/encrypt/config/encrypt.php to openssl

		'type'   => 'openssl',
		'cipher' => 'AES-256-CBC',

Because in PHP 7.2 with actual config: Use of undefined constant MCRYPT_RIJNDAEL_128

**Comment by bato3** [comment]
@Daijobou If you install mcrypt from PECL, you will can use `MCRYPT_RIJNDAEL_128`

Openssl is also not good idea, because it must be installed in OS, and also PHP must be compiled for it.

As I wrote: from php7.2 sodium is in PHP core (and replace outdated (7.1) / removed (7.2) MCRYPT)

**Comment by neo22s** [comment]
hello!

Someone wants to do the sodium implementation?

**Comment by toitzi** [comment]
https://github.com/koseven/koseven/pull/243

Handels this

**Comment by toitzi** [comment]
Fixed and merged into devel with #308
