### ISSUE TITLE
Travis-CI tests do not pass

### ISSUE THREAD

**Issue by knbv** [koseven/koseven#202]
Even with a minor change, Travis-CI tests will fail because the wrong configuration is installed.

There are already PRs that solve this problem, but they are not accepted, therefore further work can not be continued.

**Comment by jstrobel** [comment]
Can you help me a little, i am not so into travis. You mean the Travis-Config is wrong? Because doesn't use PHP7.2?

**Comment by errotan** [comment]
Travis uses PHPUnit 7 for PHP 7.2 for some time now. The unit tests are not compatible with PHPUnit 7. The travis config is fixed in my pr #196 but it is not accepted. :(

**Comment by jstrobel** [comment]
I have seen there where 2 reviewers so i merged it.

**Comment by jstrobel** [comment]
@errotan And thanks for the infos here!

**Comment by knbv** [comment]
Thank you! Now you need to restart the test for this PR #199. Do you have access to Travis-CI?

**Comment by jstrobel** [comment]
@knbv You are right, i restarted it and closed it .
