### ISSUE TITLE
phing in composer.json

### ISSUE THREAD

**Issue by errotan** [koseven/koseven#203]
I see phing in composer.json but no evidence that it is used. Can it be removed?

**Comment by jstrobel** [comment]
These are the only places i find some phing-relations:
> CONTRIBUTING.md: * Install [Phing](http://phing.info)
> CONTRIBUTING.md: * Finally, run `phing test`
> composer.json:    "phing/phing": "^2.16"
> modules/unittest/guide/unittest/testing_workflows.md:The two more popular CI servers are [Hudson](https://hudson.dev.java.net/) and [phpUnderControl](http://www.phpundercontrol.org/about.html), both of which use [Phing](http://phing.info/) to run the build tasks for your application.

**Comment by errotan** [comment]
I checked that previously kohana used phing for releases and other stuff. The build.xml for phing is no longer present so posting a pr for removing any remaining references #207
