### ISSUE TITLE
should we set http status to 500 after an exception in View?

### ISSUE THREAD

**Issue by errotan** [koseven/koseven#206]
If an exception occurs during View rendering http status is not changed. As seen in this method: https://github.com/koseven/koseven/blob/b55b71c60105e7ef2786e48768d39e00298bdc4a/system/classes/Kohana/View.php#L247 Should we put a `if ( ! headers_sent()) { header('status: 500'); }` inside the catch block to indicate failure?

**Comment by WinterSilence** [comment]
@koseven 
1. https://en.wikipedia.org/wiki/Single_responsibility_principle
2. https://github.com/koseven/koseven/blob/b55b71c60105e7ef2786e48768d39e00298bdc4a/system/classes/Kohana/Kohana/Exception.php#L124

**Comment by errotan** [comment]
You are completely right about the first part. Unfortunately an error in view does not set the main response's http status to 500. Reproduction steps:

1. download fresh koseven
2. delete install.php
3. change this line `$this->response->body('hello, world!');` in welcome controller to `$this->response->body(View::factory('test'));`
4. create test.php with content `<?php echo $x;`
5. start local server `php -S 127.0.0.1:3000 -t public` and visit in browser

I have spent many hours on this and haven't found a nice solution.

**Comment by errotan** [comment]
Finally came up with something. #208 What do you guys think about it?

**Comment by WinterSilence** [comment]
@errotan need return string at error too.

**Comment by errotan** [comment]
Putting `return` before `Kohana_Exception::handler($e)` would false assume users that the method should return something which infact not. On the other hand putting a `return ''` at the end of catch block also questionable because it will never be reached. Right?

**Comment by WinterSilence** [comment]
@errotan 
~~~
function nope() {
	echo 'Right?';
	return false;
}
~~~

**Comment by errotan** [comment]
:) so what do you suggest?

**Comment by WinterSilence** [comment]
`return ''` or `return (string)Kohana_Exception::handler($e);`

**Comment by errotan** [comment]
Updated.
