### ISSUE TITLE
koseven is not auto updating on packagist

### ISSUE THREAD

**Issue by errotan** [koseven/koseven#222]

**Comment by jstrobel** [comment]
I have changed the Packagist-Settings now to my account. I don't know if the user which was added changed his API-Key or something like this. Let's have a look.

**Comment by errotan** [comment]
There has been a commit in the devel branch, but packagist still points to 068e732.

**Comment by jstrobel** [comment]
Seems because i am not the owner or maintainer of the package it failed. Will have a look.

**Comment by jstrobel** [comment]
Contacted the user which is seem is the maintainer, and i contacted packagist what the workflow for this is.

**Comment by jstrobel** [comment]
Packagist added me as maintainer too so i hope with the next update it's update will be triggered.

**Comment by jstrobel** [comment]
Was added to maintainer list. Got an error from packagist. Fixed the licence after recheck of the right one with @errotan . Let's see.

**Comment by errotan** [comment]
Great. Thanks!
