### ISSUE TITLE
Next release 3.3.7

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#23]
To keep the same semantic version as Kohana, lets do Koseven 3.3.7?

**Comment by svenbw** [comment]
Perfect!
However there might be some conflict if Kohana itself releases a new version (but I doubt this will happen).

**Comment by jstrobel** [comment]
+1 Yes let's keep the same semantic.

**Comment by neo22s** [comment]
ok I keep this open until we do the release.

**Comment by Gazoo** [comment]
The old Kohana is no longer. 
http://discourse.kohanaframework.org/t/kohana-retirement-2017-07-01/1277

**Comment by uBizzy** [comment]
Congrats! I'll definitely follow this project and do all my best to help the development and bug fixes.

**Comment by satara** [comment]
Thanks for keeping up with Kohana, I still use it a lot!

**Comment by piodro** [comment]
Cheers for that idea!

**Comment by neo22s** [comment]
https://github.com/koseven/koseven/releases/tag/3.3.7
