### ISSUE TITLE
Add repository for new site koseven.ga

### ISSUE THREAD

**Issue by WinterSilence** [koseven/koseven#230]
> You can consult this list at kohana-modules.com

Also fix link or title.

**Comment by neo22s** [comment]
what do you mean new repository? thanks

**Comment by WinterSilence** [comment]
Base github repository as for old site https://github.com/koseven/kohanaframework.org

**Comment by neo22s** [comment]
we have https://github.com/koseven/koseven/tree/gh-pages

**Comment by WinterSilence** [comment]
@neo22s why here? its used in other repo? i think it's strange - use branche as repo

**Comment by neo22s** [comment]
It was created like that as per github instructions back in the time to be able to use their templates. Not any other reason. Feel free to create a repo and move all. I do not have time to do it nor to discuss it.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/
https://pages.github.com/

**Comment by neo22s** [comment]
sorry closed, by clicking wrong button.

Anyone does not like it can change it, got no problem. thanks

**Comment by WinterSilence** [comment]
@neo22s its normal - no problem, i close.

**Comment by neo22s** [comment]
I actually think is better to have own repo if it's possible to keep it all as it is. so leave it open and someone will do it ;)

**Comment by WinterSilence** [comment]
@neo22s someone? i see only one admin and dont know who is mr.koseven)

**Comment by WinterSilence** [comment]
@neo22s thanks, but i dont planed work on improving koseven - i write shop cms based on kohana and come to see security fixes. At start my work i think before refactore kohana 3.4 but i dont have so many time and start work as is. I think koseven in current version stillborn child. Need full refactoring - change code style, add namespaces, remove static wherever its possible. Its need for normal integration with other modern libraries.

**Comment by jstrobel** [comment]
Done ✔
https://github.com/koseven/koseven.ga
