### ISSUE TITLE
Modern router

### ISSUE THREAD

**Issue by WinterSilence** [koseven/koseven#231]
Modern router https://gist.github.com/WinterSilence/a6fb75a990c3b3ecd0a48bd9831780d0 , may be in future this code be usefull :)

**Comment by errotan** [comment]
It would be great if you could make a composer package from it. Than it can be integrated easier. Closing for now.

**Comment by WinterSilence** [comment]
@errotan 
1. not complete & tested 
2. not abstract code
3. lost if close

P.S. i know some guys from https://github.com/orgs/kohana/people , but dont know u. Why?

**Comment by errotan** [comment]
I never contributed to kohana.

**Comment by toitzi** [comment]
Idle for a long time. No PR referenced to this. Moved it to our [Forum](https://koseven.discourse.group/t/idea-modern-router-class/21).
