### ISSUE TITLE
Multi-byte string

### ISSUE THREAD

**Issue by saruman** [koseven/koseven#233]
Hello community.
I have a critical issue with alphabetic characters, such Spanish accents.
Right now in ORM there is a private function called "run_filters".  
In my model I have some filters, such strtolower.  When I pass a text using this filter, the output is wrong (non utf8).

For example: HOLA MAMÁ, the result will be: hola mam??

If I use mb_strtolower, the problem is gone and the result is: hola mamá. (OK).

My working filter is:

'nombre' => array(
                                //array('strtolower')
				array('mb_strtolower'),
				array('ucwords')
			),

Do I have to change all my strtolower to mb_strtolower manually or is there a better solution for my problem?

Thank you in advance.  Sorry for my English grammar.

**Comment by knbv** [comment]
Hello! You need to use the UTF8 helper methods

https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/UTF8.php#L315
https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/UTF8.php#L341
https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/UTF8.php#L367
...

A simple example:
```
class Model_User extends Model_Auth_User
{
...
    public function filters()
    {
        return [
            'first_name' => [
                ['UTF8::trim', [':value']],
                ['UTF8::strtolower', [':value']],
                ['UTF8::ucfirst', [':value']],
            ],
        ];
    }
...
}
```

**Comment by saruman** [comment]
Thank you so much @knbv <3

**Comment by knbv** [comment]
You can read the details [here](https://docs.koseven.ga/guide-api/UTF8) :)

**Comment by saruman** [comment]
@knbv sweet!
