### ISSUE TITLE
Pagination - Required route parameter not passed: directory

### ISSUE THREAD

**Issue by jrushworth** [koseven/koseven#239]
This seems almost exactly the same as issue #59.
Have  a variable `<directory>` in my route and pagination was failing with

> Kohana_Exception [ 0 ]: Required route parameter not passed: directory

Added at line 103	
```php
$this->_route_params['directory'] = $request->directory();
```` 
Sorry, don't understand enough to know whether this is a valid fix or I have something mis-configured. Any advice/corroboration would be great.

**Comment by jstrobel** [comment]
As you can see in #59 the changes are merged into the branch. Are you on the newest version?

**Comment by jstrobel** [comment]
Sorry, jumped into the other task and have overseen then that is the directory param. Can you do a PR so we can test it?

**Comment by piotrbaczek** [comment]
This should be fixed in #263

**Comment by piotrbaczek** [comment]
This missing parameter has by mistake not been added by @Azuka on 777a5e0e13204034812baf2b6b702a9623d7f78f, just to put blame 😃

**Comment by piotrbaczek** [comment]
@jrushworth Does this fix your issue. Can you maybe provide some code where this doesn't work?

**Comment by piotrbaczek** [comment]
Merged, therefore closing.
