### ISSUE TITLE
Error handlers in strict accordance with PHP 7

### ISSUE THREAD

**Issue by bkosun** [koseven/koseven#248]
Koseven installer requires PHP version at least 7.0:
https://github.com/koseven/koseven/blob/devel/public/install.php#L136

Tests for PHP 5 are not performed:
https://github.com/koseven/koseven/blob/devel/.travis.yml#L4

We can replace the error handlers in strict accordance with PHP 7?

http://php.net/manual/en/function.set-exception-handler.php

What do you think of it?

**Comment by WinterSilence** [comment]
At first need move code from Kohana_Exception to Kohana_Exception_Handler.

**Comment by WinterSilence** [comment]
P.S. sorry i dont see your PR and send my (more fixes).

**Comment by bkosun** [comment]
Your commit does not contain complete fixes for the system, it will break the work of the Minion CLI module, so the unit tests are not executed. This commit should be canceled.

https://travis-ci.org/koseven/koseven/builds/414092712

It's also worthwhile to think about not making direct commits in a branch. You can always add an issue, make a PR and wait for a review.

**Comment by WinterSilence** [comment]
@bkosun Yes, my mistake. I'm always forget about my status. :(

**Comment by chrisgo** [comment]
What should be the correct code on this line?  Not 100% sure if  all `catch (Exception $e)` should be changed to `catch (Throwable $e)`?

https://github.com/koseven/koseven/blob/devel/system/classes/Kohana/View.php#L238

With `catch (Exception $e)`, I'm getting this error

```
EMERGENCY: ErrorException [ 1 ]: Method View::__toString() must not throw an exception, caught Error: Call to undefined method
DEBUG: #0 [internal function]: Kohana_Core::shutdown_handler()
#1 {main} in file:line
```

Found this somewhere: https://github.com/kohana/core/issues/703

**Comment by errotan** [comment]
Exception implements Throwable (http://php.net/manual/en/class.exception.php) so it is safe to use either in PHP7. Use `$view->render()` instead of `(string)$view` or `$view->__toString()` everywhere to avoid this error and see usefull call traces.

**Comment by chrisgo** [comment]
Thanks for the clarification!
