### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by duncan3dc** [koseven/koseven#250]
I looked around but I couldn't find any mention of when the next release will be tagged, a lot of issues have been fixed since `3.3.7`, do you have a plan of when they'll be released?

**Comment by neo22s** [comment]
You are right we should release 3.3.8 asap ;)

**Comment by neufena** [comment]
Any update on this, it has been a few months.

**Comment by jstrobel** [comment]
@neufena Thanks for asking. The 3.3.8 is in the making now.

**Comment by errotan** [comment]
Tagged.

**Comment by neo22s** [comment]
https://github.com/koseven/koseven/tree/3.3.8
