### ISSUE TITLE
Koseven Twig ErrorException [ Fatal Error ]: Interface 'Twig_LoaderInterface' not found

### ISSUE THREAD

**Issue by tomeroto** [koseven/koseven#251]
Hi there,

I see koseven have twig wrapper modules:
[https://github.com/errotan/koseven-twig](https://github.com/errotan/koseven-twig)

I was complete installation and tested it, but it show error message like below:

`ErrorException [ Fatal Error ]: Interface 'Twig_LoaderInterface' not found`

Any solution for this?

**Comment by errotan** [comment]
Same issue (https://github.com/errotan/koseven-twig/issues/2) at my repo. This is not related to koseven core. We should discuss it there.
