### ISSUE TITLE
Redis cache

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#252]
Same as memcached. But using redis.

We can use as base https://github.com/bkhrupa/kohana-rediscache

**Comment by neo22s** [comment]
I do not think there's need of making many changes. I have adapted already the code, needs to be tested in production (tests working) and staging working fine. as soon as I am 100% sure works good I will do a PR. Basically it's copy pasting the module making few changes so it's is compatible.

**Comment by chrisgo** [comment]
I have this one too (super old with no tests unfortunately) with tagging support https://github.com/chrisgo/kohana-cache-redis
