### ISSUE TITLE
ERROR: Kohana_Exception [ 0 ]: Not an image or invalid image

### ISSUE THREAD

**Issue by DonPramis** [koseven/koseven#253]
Im having this error on my code, can anyone advise what is the cause of the error

```ERROR: Kohana_Exception [ 0 ]: Not an image or invalid image:  ~ APPPATH/kohana/modules/image/classes/Kohana/Image.php [ 112 ] in /home/linkin12/public_html/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110```

**Comment by errotan** [comment]
This is that line:

`throw new Kohana_Exception('Not an image or invalid image: :file', [':file' => Debug::path($file)]);`

In your error line there is nothing after "image:" so your $file variable is empty at that point.

**Comment by DonPramis** [comment]
im new to this can you please explain further. Thanks

**Comment by errotan** [comment]
When you create the Image object, the constructor arg is the file name. Eg.:

`$a = new Image_GD($file_path);`

Your $file_path variable is empty.

**Comment by DonPramis** [comment]
Thank you so much for your help

**Comment by neo22s** [comment]
Hello,

@DonPramis that error is due to the Validation, the image is not valid as indicated the error message.

Please the issues are for developers. Thanks

**Comment by neo22s** [comment]
@errotan thanks a lot for answering. @DonPramis it's trying by any means to get free support from yclas without following any of our simple rules, issues are for developers.

https://github.com/yclas/yclas/issues/2754

**Comment by DonPramis** [comment]
Hi Chema, I purchase 4 premium websites from yclas. I dont need free support. This error was been for long time in my four website. I found kohana in github so i msg. trying to figure out the issues. I raised this issued long time back with constantino, but still we're facing errors., and everytime we update we have problem, thats why I stop premium support.

I can purchase again a premium support if this time this can be fix. I have 4 websites having issues like this.

Thanks :), Im sorry if i made some trouble from here. I  thought i could help coz for long time this was not fix.

**Comment by neo22s** [comment]
Hello,

@DonPramis theres not any issue to be fixed at all... a client uploads an image to the system and he gets a message saying that the image is not valid, then we log the error in the error log. What do you want to fix?

Please use the proper channel you are trying to get support from yclas in koseven. regards

**Comment by DonPramis** [comment]
Okay, I will speak with Martina., and ask for bill. Thanks
