### ISSUE TITLE
PHPStorm PHP Editor config in contributing

### ISSUE THREAD

**Issue by piotrbaczek** [koseven/koseven#258]
It would be useful if someone dumped their PHPStorm config, so that we have unified code styling out-of-the-box.

I know the rules are there, but setting them up is a headache.

**Comment by piotrgolasz** [comment]
@errotan @neo22s @jstrobel @Hyaena @arkagod ?

**Comment by errotan** [comment]
I use vscode.

**Comment by neo22s** [comment]
I use sublimetext 😅

**Comment by jstrobel** [comment]
I use PHPStorm and Sublime. But my config wouldn‘t a good reference i think because of not 100% as reference.

**Comment by piotrbaczek** [comment]
@jstrobel would you like to collaborate in preparation of one?

**Comment by andrej-tkachenko** [comment]
My config for PHPStorm 2018.1
[Koseven_PHPStorm2018.1.zip](https://github.com/koseven/koseven/files/2471918/Koseven_PHPStorm2018.1.zip)

**Comment by jstrobel** [comment]
Thanks @andrej-tkachenko for sharing. @piotrbaczek lets use this a base. Where should we store stuff like this? Is it interesting to store configs for sublime, vscode?

**Comment by piotrbaczek** [comment]
I mean for start we have phpstorm config, we can aswell store other configs in contributing

**Comment by piotrbaczek** [comment]
I don't think this should be stored in current repo. Maybe koseven.ga?

**Comment by svenbw** [comment]
Can we create a separate repo for this? With a folder for each editor.
We could agree on a folder for the editor config in the root (e.g. `.editorconfig`) and add this by default to the `.gitignore`. Then everybody can copy there favorite editor in the folder, and the main Koseven repo is never "polluted".

**Comment by neo22s** [comment]
Moved conversation to the forum:

https://gitq.com/koseven/koseven/topics/5/editor-configurations
