### ISSUE TITLE
JSON field type on MySQLi driver

### ISSUE THREAD

**Issue by uBizzy** [koseven/koseven#262]
Hi everyone,

"JSON" field type is an alias for "LONGTEXT" but it's not defined on MySQLi driver on database module.

This is an easy fix and I've just made a pull request. Additionally, I don't know if it's a good option to open an issue and do a pull request at the same time. Please let me know your comments on this.

Regards.

**Comment by jstrobel** [comment]
Hi @uBizzy 
I can't see a PR for this? Can you do one so we can see what you want change?
Thanks

**Comment by uBizzy** [comment]
Hi @jstrobel, I just made a pull request ( #264  ). Let me know if there is something else I need to do. Regards.

**Comment by jstrobel** [comment]
@uBizzy I am closing this issue because the discussion moved over to your PR.
