### ISSUE TITLE
Kohana_HTTP_Exception [ 404 ]: The requested URL / was not found on this server.

### ISSUE THREAD

**Issue by xpertogo** [koseven/koseven#266]
SYSPATH/classes/Kohana/Request/Client/Internal.php [ 78 ]

73 		{
74 			if ( ! class_exists($prefix.$controller))
75 			{
76 				throw HTTP_Exception::factory(404,
77 					'The requested URL :uri was not found on this server.',
78 					array(':uri' => $request->uri())
79 				)->request($request);
80 			}
81 
82 			// Load the controller using reflection
83 			$class = new ReflectionClass($prefix.$controller);

This is the error im getting, i have managed to get it working on XAMP on windows machine, but i get this error on UBUNTU 18.10 , php7.2 , APACHE2, Please need help

**Comment by xpertogo** [comment]
this is the link 
towmydrive.ddns.net:94

**Comment by xpertogo** [comment]
.htaccess file 

## Turn on URL rewriting
RewriteEngine On

# Installation directory
RewriteBase /towmydrive7.2/

# Protect hidden files from being viewed
<Files .*>
        Order Deny,Allow
        Deny From All
</Files>

# Protect application and system files from being viewed
RewriteRule ^(?:application|modules|system)\b.* index.php/$0 [L]

# Allow any files or directories that exist to be displayed directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# Rewrite all other URLs to index.php/URL
RewriteRule .* index.php/$0 [PT]

**Comment by xpertogo** [comment]
.htaccess file

## Turn on URL rewriting
RewriteEngine On

# Installation directory
RewriteBase /towmydrive/
# Protect hidden files from being viewed
<Files .*>
	Order Deny,Allow
	Deny From All
</Files>

# Protect application and system files from being viewed
RewriteRule ^(?:application|modules|system)\b.* index.php/$0 [L]

# Allow any files or directories that exist to be displayed directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# Rewrite all other URLs to index.php/URL
RewriteRule .* index.php/$0 [PT]

**Comment by uBizzy** [comment]
If you are using the url "towmydrive.ddns.net:94", your RewriteBase on htccess file should be set to just "/".

**Comment by xpertogo** [comment]
i did that and same error

**Comment by xpertogo** [comment]
anyone here, could guide me, how to fix this?, php 5.6 the project works fine but on php7.2 im getting this error

**Comment by neo22s** [comment]
do you have mod rewrite enabled on 7.2?

**Comment by xpertogo** [comment]
yes i have

**Comment by neo22s** [comment]
can you paste the htaccess file so we can read it? using the code tags in github

**Comment by xpertogo** [comment]
## Turn on URL rewriting
RewriteEngine On

# Installation directory
RewriteBase /
# Protect hidden files from being viewed
<Files .*>
        Order Deny,Allow
        Deny From All
</Files>

# Protect application and system files from being viewed
RewriteRule ^(?:application|modules|system)\b.* index.php/$0 [L]

# Allow any files or directories that exist to be displayed directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# Rewrite all other URLs to index.php/URL
RewriteRule .* index.php/$0 [PT]

**Comment by neo22s** [comment]
I said please paste the code without markdown, I can not read it like this...

**Comment by xpertogo** [comment]
Turn on URL rewriting
RewriteEngine On
Installation directory
RewriteBase /
Protect hidden files from being viewed
<Files .*>
Order Deny,Allow
Deny From All
Protect application and system files from being viewed
RewriteRule ^(?:application|modules|system)\b.* index.php/$0 [L]
Allow any files or directories that exist to be displayed directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
Rewrite all other URLs to index.php/URL
RewriteRule .* index.php/$0 [PT]

**Comment by neo22s** [comment]
please try with https://github.com/koseven/koseven/blob/devel/public/example.htaccess

or https://github.com/koseven/koseven/blob/devel/public/example_2.4.htaccess

**Comment by xpertogo** [comment]
just tried both, same error as above

**Comment by svenbw** [comment]
Check the case of your controller class name and file name. This makes no difference in Windows but will cause failure under Linux.

**Comment by svenbw** [comment]
If your controller name MyAwsomeSite_Controller, your filename should be MyAwsomeSite.php.
If you access the page you should go to www.foo.bar/MyAwesomeSite.
So your url should match the name of the controller and filename.

Typically I use Myawsonesite_Contoller in Myawsomesite.php and can browse to www.foo.bar/myawsomesite.

**Comment by xpertogo** [comment]
ok let me try it

**Comment by uBizzy** [comment]
@xpertogo , did you solved your issue already?

**Comment by xpertogo** [comment]
not yet, still trying to, will update ,if done or anything new comes up

**Comment by JokerTX** [comment]
When I go to the link you provided, I get the directory listing. When I click /public (http://towmydrive.ddns.net:94/public/), I get the successfully tested install.php page. Are you sure your Directory is setup correctly in your site's conf file?
`<Directory /var/www/html/towmydrive/public>...</Directory>`

**Comment by xpertogo** [comment]
@JokerTX  i was trying to see if my environment passes the test, i have uploaded my files again, and im getting the same error. any help would be great

**Comment by uBizzy** [comment]
I see you have configured this default route:
```
protected _defaults => array(2) (
            "controller" => string(5) "users"
            "action" => string(5) "index"
        )
´´´
My questions are:
1. Did you have a Controller "Users" with the "action_index()" function defined?
2. **OR** do you have a module that have a Controller "Users" with the "action_index()" function defined?
