### ISSUE TITLE
koseven with more PHP7

### ISSUE THREAD

**Issue by michalpietron-coderslab** [koseven/koseven#267]
What do you think about start to rewrite the code, step by step, class by class, so that it is more modern and with more use of PHP7 capabilities. Is it possible at all? Kohana is very fast - it's a fact, but outdated :(

**Comment by uBizzy** [comment]
This is just my 5 cents about this subject:
1. **If it isn't broken, don't fix!** => For sure Koseven can be improved and updated, but I agree with @jstrobel  and most of the users here. Let's keep it simple, easy to use, fast and secure (and drop-in as kohana substitute)
2. **But I need a modern framework** => You may choose between laravel, symfony, cakepkp, ...
3. **Everyone is going other way** => Here you have http://www.phpthewrongway.com/
4. This is a little bit old video, but it's a good example: https://www.youtube.com/watch?v=DuB6UjEsY_Y
5. Additionally you may also tale a look on this project example: https://github.com/nirix/unframework

As @neo22s said repeatedly, fell free to contribute improving koseven, on the other side, you may also fork it and take your own way if you need.

**Comment by neo22s** [comment]
@uBizzy agree ;)

**Comment by jstrobel** [comment]
So like @uBizzy and @neo22s and myself are in the same direction and view on that, i will close this issue.
