### ISSUE TITLE
Kohana Minion not compatible with PHP 7.0 Exception class change

### ISSUE THREAD

**Issue by piotrgolasz** [koseven/koseven#27]
After trying to use minion on fresh out-of-box koseven, got this error:
`<h1><span class="type">ErrorException [ Warning ]:</span> <span class="message">Declaration of Kohana_Minion_E
xception::handler(Exception $e) should be compatible with Kohana_Kohana_Exception::handler($e)</span></h1>
        <div id="error58850d0d06654" class="content">
                <p><span class="file">MODPATH\minion\classes\Kohana\Minion\Exception.php [ 65 ]</span></p>
`

Hence handler(Exception $e) -> handler($e)

**Comment by neo22s** [comment]
but I think its fixed here https://github.com/koseven/koseven/pull/20

In next 3.3.7 will be added , download master and will work ;)
