### ISSUE TITLE
Copyright in footer

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#271]
It says "2008–2012 Kohana Team" what should we change it for?

----------
Searching 673 files for "2008–2012 Kohana Team" (case sensitive)

/var/www/koseven/modules/auth/config/userguide.php:
   19  
   20  			// Copyright message, shown in the footer for this module
   21: 			'copyright' => '&copy; 2008–2012 Kohana Team',
   22  		]
   23  	]

/var/www/koseven/modules/cache/config/userguide.php:
   18  			
   19  			// Copyright message, shown in the footer for this module
   20: 			'copyright' => '&copy; 2008–2012 Kohana Team',
   21  		]	
   22  	]

/var/www/koseven/modules/codebench/config/userguide.php:
   18  			
   19  			// Copyright message, shown in the footer for this module
   20: 			'copyright' => '&copy; 2008–2012 Kohana Team',
   21  		]	
   22  	]

/var/www/koseven/modules/database/config/userguide.php:
   18  			
   19  			// Copyright message, shown in the footer for this module
   20: 			'copyright' => '&copy; 2008–2012 Kohana Team',
   21  		]	
   22  	]

/var/www/koseven/modules/orm/config/userguide.php:
   18  			
   19  			// Copyright message, shown in the footer for this module
   20: 			'copyright' => '&copy; 2008–2012 Kohana Team',
   21  		]	
   22  	]

5 matches across 5 files

**Comment by errotan** [comment]
According to the license text ("Redistributions of source code must retain the above copyright notice") these lines can't be changed. But any number of additional copyright lines can be put under these.

Example: @copyright (c) 2012–2018 Koseven Team <https://github.com/orgs/koseven/people>

**Comment by neo22s** [comment]
Perfect!! Yes ;)
