### ISSUE TITLE
3.3.8 break changes

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#273]
Hello,

Found an API break change:

https://github.com/koseven/koseven/commit/05d2e8bf95c35dedc9b44509d89faed794e9820b

What sohuld we do? revert or document?

**Comment by jstrobel** [comment]
i think revert. but just my opinion

**Comment by neo22s** [comment]
for me too. and release 3.3.9 with any other bug fix we find.

**Comment by Sebjugate** [comment]
Just curious, is filter_var considered a poor way of validating email addresses? Or why do you want to revert?

**Comment by neo22s** [comment]
Theres an API break change:

This:
`public static function email($email, $strict = FALSE)`

Was changed to this:
`public static function email(String $email, bool $strict = FALSE): bool`

Therefore anyone that has extended that function will get an error and therefore the update does not work as a dropin.

The filter_var works great ;)

**Comment by svenbw** [comment]
I would keep the function body and revert the function definitions.

**Comment by neo22s** [comment]
This is still wrong:

![image](https://user-images.githubusercontent.com/241725/48702246-bc61bb00-ebf0-11e8-8b6a-be43f13d55ce.png)


Should be 
`public static function email($email, $strict = FALSE)`
