### ISSUE TITLE
ORM_Behavior_Guid: class UUID doesn't exist

### ISSUE THREAD

**Issue by WinterSilence** [koseven/koseven#288]
https://github.com/koseven/koseven/blob/4854377886f69324ed5d9720d4ae2b2cb1e18bb5/modules/orm/classes/ORM/Behavior/Guid.php#L46

**Comment by svenbw** [comment]
See #244: I'm integrating a separate UUID generator in ORM.

**Comment by WinterSilence** [comment]
@svenbw i cant find file/class `UUID`

**Comment by WinterSilence** [comment]
@svenbw It's our problem. Move `UUID::valid()` to `ORM_Behavior_Guid` or copy u code here - we rewrite & add him.

**Comment by piotrbaczek** [comment]
You can use this library: https://github.com/ramsey/uuid
7.5k stars on github, well maintained
