### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#29]
Integrate https://travis-ci.org/

**Comment by neo22s** [comment]
@kotsios5 so whats next now? we need to register in travis or how does it work? thanks a lot!!!

**Comment by neo22s** [comment]
https://travis-ci.org/koseven/koseven

**Comment by kotsios5** [comment]
1. https://github.com/settings/applications -> Organization access -> Grant access
2. https://travis-ci.org/profile/ -> Choose Koseven on the left sidebar under Organizations.
3. Enable koseven/koseven.

I created a test organization on Github to see how it works, if something doesn't work let me know!

**Comment by neo22s** [comment]
Problem here is that I can not choose the branch :S https://travis-ci.org/koseven/koseven goes aginst master but should go against devel branch

**Comment by neo22s** [comment]
aha seems after adding a PR does execute it https://travis-ci.org/koseven/koseven/branches
