### ISSUE TITLE
PHP 7+ support, remove unavailable classes/extensions

### ISSUE THREAD

**Issue by toitzi** [koseven/koseven#297]
As already mentioned in other issues (eg. #248 ), koseven only supports php7+

I think following classes can be removed:

`Cache_Memcache` (php extension replaced with memcache**d**)
`Cache_Apc`  (discontinued and removed since PHP 5.5, because OPCache was integrated to core)

Do you agree?

There is an **inofficial** memcache [port to php 7](https://github.com/websupport-sk/pecl-memcache), but should we really keep it even if it is not officially supported by php?

And there is an official pecl extension for backwards apc api calls [apcu_bc](https://pecl.php.net/package/apcu_bc), but since this was removed with php5.5 this only applies to Kohana projects before php5.5 and using apc with installed compatibility extension.

What do you guys think? Keep them or remove them?

(If anyone is curious why i am asking: I plan to write many unittests this week and want to know if i have to write smth for those or not. Also i am updating our "travis" configuration and want to know if we need to install those extensions there)

**Comment by neo22s** [comment]
Hello,

Indeed memcache and APC can get removed.

We have memcached and APCu that are 100% compatible with php 7.

So I agree. But we should also documented on the docs. Mentioning it on the migration. Although they will face the issue immediately.
