### ISSUE TITLE
Development flow

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#30]
Should we commit everything into Master, and then just do a Tag per release? Is what I had in mind now.

I want to keep things as simple as possible so its easy to collaborate.

**Comment by mercury64** [comment]
I would suggest create a 'develop' branch, everything commit into develop, then merge to master and tag. I never commit directly into master. I suggest a simplified version of this http://nvie.com/posts/a-successful-git-branching-model/

**Comment by neo22s** [comment]
ok! sounds good to me to. 

To keep it simple and please let me know if you all agree:

1. Commit all to devel
2. Merge to Master from Devel once tested in Devel (normally before release?)
3. Tag for release

Master should be latest stable? so same as the last tag?

If we agree I will add this simple flow to the docs.

**Comment by svenbw** [comment]
Yes. Agreed.

**Comment by jstrobel** [comment]
+1

**Comment by neo22s** [comment]
ok, new guides about how to contribute
https://github.com/koseven/koseven/blob/devel/CONTRIBUTING.md

New branch
https://github.com/koseven/koseven/tree/devel

Now devel is the default branch too
https://github.com/koseven/koseven

We will not accept PR to Master ;)
