### ISSUE TITLE
PHP 5 Compatibility

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#33]
Should we maintain the software compatible? PHP 5.6 will have support until 31 December 2018. Support, so only bug fixing.

Not sure what you all think, your input is important.

What I am sure:  I will not test on PHP 5 at all. xD Someone wants to take care of it?

**Comment by Gazoo** [comment]
I think with the recent news that Kohana is completely shutting down that maintaining PHP 5 compatibility is might be important (at least in the short term).

There are a lot of Kohana projects that are going to be turning to Koseven now.

**Comment by neo22s** [comment]
ok, agreed we will try to keep it compatible with PHP 5 an 7 as much as we can. Once https://github.com/koseven/koseven/issues/29 is closed will be easier. thanks!
