### ISSUE TITLE
Deprecation support

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#335]
**The problem**
As it turns out static functions are really hard to test with phpunit. All functions in `Minion_CLI` are static, so most of them are hard to test.
So a question pops up: what's in that class, can I move it?
As it turns out it's possible I could modify the `Minion_Task` class and add the `write ` method over there. So `Minion_CLI::write('some text')` should be replaced in the applications by `$this->cli->write('some text')` or `Minion_CLI::instance()->write('some text')`.
Because of the nature of Koseven (keep the backward compatibility) I cannot remove the original `Minion_CLI::write()` method, but if we want to take the project further it will become very hard to keep this up.

**Possible solution**
The idea is to introduce a deprecated function in the log class:
`Log::instance()->deprecated('This function will be removed in the future', '$this->cli->write');`

Resulting in a log entry which might look like this (date, time and line numbers are fake):
`2019-01-02 01:02:03 --- DEPRECATION: KO7_Minion_CLI::write: This function will be removed in the future. Replace by $this->cli->write ~ in /home/demo/modules/minion/classes/KO7/Minion/CLI.php:123
`
This allows developers to update the code by scanning the log files for this entry.

**Taking it further**
`Log::instance()->deprecated('This function will be removed in the future', '4.1.0');`

If the Koseven version is larger (or equal) to 4.1.0 we can throw an exception when this function is called; if the function is covered by unit testing these will fail. Using a configuration variable we can switch on or off the exceptions, this allows upgrades from old versions of Kohana/Koseven to newer versions of Koseven without exceptions (keeping the warnings).

**If one upgrades from 3.X.X to 4.1.0 the code will fail because the function is removed.**

**Comment by toitzi** [comment]
> As it turns out static functions are really hard to test with phpunit.

Can you explain this one a bit more, i do not quite agree.

> The idea is to introduce a deprecated function in the log class:

I honestly like that, but also keep in mind that you can simply add the `@deprecated` annotation and than it will be written into the php log and also the ide (most of them) will tell you that this function shall not be used 

> If the Koseven version is larger (or equal) to 4.1.0 we can throw an exception when this function is called;

Don't think this is neccessary. You deprecate a function for removal and declare it in the Changelog / Guides. After 1 or 2 versions (usally 1) you remove them. An Exception will be thrown anyway after that telling you that the function no longer exists.

**Comment by svenbw** [comment]
There are a lot of static functions which can be tested without a problem, however for the `Minion_CLI` there are some functions that write to the console. I was not able to validate the output in phpunt because these functions write to STDOUT (which should be replaced by `php://stdout`) because it's unbuffered output, The solution would be to create an output function which can be mocked in phpunit. However static functions cannot be mocked in phpunit.

I like to have all logging in one place; so the Koseven log was -in my opinion- a clean solution.

**Comment by toitzi** [comment]
> I like to have all logging in one place; so the Koseven log was -in my opinion- a clean solution.

Indeed it is but i think it is cleaner to catch them within our `error_handler` and log them there instead of doing it manually in every function.

>  STDOUT (which should be replaced by php://stdout)

No need for replacement `STDOUT` is just a constant for `php://stdout`

Not sure if rewriting and deprecating everything is the optimal solution. [Here](https://stackoverflow.com/questions/39783811/test-output-to-php-stdout-with-phpunit) is a quick example how you could read stdout in PHPUnit, we could integrate this in the Helper class of our PHPUnit.

Maybe we could also create a new static variable which holds the last written line, you can read this than in your unit test, without breaking compatibility / deprecating anything.

**Comment by svenbw** [comment]
> Not sure if rewriting and deprecating everything is the optimal solution. [Here](https://stackoverflow.com/questions/39783811/test-output-to-php-stdout-with-phpunit) is a quick example how you could read stdout in PHPUnit, we could integrate this in the Helper class of our PHPUnit.

It's not deprecating eveything; we might replace some functions in the future and should have a way of informing the users. So should we include this feature?

As for capturing `STDOUT`: I will look in to the example you provided, thanks for the suggestion.

> No need for replacement STDOUT is just a constant for php://stdout

The difference between `STDOUT` and `php://stdout` is explained [here](http://php.net/manual/en/wrappers.php.php), for me `php://` seems the preferred way to interface with streams (altough `STDOUT`/`STDIN`/`STDERR` are fine for me).

**Comment by toitzi** [comment]
> It's not deprecating eveything; we might replace some functions in the future and should have a way of informing the users. So should we include this feature?

Ok i think i misunderstood...so if you want to implement a function for throwing a deperecated error / and log it, then there is definitley a +1 from me 😸 

> The difference between STDOUT and php://stdout is explained here

Maybe you pasted the wrong link? all i get from this page is that:

>  It is recommended that you simply use the constants STDIN, STDOUT and STDERR instead of manually opening streams using these wrappers.

which we currently do

**Comment by svenbw** [comment]
> Maybe you pasted the wrong link?

I think the sentence before your quote is also important:

> *Note that PHP exhibited buggy behavior in this regard until PHP 5.2.1.* It is recommended that you simply use the constants STDIN, STDOUT and STDERR instead of manually opening streams using these wrappers.

So it was a good thing to use them before PHP version 5.2.1.

**Comment by toitzi** [comment]
@svenbw My bad, thought it would still be recommended. Thansk for the clearificaton. If you want to remove the constants you can do so if you want 😸 
Anyway +1 For me for a deprecated integration.

**Comment by toitzi** [comment]
@svenbw What do you think about this:

Inside _KO7_Core.php_:
````
/**
 * Call this within your function to mark it deprecated.
 *
 * @param string $since         Version since this function shall be marked deprecated.
 * @param string $replacement   [optional] replacement function to use instead
 */
public static function deprecated(string $since, string $replacement = '') : void
{
	// Get current debug backtrace
	$calling = debug_backtrace()[1];

	// Extract calling class and calling function
	$class = $calling['class'];
	$function = $calling['function'];

	// Build message
	$msg =
		'Function "' . $function . '" inside class "' . $class . '" is deprecated since version ' . $since .
		' and will be removed within the next major release.';

	// Check if replacement function is provided
	if ($replacement)
	{
		$msg .= ' Please consider replacing it with "' . $replacement . '".';
	}

	// Log the deprecation
	$log = Log::instance();
	$log->add(Log::WARNING, $msg);
	$log->write();
}
````

Now if you want to deprecate a function e.g inside _Controller_Welcoeme_

````
public function test() 
{
	KO7::deprecated('4.0', 'test2');
	...
}
````

the example above will log the following line inside your koseven log file:

````
YYYY-MM-DD HH:MM:SS --- WARNING: Function "test" inside class "Controller_Welcome" is deprecated since version 4.0 and will be removed within the next major release. Please consider replacing it with "test2". in /<your_folder>/application/classes/Controller/Welcome.php:<line>
````
