### ISSUE TITLE
KO7::list_files only with certain extension

### ISSUE THREAD

**Issue by toitzi** [koseven/koseven#336]
**Is your feature request related to a problem? Please describe.**
If you want to get a list of files / a folder tree the `KO7::list_files` function currently returns the complete file tree and does not allow to filter this by file extension.

**Describe the solution you'd like**
The possibility to pass an file extension. for example listing only `.php` or `.css` files, by simply
adding a 3rd parameter to the function.

**Describe alternatives you've considered**
Loop through them again and check it for myself.

**Comment by toitzi** [comment]
@neo22s @jstrobel @svenbw @errotan @piotrbaczek  what do you think?

**Comment by jstrobel** [comment]
3rd parameter would be nice if i can add an array of extensions e.g. for kmages joh,ng
