### ISSUE TITLE
Constructor/destructor for static classes

### ISSUE THREAD

**Issue by WinterSilence** [koseven/koseven#348]
Static classes implemented `KO7_Statical` interface and have public methods `construct` and `destruct` (or maybe `init`/`deinit`). Constructor called when autoloader include class implemented `KO7_Statical`, destructor register as shutdown handler (before core shotdown handler). Rewrite public properties as protected with setter/getter methods.
~~~
interface KO7_Statical {
    public static function construct();
    public static function destruct();
}
~~~

**Comment by toitzi** [comment]
I dont quite know what you mean....adding construct/destruct function to static classes? Why do you want to do that i mean the advantage of a static class is you do not have to construct it...or did i understand that wrong?

**Comment by WinterSilence** [comment]
@toitzi static classes have static properties, ex.: `Cookie::$salt`, `Cookie::$domain`, etc. we can set this properties from config at first calling class or delete temp files at shutdown.

**Comment by errotan** [comment]
Static methods resemble to procedural programming, hard to unit test and overuse of them make more issues. It would be better to decrease the use of it within koseven and not the opposite.

**Comment by WinterSilence** [comment]
@errotan `hard to unit test` - half core is static and i dont see problems with tests,  if u have idea how do it and save backward compatibility - tell about this.

**Comment by errotan** [comment]
I'm not saying that we should convert anything from static, but at least let's not introduce new ones. But thats just a suggestion.

**Comment by WinterSilence** [comment]
@errotan initial idea - sets default values for properties of static classes from common config:
~~~
return [
    'Class' => [
        'property' => 'value',
        'property2' => 'value2',
    ],
    'Class2' => [
        'property' => 'value',
    ],
];
~~~
we can use interface without methods (or not use interface) and add `KO7` method  called in 'KO7::auto_load()'.

**Comment by WinterSilence** [comment]
~~~
/**
 * Sets default values for static properties.
 * @param string $class
 * @return void
 */
protected static function set_static_properties($class)
{
    if ($class instanceof KO7_Statical)
    {
        if ($defaults = static::$config->load('statical')->get($class))
        {
            foreach ($defaults as $property => $value)
            {
                $class::${$property} = $value;
            }
        }
    }
}

public static function auto_load($class, $directory = 'classes')
{
    // Transform the class name according to PSR-0
    $class = ltrim($class, '\\');
    $file = $namespace = '';
    if ($last_namespace_position = strripos($class, '\\'))
    {
        $namespace = substr($class, 0, $last_namespace_position);
        $class     = substr($class, $last_namespace_position + 1);
        $file      = str_replace('\\', DIRECTORY_SEPARATOR, $namespace).DIRECTORY_SEPARATOR;
    }
    $file .= str_replace('_', DIRECTORY_SEPARATOR, $class);
    if ($path = static::find_file($directory, $file))
    {
        // Load the class file
        require $path;
        static::set_static_properties($class);
        // Class has been found
        return TRUE;
    }
    // Class is not in the filesystem
    return FALSE;
}
~~~

**Comment by toitzi** [comment]
Agree to @errotan we should not introduce more static classes / functions. Althrough i understand your point but i think it would be better to rewrite the static ones to not static. (ofc not all but some). 

Example:
If you want to set your current Timezone or your current Language etc, you don't do it via the configuration files right now, you have to "modify" the code and call it static. Maybe rewriting this and add a "core" configuration or smth. and load it from there instead. I thought of that a time ago. We could for example also declare the modules in a config file and won't have to edit the "bootstrap.php" file anymore if we separate the routes etc....but anyways for me this issue can be closed.

**Comment by WinterSilence** [comment]
@toitzi 

> Maybe rewriting this and add a "core" configuration or smth

you are right, but we talk about kohana **fork**, big changes make it unrecognizable. I like many things in kohana and i hate many things in kohana:

- distinctive code style
- statical, magical and unstrict code
- legasy pack

Maybe we will not confuse coders and create other project? We takes all goods from kohana without fork problems, adds namespaces, strict params, PSR styles and interfaces and rewrite code with minimum static, magic and "for kinds" solutions?

**Comment by toitzi** [comment]
@WinterSilence 

> distinctive code style
statical, magical and non strict code
legasy pack

agree with this and we try to update it from time to time. This has to happen in a "slow" process because Koseven aims/aimed to be the replacement for Kohana. So the goal was to make old kohana apps work with PHP7 without having to invest much time (and money) to update legacy code.

> Maybe we will not confuse coders and create other project? 

Personally i do not have time for such a thing - sorry - and as far as i know other koseven members also don't.
Althrough i am intereste...if you are willing to create a seperate fork which is more 'strict' and does not have to be compatible with kohana i would definitly look into it and be interested / maybe even use it and put a bit work in it.

Therefore i will close this issue (also has been inactive quite some time). If you disagree and have more feedback/wishes/input/thoughts to share feel free to re-open.
