### ISSUE TITLE
preg_match() unkown modifier '?'  in valid.php .

### ISSUE THREAD

**Issue by mas1375** [koseven/koseven#351]
/**
	 * Checks whether a string is a valid number (negative and decimal numbers allowed).
	 *
	 * Uses {@link http://www.php.net/manual/en/function.localeconv.php locale conversion}
	 * to allow decimal point to be locale specific.
	 *
	 * @param   string  $str    input string
	 * @return  boolean
	 */
	public static function numeric($str)
	{
		// Get the decimal point for the current locale
		list($decimal) = array_values(localeconv());

		// A lookahead is used to make sure the string contains at least one digit (before or 
                    after the decimal point)
		 return (bool) preg_match('/^-?+(?=.*[0-9])[0-9]*+'.preg_quote($decimal).'?+[0-9]*+$/D', (string) $str); }

 // my solution :  return (bool) true ;   :)

 ** but what is that error for??? **

**Comment by mas1375** [comment]
@neo22s @Azuka @stik @juherr

**Comment by WinterSilence** [comment]
@mas1375 php 7.3? add dump localeconv()

rework:
~~~
/**
 * Checks whether a value is a valid number (negative and decimal numbers allowed).
 *
 * @param   mixed  $value
 * @return  boolean
 */
public static function numeric($value)
{
    if (is_numeric($value))
    {
        if (((int) $value == $value) OR ((float) $value == $value))
        {
            return TRUE;
        }
        // Used to make sure the value contains at least one digit (before/after the decimal point)
        $locale = localeconv();
        return (bool) preg_match(
            '/^-?+(?=.*\d)\d*+['.preg_quote($locale['decimal_point']).']?+\d*+$/D',
            $value
        );
    }
    return FALSE;
}
~~~

**Comment by mas1375** [comment]
@WinterSilence PHP 7.2.
thanks.

**Comment by WinterSilence** [comment]
@mas1375 show dump `localeconv()`, changes in regexp only in php 7.3 - i think problem in incorrect pointer.

**Comment by toitzi** [comment]
@mas1375 @WinterSilence cannot reproduce this one. Is it a error / issue of the framework?

**Comment by mas1375** [comment]
it's localeconv() dump :
```json 
array (size=18)
  'decimal_point' => string '/' (length=1)
  'thousands_sep' => string ',' (length=1)
  'int_curr_symbol' => string 'IRR' (length=3)
  'currency_symbol' => string 'ريال' (length=8)
  'mon_decimal_point' => string '/' (length=1)
  'mon_thousands_sep' => string ',' (length=1)
  'positive_sign' => string '' (length=0)
  'negative_sign' => string '-' (length=1)
  'int_frac_digits' => int 2
  'frac_digits' => int 2
  'p_cs_precedes' => int 0
  'p_sep_by_space' => int 0
  'n_cs_precedes' => int 0
  'n_sep_by_space' => int 0
  'p_sign_posn' => int 3
  'n_sign_posn' => int 3
  'grouping' => 
    array (size=1)
      0 => int 3
  'mon_grouping' => 
    array (size=1)
      0 => int 3
```

**Comment by WinterSilence** [comment]
@toitzi problem with "not dot" decimal pointers, this class used many strange and old solution :(

**Comment by toitzi** [comment]
@WinterSilence Thanks for clarification!

**Comment by toitzi** [comment]
@WinterSilence Does your code above fix it? Can you make a PR out of it?

**Comment by mas1375** [comment]
> @mas1375 php 7.3? add dump localeconv()
> 
> rework:
> 
> ```
> /**
>  * Checks whether a value is a valid number (negative and decimal numbers allowed).
>  *
>  * @param   mixed  $value
>  * @return  boolean
>  */
> public static function numeric($value)
> {
>     if (is_numeric($value))
>     {
>         if ((intval($value) === $value) OR (floatval($value) === $value))
>         {
>             return TRUE;
>         }
>         // To make sure the value contains at least one digit (before/after the decimal point)
>         $locale = localeconv();
>         return (bool) preg_match(
>             '/^-?+(?=.*\d)\d*+['.preg_quote($locale['decimal_point']).']?+\d*+$/D',
>             $value
>         );
>     }
>     return FALSE;
> }
> ```

there is another solution for it, according to the manual : 

> **Note that / is not a special regular expression character.**
> [...]
> delimiter
> If the optional delimiter is specified, it will also be escaped. This is useful for escaping the delimiter that is required by the PCRE functions. The / is the most commonly used delimiter.

**so :**
```php
return (bool) preg_match('/^-?+(?=.*[0-9])[09]*+' . preg_quote($decimal, '/') . '?+[0-9]*+$/D', (string) $str);
```
