### ISSUE TITLE
PHP RFC: Deprecate PHP Short open tags

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#359]
**Describe the bug**
Deprecate and disable short_open_tag in PHP 7.4 and remove PHP's short open tags in PHP 8.0.

https://wiki.php.net/rfc/deprecate_php_short_tags

**To Reproduce**

I have not reproduced it but we need to check our code to see if we use it.

**Additional context**
added here so we do not forget will be in php 7.4

**Comment by WinterSilence** [comment]
@neo22s i think add it in "Conventions and сoding style"

**Comment by jstrobel** [comment]
@neo22s A first grep over the source with
`grep '<? ' * -r`
just gets me one result:
> modules/userguide/vendor/markdown/markdown.php:			| # PHP and ASP-style processor instructions (<? and <%)

**Comment by WinterSilence** [comment]
@jstrobel i fix it, but not public. Need find it in pantry :)

**Comment by WinterSilence** [comment]
https://github.com/kohana/userguide/tree/682cc9595b9716428d5a7e83834d61b3784aa7fa updated markdown and kodoc classes

**Comment by toitzi** [comment]
Added convention and removed existing usage (only in docs - we do not use it somewhere else). Will be online with devel.
