### ISSUE TITLE
Can we name and add this to Packagist?

### ISSUE THREAD

**Issue by Azuka** [koseven/koseven#36]
I'm currently using the Kohana 3.4 packages from composer on a site I hope to upgrade to PHP 7 to take advantage of the performance improvements.

Would it make sense to get this added to packagist, at least for easy updates? Although it's a full framework, it should be relatively trivial to continue to use an existing Kohana site with modules and the system directory pointing to the appropriate locations in `vendor`. `koseven/koseven` or `koseven/framework` would be a good name (pending the decision to split into separate modules and core).

I can put in a pull request for a change to the composer.json file if everyone thinks it's a good idea.

Thoughts?

**Comment by neo22s** [comment]
good for me!
