### ISSUE TITLE
[question] How to add rules to validation that are executed even when the value is empty

### ISSUE THREAD

**Issue by sabat24** [koseven/koseven#362]
Validation class has got property named `$_empty_rules`. There are listed rules that can be executed on empty fields values. When I wanted to add my custom methods of validation I wasn't able to force validator to use my rules. The only workaround without creating another files I found was to add names of my methods to that property. However it's not the best approach. 
Maybe there should be some setter method, which allows me to add custom methods names?

**Comment by WinterSilence** [comment]
@sabat24 
~~~
public function rule($field, $rule, array $params = NULL)
{
    if ($params === NULL)
    {
        // Default to array(':value')
        $params = [':value'];
    }
~~~

**Comment by sabat24** [comment]
It was not about adding my own, custom rule, but about executing it when value is empty.
Something more like:

```
public function add_empty_rule($rule_name)
{
    if ( ! is_array($rule_name))
    {
        $rule_name = [$rule_name];
    }    
    $this->_empty_rules = Arr::merge($this->_empty_rules, $rule_name);
}
```

But I don't want to modify system classes by myself because there are further problems with upgrades. This is why I asked if someone already had to deal with such problem.

**Comment by WinterSilence** [comment]
@ sabat24 it's need only if u extends `Valid` class, but "I don't want to modify system classes"

**Comment by toitzi** [comment]
@sabat24: @WinterSilence answered to your issue (Thanks!). Because of inactivity i think this can be closed. Feel free to re-open if you still got questions
