### ISSUE TITLE
Remove EXIF in Image-Module

### ISSUE THREAD

**Issue by Daijobou** [koseven/koseven#370]
**Describe the bug**
Default image driver is GD. There function like imagecreatefromjpeg() copy only image data and not EXIF data. So removing EXIF here is already default.

Change image driver to IMAGICK the EXIF data still exists after save(), because here is no call of stripImage() before saving. See https://www.php.net/manual/de/imagick.stripimage.php

**To Reproduce**
1. Set image driver to IMAGICK
2. Call Image::factory($file)->save($file,100);
3. New saved file still have EXIF data
-----
1. Set image driver to NULL (GD)
2. Call Image::factory($file)->save($file,100);
3. New saved file have **not** EXIF data

**Expected behavior**
It should always remove EXIF data.
https://github.com/koseven/koseven/blob/master/modules/image/classes/Kohana/Image/Imagick.php#L267
Add this line?
$this->im->stripImage();

**Comment by toitzi** [comment]
@Daijobou Thanks a lot for your report. I can verify this issue. The image module is currently under a "rework" (#369). I will fix this one there and it will be released soon with v4.0.

I will add an option for the user to configure if exif data get's removed or not. 
By default the EXIF data will be removed, if necessary to keep the user can define
(something like - not final yet): `$image->keepEXIF(TRUE)` .... as soon as i've more informations/updates on this i will notify you here.

Thanks a lot!

**Comment by toitzi** [comment]
Fixed in #369
