### ISSUE TITLE
[question] How to implement and then use Config_Writer?

### ISSUE THREAD

**Issue by sabat24** [koseven/koseven#376]
I tried to implement a writer for file config class.  I created following class:
```class Kohana_Config_File_Writer extends Kohana_Config_File_Reader implements Kohana_Config_Writer {```
and I added my own "write" method. Then I tried to use it, but I have no idea how.

I tried to do following:
```
$config = Kohana::$config->load('group');
Kohana::$config->_write_config('group', 'key', 'value');
```
*_write_config* method is searching in sources for *Kohana_Config_Writer* instance, however in such case there are only: *class Kohana_Config_File#11* and *class Config_File#10* so *write* method is never executed.

It's more direct approach to: ```$config->offsetSet('key', 'value');``` but both works identical.

**Comment by toitzi** [comment]
You referenced the wrong class, if you only need a Writer you do not have to extend the Reader Class. Also very Important: You need to attach the new Reader as source. Here is a example how it works:

Example Class:
````
class Kohana_Config_File_Writer implements Kohana_Config_Writer
{
    public function write($group, $key, $config)
    {
        // TODO: Implement write() method.
        var_dump('excecuted');
    }
}
````

Instead of your code you ned to inject the new reader / writer:
````
$conf = Kohana::$config->attach(new Kohana_Config_File_Writer(), TRUE)
````

Now you can write using the write above:
````
Kohana::$config->_write_config('group', 'key', 'value');
````

Following Result will be printed:
`application/classes/Kohana/Config/File/Writer.php:8:string 'excecuted' (length=9)`

**Comment by sabat24** [comment]
Thanks. Now I get it.
I need both writer and reader, but I didn't realize that by attaching *new Config_File* in bootstrap I refered basically only to reader. There were 2 extensions which leaded finally to the Kohana_Config_File_Reader
By attaching there my writer I can just use:
```
$conf = Kohana::$config->load('group');
$conf->set('key', 'val');
```

**Comment by toitzi** [comment]
Glad to hear you solved it! :)

p.s. if you have further questions / need tutorials it would be great if you open a topic on: https://koseven.discourse.group instead of here so other users can also find it there...but no worries.

Thanks a lot! :)
