### ISSUE TITLE
Profiler  -> Kohana\Profiler autoload (Error [ 0 ]: Class 'Profiler' not found)

### ISSUE THREAD

**Issue by Norpan83** [koseven/koseven#394]
when i ran koseven-3.3.9 with PHP Version 7.4.1 i noticed that when the class Profiler tries to autoload 
Kohana_Profiler class_exists('Profiler', FALSE) returns true,  but that class doesnt work because the parent isnt loaded,

so i had to chane in \system\classes\Kohana\Core.php (595)
-if (Kohana::$profiling === TRUE AND class_exists('Profiler', FALSE))
+if (Kohana::$profiling === TRUE  && $file != 'Kohana\Profiler' AND class_exists('Profiler', FALSE))

**Comment by themech** [comment]
This is a bug with PHP 7.4.1 autoloader, I reported it in https://bugs.php.net/bug.php?id=79022, should be fixed in the next PHP release. But I also experienced other issues with PHP 7.4, which may need fixing in koseven code.

**Comment by toitzi** [comment]
@themech Thank you yes indeed seems like it was the php bug. If you encounter other issues feel free to open a new issue for the ones you find. Thanks!
