### ISSUE TITLE
ErrorException [ Deprecated ]: array_key_exists(): Using array_key_exists() on objects is deprecated.

### ISSUE THREAD

**Issue by zweyka** [koseven/koseven#403]
PHP Version 7.4.3

ErrorException [ Deprecated ]: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead
SYSPATH/classes/Kohana/Arr.php [ 104 ]
```
104            if (array_key_exists($path, $array))
105            {
106                        // No need to do extra processing
107                        return $array[$path];
108            }
```

My offer:
```
104            if(is_array($array) && isset($array[$path])){
105                // No need to do extra processing
106                return $array[$path];
107            }
108            elseif (is_object($array) && property_exists($array, $path))
109            {
110                // No need to do extra processing
111                return $array[$path];
112            }
```

**Comment by WinterSilence** [comment]
@zweyka check [devel branch](https://github.com/koseven/koseven/tree/devel)

**Comment by Daijobou** [comment]
Source https://www.php.net/manual/de/migration74.deprecated.php

@zweyka 
Its here not needed, because on this point only an array is allowed ;)
See https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Arr.php#L91

**Comment by toitzi** [comment]
Fixed in devel

**Comment by Daijobou** [comment]
@toitzi 
This issue is not fixed in devel. Shouldn't you set it correctly everywhere at once? "array_key_exists" is not only in Arr.php. Currently only the example is fixed.

See https://github.com/koseven/koseven/blob/devel/system/classes/KO7/View.php#L170 and more...

**Comment by WinterSilence** [comment]
@Daijobou `$this->_data` is `array` not `object`

**Comment by Daijobou** [comment]
What are you trying to tell me?
```
$arr = array('test'=>NULL);
echo isset($arr['test']) ? 'found' : 'not found';
```
Output is "not found", but its exists.

**Comment by WinterSilence** [comment]
@Daijobou > See https://github.com/koseven/koseven/blob/devel/system/classes/KO7/View.php#L170 and more...

in new php `array_key_exists` work only with arrays, objects not supported

**Comment by Daijobou** [comment]
I was of the opinion that array_key_exists() was completely abolished, but its only for objects. https://www.php.net/manual/de/migration74.deprecated.php

Thanks for the advice.

**Comment by WinterSilence** [comment]
@Daijobou nope, php devs decided to make their work easier - if `array_key_exists` support objects, then any `array_...` functions must do it (:

**Comment by Daijobou** [comment]
Sounds logic ;)

**Comment by WinterSilence** [comment]
>Daijobou php devs inside (:
