### ISSUE TITLE
caching mode breaks koseven with multiple config readers

### ISSUE THREAD

**Issue by lerman** [koseven/koseven#409]
**Describe the bug**

When using multiple config readers with $caching enabed, the contents of the first config file get cached and prevent the rest from loading / getting merged in.

This is due to $_cache being set in KO7_Config_File_Reader ...which prevents further loading due to the if block below:
 if (KO7::$caching && isset(self::$_cache[$group])) {

Note: The old kohana code does not have this cache, and therefore does not have the issue.

As a result of this, my environment specific configs never load when $caching is enabled.

Running the latest develop branch of koseven.

**To Reproduce**

In boostrap.php set something like:

// set default config
KO7::$config->attach(new Config_File)

// set env specific config
KO7::$config->attach(new Config_File(ENV_CONF_DIR), TRUE);

**Expected behavior**

When $caching === TRUE, I expect koseven to load my configs properly, but instead only the default configs load.

**Comment by toitzi** [comment]
Fixed in PR form @WinterSilence thank you!
