### ISSUE TITLE
Class 'Dump' not found

### ISSUE THREAD

**Issue by DB-CL** [koseven/koseven#415]
**Describe the bug**
With latest devel version of Koseven, I have an error : 
`PHP Fatal error:  Uncaught Error: Class 'Dump' not found in /path/to/koseven/system/classes/KO7/View.php:68`

It looks like it has been introduced with commit https://github.com/koseven/koseven/commit/6a0d2753d182ea905d1e656add4084699334a24c

I've checked dependencies and I did not find anything called "Dump"

Am I missing something ?

**To Reproduce**
1. Git pull latest devel
2. Run anything
3. See error

**Comment by WinterSilence** [comment]
@DB-CL nope, my fail

**Comment by toitzi** [comment]
Thank you fixed with wintersilence pr
