### ISSUE TITLE
Test Failure 

### ISSUE THREAD

**Issue by rahul-works** [koseven/koseven#416]
Testing on Mac Operaing System
1) KO7_URLTest::test_is_trusted_host with data set #2 ('www.koseven.dev', array('.*\.koseven\.ga'), true)
Failed asserting that false is identical to true.

koseven/system/tests/ko7/URLTest.php:362
koseven/modules/unittest/classes/KO7/Unittest/TestSuite.php:61

**Comment by koseven-ga** [comment]
> Testing on Mac Operaing System
> 
> 1. KO7_URLTest::test_is_trusted_host with data set [Improve install.php #2](https://github.com/koseven/koseven/issues/2) ('www.koseven.dev', array('.*.koseven.ga'), true)
>    Failed asserting that false is identical to true.
> 
> koseven/system/tests/ko7/URLTest.php:362 koseven/modules/unittest/classes/KO7/Unittest/TestSuite.php:61

Please check @rahul-works
