### ISSUE TITLE
How to deal with Mcrypt from Encrypt module on php7.2 and above?

### ISSUE THREAD

**Issue by sabat24** [koseven/koseven#417]
In system/classes/Kohana/Session.php there is reference to Encrypt class

```php
if ($this->_encrypted)
{
    // Encrypt the data using the default key
    $data = Encrypt::instance($this->_encrypted)->encode($data);
}
```

In Encrypt module you still use mcrypt
https://github.com/koseven/koseven/blob/master/modules/encrypt/config/encrypt.php

which shouldn't be used since 7.2 and because of lacking that lib, I receive warnings and errors.

Should I configure that module somehow to not use mcrypt or how do deal with it?

**Comment by Daijobou** [comment]
Use openssl instead in config/encrypt.php
```
return array
(
	'default' => array(
		'type'   => 'openssl',
		'key'    => 'your-secret-key',
		'cipher' => 'AES-256-CBC',
	)
);
```

chiper = http://php.net/manual/de/function.openssl-get-cipher-methods.php

**Comment by sabat24** [comment]
Thanks it works.
However I think that MCRYPT constants should be removed from module's config as I want to define encryption inside application config because of cascading filesystem. Right now I have to comment these lines there and I shouldn't basically touch module files directly.

```php
/*'cipher' => MCRYPT_RIJNDAEL_128,
'mode' => MCRYPT_MODE_NOFB,*/
```

**Comment by Daijobou** [comment]
Look here https://github.com/koseven/koseven/blob/devel/modules/encrypt/config/encrypt.php for version 4.0 or changelog https://github.com/koseven/koseven/blob/devel/CHANGELOG.md

**Comment by toitzi** [comment]
Mcrypt is deprecated in 4.0 (devel) and constants are moved there, so no todo here i guess
