### ISSUE TITLE
New Kohanaframework.org site

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#42]
- [x] create repo https://github.com/koseven/kohanaframework.org
- [ ] Point domain to cloudflare
- [ ] set https
- [ ] point to CNAME at github pages
- [x] landing https://github.com/BlackrockDigital/startbootstrap-freelancer or any from https://startbootstrap.com/template-categories/all/
- [x] links to kohana modules, kohana alternatives, Old download
- [x] Explain that is not active anymore but there's alternatives
- [ ] add g.analytics

**Comment by neo22s** [comment]
preview available at https://koseven.github.io/kohanaframework.org/

**Comment by neo22s** [comment]
if anyone can redact a bit of text.... I will apreciate it, I am  not inspired at all...

Some history of kohana https://www.wikiwand.com/en/Kohana_(framework)

**Comment by jstrobel** [comment]
I added some text and some first links. Think it's a beginning.

**Comment by neo22s** [comment]
@jstrobel thanks! for me is more than enough. Only thing is that the 3.3.6 release and all the KO repo will be offline... so if we want to point to latest stable maybe we need to host the file ourselves :S

**Comment by neo22s** [comment]
I have cloned the repo and added the release. https://github.com/koseven/kohana/releases/tag/v3.3.6

**Comment by neo22s** [comment]
no any answer from @shadowhand... can not move forward. Removing this issue from 3.3.7 release

**Comment by mrliuxiang** [comment]
hi @neo22s is this framework just work in PHP7?         how about PHP5.6?

**Comment by neo22s** [comment]
hi @mrliuxiang should work too , but I do not recommend it.

**Comment by mrliuxiang** [comment]
@neo22s great ! thanks for your answer~~ ,   i want to use koseven in my project  with php5.6+
