### ISSUE TITLE
Composer package is not auto-updated

### ISSUE THREAD

**Issue by danielbreves** [koseven/koseven#425]
**Describe the bug**
The koseven package is not getting auto-updated on packagist: https://packagist.org/packages/koseven/koseven

**Expected behavior**
New koseven should be updated automatically when available.

**Screenshots**
![Screen Shot 2020-10-13 at 12 21 15 pm](https://user-images.githubusercontent.com/2517811/95804510-9991a000-0d4e-11eb-8968-1d054708feea.png)

**Additional context**
This prevents us from updating it via composer.

**Comment by toitzi** [comment]
Thank you im looking into it

**Comment by toitzi** [comment]
Should now be auto updating...thanks!
