### ISSUE TITLE
Incorrect description of _sanitize_id in Modules Cache is confusing

### ISSUE THREAD

**Issue by Chipcius** [koseven/koseven#426]
**Describe the bug**
When looking at the description of `_sanitize_id` in `modules/cache/Kohana/Cache.php` the result of the function results do not match the function description

**To Reproduce**
1. Take a look at the comment in the file

**Expected behavior**
A function description should reflect the function behaviour

**Screenshots**
![image](https://user-images.githubusercontent.com/1033039/96002214-66bbda80-0e28-11eb-84f4-f5a9159f8d20.png)

**Additional context**
This caused me to go in circles for 2 hours because I expected the comment to be correct

**Comment by toitzi** [comment]
You are right, thank you for the PR and thanks for noticing. I merged your PR!
