### ISSUE TITLE
PHP 8 compatibility for 3.3.x branch

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#433]
**Is your feature request related to a problem? Please describe.**
PHP 8 compatibility for 3.3.x branch

**Describe the solution you'd like**
Let's analyze the code in 3.3.10 and see incompatibilities with PHP8 to make it work.

**Describe alternatives you've considered**
Maybe we can create new branch 3.4.x for PHP8 ?
**Additional context**
https://www.php.net/index.php#id2020-11-19-1
https://github.com/php/php-src/blob/php-8.0.0RC5/UPGRADING

**Comment by neo22s** [comment]
array\_key\_exists() on objects. 

> Using array\_key\_exists() on objects is deprecated since PHP 7.4

https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Arr.php#L104

Replace with

```
if (is_object($array) AND property_exists($array, $path))
```

**Comment by Daijobou** [comment]
See https://github.com/koseven/koseven/issues/403 Its changed in devel with "isset" https://github.com/koseven/koseven/blob/devel/system/classes/KO7/Arr.php#L105

But, this issue "array_key_exists" is still in more files. Like https://github.com/koseven/koseven/blob/devel/system/classes/KO7/View.php#L176

**Comment by chrisgo** [comment]
Maybe we should just call it Koseven 8.0.0 as the first PHP 8 compatible branch

**Comment by pfuhrmann** [comment]
Or create Koeight since Koseven 8 is an oxymoron really.

**Comment by Daijobou** [comment]
I would call it Koseven v4.0.0. Why would you need to call it version 8 or "koeight"? I see "Koseven" as a brand name. ;)
Does anyone already have Koseven running with PHP8? Does it work?

PHP 7.4 has only support for security: https://www.php.net/supported-versions.php (Active Support was until 28 Nov **2021**)

**Comment by neo22s** [comment]
IMHO I will not complicate things, since the change is minimal. I am using php 8.0 in development for more than a year now. Only made 1 change. A simple release just increasing the number should suffice.

**Comment by timhj** [comment]
@Daijobou - yes running in 8.0 (all environments) for maybe six months. 
@chrisgo @pfuhrmann @neo22s - Yes, Koseven 3.4.X should be the version number (following [Semantic Versioning](https://semver.org/) pricinciples) as there are no breaking changes but it is a significant jump.

**Comment by Sephster** [comment]
Hi folks - is there a timescale on an official release to support PHP 8.0? Conscious the 7.4 is reaching EOL so need to make decisions about our existing Koseven infrastructure soonish. Thanks for all efforts on this project to date. Doing some amazing work!

**Comment by neo22s** [comment]
If someone can do a PR with this change and we tag it as 3.4 that would be all.

**Comment by Sephster** [comment]
I'm happy to put in a PR at some point to address this

**Comment by toitzi** [comment]
Duplicates #471 we are working on it, php 8.3 compatibility will hopefully be here soon!
