### ISSUE TITLE
ErrorException [ 8 ]: Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by tangerine** [koseven/koseven#435]
**Describe the bug**
Koseven 3.3.9
I have the above exception thrown at line 207 in Debug.php.  >>>>    	**if ($key[0] === "\x00")**

Presumably it arises from an error in my own code, but I have not managed to figure out where this may be despite using Chrome's debugger tools. 
According to PHP Docs this is a backward-incompatible change:
Array-style access of non-arrays ¶
Trying to use values of type null, bool, int, float or resource as an array (such as $null["key"]) will now generate a notice.

It seems likely that others have encountered this, so I am hoping there is a fix.
Thanks for any help.

UPDATE: My error was simple: sending a POST request while the back-end expected a GET. How might Koseven Debug() have handled this prior to PHP 7.4?

**Comment by svenbw** [comment]
This can be reproduced like this:
```
$obj = (object) [
  'one',
  'two'
];
echo Debug::dump($obj);
```

**Comment by timhj** [comment]
I came across this issue upgrading through to php 8.0 (may have been a 7.4 change).

Resolved it by checking if the $key was a string.
Debug.php:207
`if ($key[0] === "\x00")` 
to
`if (is_string($key) && $key && $key[0] === "\x00")`

Will submit a PR.

**Comment by Sebjugate** [comment]
Looks like this change may have actually been introduced in PHP 7.2: https://wiki.php.net/rfc/convert_numeric_keys_in_object_array_casts

PHP 7.1 casts `$o->{1} = 'value'` to `['1' => 'value']` whereas 7.2 casts it to `[1 = >'value']`

**Comment by timhj** [comment]
I'm not sure but Koseven was happily running on PHP 7.2 without this error for our app. I came across the issue in progressing from 7.2 through 7.3, 7.4 then 8. No app code changed were made during the process, only the php environment stepping up and triaging issues. It seems unlikely the issue existed in 7.2 for me for this reason.

Accessing object properties via curly braces was deprecated in 8 I think, there were some app changes required for us but I don't think there were any issues in Koseven framework.

**Comment by timhj** [comment]
I'm not sure, it did work for us on 7.2 without this issue. There was another crucial change to fix this issue actually. In the Kohana_Arr class there was a change required to the 'path' function. 
The path function (line 91) was changed to use the SPL (standard) is_array() function instead off Kohana_Arr::is_array() as the Kohana_Arr::is_array() function should really be called Arr::is_array_or_traversable() as it returns true for traversable objects aswell.
Those previously traversable objects can't be accessed via array syntax any longer as the functionality is deprecated, I think. 
The change worked for our app so I'd add it to the pull request but it might make it a breaking change and would require more testing.
