### ISSUE TITLE
php7.4 error when loading config twice (occurs when using cache)

### ISSUE THREAD

**Issue by Smartsasse** [koseven/koseven#444]
Php 7.4 no longer allows "array_key_exists" to work on an object even if that object is Traversable. In the file "koseven/system/classes/Kohana/Arr.php" the function "path" first checks the array with "is_array" which returns "true" for a traversable object and then "array_key_exists" is called on that object.

The error occurs when reading cache:
`$cache = Cache::instance('file');
$statistics = $cache->get('statistics');`

The error is also reproducible just loading a config-file and then an entry in the same config-file.

`$cache = \Kohana::$config->load('database');
$prefix = Kohana::$config->load('database.default');`

**Comment by svenbw** [comment]
I was not able to reproduce the issue under PHP 7.4.16 using the last version on the master will resolve your issue.

**Comment by Smartsasse** [comment]
I tried using the master branch but got message "koseven/koseven dev-master conflicts with koseven/koseven dev-master", not sure why.

But I can see that the code in koseven/system/classes/Kohana/Arr.php has been changed and that "array_key_exists" isn't even used anymore.

So this issue is indeed already resolved. Sorry for my inconvenience.
