### ISSUE TITLE
PHP 7.4 Could not execute Model::__construct()

### ISSUE THREAD

**Issue by satara** [koseven/koseven#452]
When using PHP 7.4 with Koseven 3.3.10 I get the following error:

![image](https://user-images.githubusercontent.com/3330908/128571078-b7e396ad-5e05-4d27-8446-feec93974f70.png)

The model is loaded, the error appears when I try to iterate over it. It happens for any model, not just for this one.

Can anyone help? Thanks a lot.

**Comment by jstrobel** [comment]
Hi @satara . Have you seen the example at https://www.php.net/manual/en/language.oop5.decon.php are your Classes build like that? Is is possible that we can have a look at your classes? Another example is: https://github.com/koseven/koseven/blob/master/modules/orm/classes/Model/Auth/User/Token.php

**Comment by satara** [comment]
Hi @jstrobel, thanks a lot for your answer, it helped me find out that the problem was not related to the  construct function or to Koseven. One class I am extending was overriding the __set function and was doing a $tablecolumns[$column] with $tablecolumns = NULL. That didn't seem to be a problem with PHP <= 7.3 but it is now with php 7.4.
