### ISSUE TITLE
Koseven for PHP 8.1

### ISSUE THREAD

**Issue by atze-dev** [koseven/koseven#462]
Hello,

Are there any plans to upgrade Koseven to latest PHP versions?

I already have a few customers who are being forced by hosting company to upgrade to PHP 8.x
I do not know what to do :/

Thank you.

**Comment by Daijobou** [comment]
I want test koseven with next coming version PHP 8.1.2 too.

@neo22s What new class + fix do you mean? I would also be interested. ;)

**Comment by neo22s** [comment]
I've been working in php 8 for many months already please see https://github.com/koseven/koseven/issues/433#issuecomment-730971515

**Comment by toitzi** [comment]
As @neo22s pointed out please see #433 closing this as duplicate

**Comment by phpclub** [comment]
https://github.com/koseven/koseven/issues/471
