### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by bwdutton** [koseven/koseven#464]
Lots of typing errors when using PHP 8.1. I created a PR https://github.com/koseven/koseven/pull/463 to fix the errors I ran into but what is the right type of PR to open? The contributing guide says to create against devel but that branch doesn't look like what is in master/packagist/composer.

**Comment by toitzi** [comment]
Thanks a lot, merging master is just fine, we will handle it like a hotfix. I will take a look soon, as soon as we have all the PRs together we merge them and create a new tag, so everybody can update without having to deal with a "upgrade" :)

**Comment by Daijobou** [comment]
In this fix is still strftime()? https://github.com/koseven/koseven/blob/master/system/classes/Kohana/Date.php#L284 which is deprecated https://www.php.net/manual/de/function.strftime.php

**Comment by toitzi** [comment]
Duplicates #471
