### ISSUE TITLE
Loading values from config files with dot notation gives NULL

### ISSUE THREAD

**Issue by ajuszczyk** [koseven/koseven#466]
I have upgraded an old kohana system to koseven and once switched the php to version 7.4.2 suddenly all values from config files like:
`Kohana::$config->load('language.abbr')` etc give back null.
When I load `Kohana::$config->load('language')` there is data returned.
Also `Kohana::$config->load('language')->abbr` and `Kohana::$config->load('language')->get('abbr')` both work fine.

When switched back to kohana and php 5.4 values are loaded fine.

I just can't figure out why the dot notation doesn't work in koseven, any help will be much appreciated.

**Comment by timhj** [comment]
Is your language config file returning an Array or StdClass? If an stdclass/object, return an array.

The config loader uses Arr::Path, which would have started failing on objects in PHP 7.4.x. As a quick fix to get things working with 7.4, the Arr::path behaviour was changed to work only with arrays (and not traversable objects). It now returns NULL if an object is passed so could be the cause of your issue. Sorry if that's your issue, it was my PR and a really quick fix to make the framework load with PHP 7.4.

**Comment by ajuszczyk** [comment]
In addition this is what I'm getting back with Kohana::$config->load('language')

```
object(Config_Group)[6]
  protected '_parent_instance' => 
    object(Config)[3]
      protected '_sources' => 
        array (size=1)
          0 => 
            object(Config_File)[5]
              ...
      protected '_groups' => 
        array (size=1)
          'language' => 
            object(Config_Group)[6]
              ...
  protected '_group_name' => string 'language' (length=8)
  private 'storage' (ArrayObject) => 
    array (size=5)
      'language' => string 'english' (length=7)
      'language_abbr' => string 'en-gb' (length=5)
      'lang_uri_abbr' => 
        array (size=3)
          'pl-pl' => string 'polish' (length=6)
          'en-gb' => string 'english' (length=7)
          'en-us' => string 'us_english' (length=10)
      'lang_ignore' => string 'xx' (length=2)
      'lang_desc' => 
        array (size=3)
          'en-us' => string 'US English version' (length=18)
          'en-gb' => string 'English version' (length=15)
          'pl-pl' => string 'Polish version' (length=14)
```

**Comment by timhj** [comment]
@ajuszczyk  - I mentioned two fixes, did you apply this one: https://github.com/koseven/koseven/pull/467/files ? 

It looks like it should solve your issue as you're getting individual values from the config array, which would not have worked.

**Comment by ajuszczyk** [comment]
@timhj thanks, I have only applied the fix you mentioned (https://github.com/koseven/koseven/pull/467/files) - 1 line of code change. I'm not sure what the other fix is, I'm afraid.
I'm getting the same results with or without the fix.
