### ISSUE TITLE
Kohana to Koseven Porting Help

### ISSUE THREAD

**Issue by jeffreypicard** [koseven/koseven#469]
Hey guys,

I'm trying to port an old web game from Kohana to Koseven and I'm running into errors that I think are related to the ORM. I tried to hop into your telegram, but it seems like I was maybe auto banned for trying to post a screen shot of my error. The group says it's no longer accessible at any rate.

The error is this
```
View_Exception [ 0 ]: Rendering error in template APPPATH/views/template/gamelayout.php: KO7_Exception [ 0 ]: The loaded property does not exist in the Model_Characterstat class ~ MODPATH/orm/classes/KO7/ORM.php [ 725 ]
SYSPATH/classes/KO7/View.php [ 68 ]

63 		catch (Throwable $e)
64 		{
65 			// Delete the output buffer
66 			ob_end_clean();
67  			// Re-throw the exception
68 			throw new View_Exception(
69 				'Rendering error in template :view: :error',
70 				[':view' => Debug::path($ko7_view_filename), ':error' => $e],
71 				0,
72 				$e
73 			);
```

here is the file https://github.com/jeffreypicard/medieval-europe/blob/koseven/public_html/application/classes/Model/Characterstat.php

As I said I'm guessing it has to do with the changes in the structure of the ORM classes, but the error messages are entirely helpful and there's a ton of code so things are hard to debug at time.

Thanks!

**Comment by Sebjugate** [comment]
loaded() is a function. I vaguely recall that it was a property in some older version of Kohana. Try changing $model->loaded to $model->loaded()

**Comment by Sebjugate** [comment]
Here is your problem (or at least the one that caused this error).

https://github.com/jeffreypicard/medieval-europe/blob/54bdca77165b153bfba6e48e057cc977a03fae2a/public_html/application/views/template/gamelayout.php#L537

**Comment by jeffreypicard** [comment]
Thanks for responding! That line was the source of that issue, however I'm still getting that same error even when I try to call it as a function. Removing that check altogether gets me past that line, but of course that's not a permanent solution. Is there something else that I'm possibly doing wrong with how the Model object is defined or created that the loaded function isn't there?

**Comment by Sebjugate** [comment]
The exact same error? Hm. I glanced briefly at the code, but nothing stands out to me.

**Comment by jeffreypicard** [comment]
Nevermind, the issue went away when we replaced all the instances of `loaded` with `loaded()`. Thanks again!
