### ISSUE TITLE
proxy/ssrf issue

### ISSUE THREAD

**Issue by PhilippHandle** [koseven/koseven#493]
**Describe the bug**
the request class states that a url like `http://localhost/http://example.com/judge.php` is know to be troublesome.
How can we harden the framework to handle such links?
the only solution i found is, to return the url with a "/" as prefix in the detect_uri method

**To Reproduce**
we are rewriting the urls with nginx.
`rewrite ^ /index.php/$uri last;`

**Expected behavior**
don't act as a proxy

**Screenshots**

**Additional context**

**Comment by augmenter** [comment]
@PhilippHandle you need to update your index.php to disable external urls from being used during the initialization phase.
`echo Request::factory(TRUE, [], FALSE)
		->execute()
		->send_headers(TRUE)
		->body();`

See the third parameter in factory, it sets $allow_external to FALSE.
