### ISSUE TITLE
New homepage/landing

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#5]
Using jekyll?

**Comment by svenbw** [comment]
Jekyll is good and makes it simple to create additional content, but if there is dynamic content (like links and version info about modules) this might not be sufficient.

**Comment by jstrobel** [comment]
1. Homepage on koseven.github.io or is there a domain?
2. I think jekyll would be good for that
3. @svenbw What do you mean with "not be sufficient"?

**Comment by svenbw** [comment]
I think koseven.github.io is a good place to put this information.
Ignore my not sufficient comment; Additional version and release information can be added when generating the pages and found on Github.

**Comment by neo22s** [comment]
We can get a free domain like koseven.ga or koseven.ml from freenom... for me is enough and I like it more than koseven.github.io

Just a landing with a bootstrap theme similar to what I have in https://euvat.ga/ with a readme and not much more...

**Comment by jstrobel** [comment]
There is one benefit i see with a github.io page. Everyone who can commit to the GIT can edit the page. And it will be directly binded to the repo.

And i am munch more a fan von common domainnames like com, net or some like tv,io,me etc. but this is just my opinion.

**Comment by jstrobel** [comment]
Eventually would this more a benefit of "edit for all with GIT-Access" when the docs are on this also. What do you think?

**Comment by neo22s** [comment]
yeah setting up with the https://pages.github.com/ project site so its auto generated.... dont want to make things complicated.

already got koseven.ga not beautiful but free. If anyone want to buy the koseven.com feel free to do so. But will be part of the open source community ;)

**Comment by jstrobel** [comment]
Sound good for me -> keep it simple first and the expand it step by step.

**Comment by neo22s** [comment]
https://koseven.ga/ ;)

I need to see how to add the download buttons as in the example... can someone check the docs?

**Comment by jstrobel** [comment]
;) koseven.ga ... lets stick to it so far :)

**Comment by jstrobel** [comment]
I've looked in the doc, themes like you have to create _includes/page-header.html to overwrite
it, like https://github.com/pietromenna/jekyll-cayman-theme/blob/master/_includes/page-header.html

Cannot test it right now, haven't set up it locally

**Comment by neo22s** [comment]
mmm could not make it work yet I will look tomorrow.

**Comment by jstrobel** [comment]
Needed some time to figure it out. Look at the pull request, the _includes folder can be deleted.
Hopefully it works the same as in my local environment.

**Comment by neo22s** [comment]
Doesnt work :(

https://github.com/koseven/koseven/blob/gh-pages/_config.yml#L2

points to https://github.com/koseven/koseven/zipball/gh-pages

**Comment by jstrobel** [comment]
So local and online doesn't work the same way :(

**Comment by jstrobel** [comment]
My other solution would be clean up the auto-generated stuff and commit just the generated site. But i think (like you too, i think) don't put to much efford in a landing page.

**Comment by neo22s** [comment]
yeah....lets keep things easy for now xD
