### ISSUE TITLE
Question: Is there a PHP checker like PHPStan that works with Kohana?

### ISSUE THREAD

**Issue by Daijobou** [koseven/koseven#505]
I tested PHPStan but this give too much false positives. I search for a tool to check general errors/mistakes in my project and for PHP 8.2 compatibility.

**Comment by yassineatik** [comment]
Have you Trid PSALM ?
I've just found it , please check its repo here : 
https://github.com/psalm/psalm-plugin-laravel

**Comment by Daijobou** [comment]
"just found it" Have you tested it with kohana? There are many such checkers, my question is which one works with Kohana, so that I don't have to test all of them for nothing. ;)

**Comment by yassineatik** [comment]
Yep , that's the point . I have not tested it yet , but yes , It works with kohana
