### ISSUE TITLE
Cache _sanitize_id improve to avoid duplicated entries

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#53]
Scenario:

You have 2 installations of KO7 in the same server with APCu active or memcached or redis... Both store a cache entry named "test". This will overwrite the one the other... We should make the _sanitize_id unique per installation? maybe adding an option cache prefix? in the config?

Possible solution, NOT TESTED

https://github.com/koseven/koseven/blob/devel/modules/cache/config/cache.php
```PHP
	'apcu'      => array(
		'driver'             => 'apcu',
		'default_expire'     => 3600,
                'prefix'     => 'cache1_',//or NULL
	),
```

https://github.com/koseven/koseven/blob/devel/modules/cache/classes/Kohana/Cache.php#L298

```php
protected function _sanitize_id($id)
	{
                //cache prefix
                if (isset($this->_config['prefix']) AND $this->_config['prefix']!=NULL)
                     $id = $this->_config['prefix'].$id;

		// Change slashes and spaces to underscores
		return str_replace(array('/', '\\', ' '), '_', $id);
	}
```

**Comment by roman-huliak** [comment]
This is easier than my edit.
In my fork i edit boostrap and add APP_NAME constant where i detect last folder name or set custom name. In cache I preppend APP_NAME to $id;
`return str_replace(array('/', '\\', ' '), '_', APP_NAME . '_' . $id);`

APP_NAME has many ways how to use. Logs, Cache, Distributed requests etc.

**Comment by neo22s** [comment]
@roman-huliak sounds good, but we need to be careful if constant does not work etc...

I do not mind the solution we need to implement one...as it is is wrong for sure ;)

**Comment by neo22s** [comment]
Theres also another issue with this... if the cache name is too long theres issues storing it. Imagine storing a SQL.... 

I used to do this:

```
protected function _sanitize_id2($id)
    {
        return sha1($id);
    }
```

**Comment by krassswr** [comment]
https://github.com/koseven/koseven/commit/6fef0b2fc28c92e91a178d98810066371c1f4802
