### ISSUE TITLE
Deprecated ini values

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#54]
Both `safe_mode` and `register_globals` are deprecated as of PHP 5.3.0. And are removed from PHP 5.4.0.
Should we check for the PHP version?

`if ((PHP_VERSION_ID < 50300) AND ini_get('register_globals'))`

and

`Kohana::$safe_mode = (PHP_VERSION_ID > 50300) OR ((bool) ini_get('safe_mode'));`

**Comment by neo22s** [comment]
agree!
