### ISSUE TITLE
Pagination - Required route parameter not passed: action

### ISSUE THREAD

**Issue by html-koder-com** [koseven/koseven#59]
Hi there,

I use the Pagination module, which is now included in this repo.

Right now I'm getting this error:

`EMERGENCY: Kohana_Exception [ 0 ]: Required route parameter not passed: action ~ SYSPATH/classes/Kohana/Route.php [ 580 ]`

I tried to debug that and the details are:

In the pagination/classes/Kohana/Pagination.php there is **url()** method... and inside there is this part of code:

```
case 'query_string':

	return URL::site($this->_route->uri($this->_route_params).
		$this->query(array($this->config['current_page']['key'] => $page)));
```

The **$this->_route->uri** expects the array as a parametr... and one of the keys of this array should be "action" key.

**But it isn't.**

The "action" key is unset in the Request class on purpos (because there is public $request->action() method), so I beleive there is some bug in the Pagination module.

If I hotfix the Pagination contructor like this:

```
// Assign default route params
$this->_route_params = $request->param();
$this->_route_params['action'] = $request->action();  // <-- this is my hotfix
```

it works just fine without any error.

Could you please verify my statement?

**Comment by neo22s** [comment]
its strange I have been using the pagination module for years now :s

Had some minor issues having capital letters (which I hate in URLs) and have modified a bit the view of pagination.php

anyone else having this issue?

**Comment by Azuka** [comment]
Here's what I overrode in mine right [after this line](https://github.com/koseven/koseven/blob/devel/modules/pagination/classes/Kohana/Pagination.php#L110):

```php
$this->_route_params['action'] = $request->action();
$this->_route_params['controller'] = $request->controller();
```

That should fix it if you're using a dynamic controller or action (or both).

**Comment by neo22s** [comment]
ok can someone do a PR? and we test it? thanks!

**Comment by neo22s** [comment]
@Azuka can you do a PR please? thanks
