### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#6]
Use something like https://readthedocs.org/ or jekyll?

We should change the module guide and API to generate static content that we can upload?

Or leave it dynamic, any ideas welcome.

**Comment by jstrobel** [comment]
When jekyll is used in https://github.com/koseven/koseven/issues/5 it could be a benefit to use it for documentation too. So don't combine to much dependencies.

**Comment by neo22s** [comment]
yeah I think the homepage will be just a static html and then the docs can go in docs.koseven.ga

lets hope tomorrow I find some time at least to host the kohana docs as they are currently so they do not get lost at least....

**Comment by jstrobel** [comment]
Other systems to generate a doc:
- http://www.phpdoc.org/
- http://www.apigen.org/
- https://codedoc.pub/

Any preferences or recommendations?
Or leave like @neo22s said dynamic?

**Comment by neo22s** [comment]
Best scenario will be using hosted at github similar to what we have at docs.yclas.com ---> https://github.com/yclas/documentation

Maybe auto generated docs from dynamic (we can build in local) and then upload it to the repo?

I am open to any suggestion.

**Comment by jstrobel** [comment]
Documentation looks really good for me.
Can you describe a little in detail how this works? You have a build-script which you run over you local files and then commit it to the repo? Sound perfect.

**Comment by neo22s** [comment]
no idea I need to check it xD hahaha

The easiest and that has less work is:

- docs.koseven.ga 
- Hosted on a server, PHP7
- Using the module documentation of kohana

This is how currently works http://kohanaframework.org/3.3/guide/

Maybe I have time later. ;)

We can always make it more complex :P

**Comment by jstrobel** [comment]
"no idea I need to check it xD hahaha" .. oh ;) thought you have a script ready for work ;)

Yes, no additional work right now seams perfect.

**Comment by svenbw** [comment]
If it works don't touch it. So lets use the documentation module.
I will document changes of my own PR (like behaviors) because the information in the source code might not be enough.

**Comment by neo22s** [comment]
ok basics working

https://docs.koseven.ga/

took a while :(
