### ISSUE TITLE
23 errors fail on fresh new koseven:devel

### ISSUE THREAD

**Issue by piotrgolasz** [koseven/koseven#64]
I tried to write a unittest related to https://github.com/koseven/koseven/pull/63, but I can't get all unittests passed even on fresh out of the box koseven.
`phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php 
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

.............................................................   61 / 1277 (  4%)
..........................W...WWWWWWW.WWWWWWWWW..............  122 / 1277 (  9%)
.............................................................  183 / 1277 ( 14%)
.............................................................  244 / 1277 ( 19%)
.............................................................  305 / 1277 ( 23%)
...............SS..................E..EEEE.EEEE.EEEEEEEEEEE..  366 / 1277 ( 28%)
....E........................................................  427 / 1277 ( 33%)
.............................................................  488 / 1277 ( 38%)
.............................................................  549 / 1277 ( 42%)
.............................................................  610 / 1277 ( 47%)
...................W..WWWW............W............WW........  671 / 1277 ( 52%)
........................EE...................................  732 / 1277 ( 57%)
.............................................................  793 / 1277 ( 62%)
.............................................................  854 / 1277 ( 66%)
.............................................................  915 / 1277 ( 71%)
.............................................................  976 / 1277 ( 76%)
............................................................. 1037 / 1277 ( 81%)
............................................................. 1098 / 1277 ( 85%)
............................................................. 1159 / 1277 ( 90%)
............................................................. 1220 / 1277 ( 95%)
....................................................WWWWW     1277 / 1277 (100%)

Time: 390 ms, Memory: 10.00Mb

There were 23 errors:

1) Kohana_FeedTest::test_create with data set #0 (array(123, array('http://kohanaframework.org/image.png', 'http://kohanaframework.org/', 'title')), array(array('bar', 123, 'foo')), array(array('localhost', 'xim', '/var/lib/lightdm-data/nzpetter', '/org/freedesktop/DisplayManag...ssion0', 'xterm-256color', '/bin/bash', 'gnome-', '4402', 'gnome-keyring', '1', '54525958', 'unix:abstract=/com/ubuntu/ups...0/2014', 'gail:atk-bridge:unity-gtk-module', 'nzpetter', 'rs=0:di=01;34:ln=01;36:mh=00:...00;36:', '1', '/org/freedesktop/DisplayManag...ssion0', '/org/freedesktop/DisplayManager/Seat0', '/run/user/1000/keyring/ssh', '/usr/share/gconf/ubuntu.default.path', '/etc/xdg/xdg-ubuntu:/usr/shar...tc/xdg', '/home/nzpetter/bin:/home/nzpe...ap/bin', 'ubuntu', 'ibus', 'qgnomeplatform', 'x11', '/var/www/html', '@im=ibus', 'pl_PL.UTF-8', 'pl', '/usr/share/gconf/ubuntu.mandatory.path', '1', 'ubuntu', 'ubuntu', 'overlay-scrollbar', '/home/nzpetter', '2', 'pl', 'this-is-deprecated', 'ubuntu', 'nzpetter', '/usr/bin/', '/usr/share/ubuntu:/usr/local/...esktop', 'xim', 'unix:path=/run/user/1000/bus', '| /usr/bin/lesspipe %s', '1910', '8:26029', '/run/user/1000', ':0', 'Unity', 'ibus', '/usr/bin/lesspipe %s %s', '/home/nzpetter/.Xauthority', 'truecolor', '/usr/bin/phpunit', '/var/www', '/usr/bin/phpunit', '/usr/bin/phpunit', '/usr/bin/phpunit', '/usr/bin/phpunit', '', 1489176007.411359, 1489176007, array('/usr/bin/phpunit', '--bootstrap=modules/unittest/...ap.php', 'modules/unittest/tests.php'), 3)), array('channel', array('item', array('foo', 'bar'))), array(array('channel', array('image', array('link', 'http://kohanaframework.org/image.png'))), array('channel', array('image', array('url', 'http://kohanaframework.org/'))), array('channel', array('image', array('title', 'title')))))
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FeedTest.php:133
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

2) Kohana_FormTest::test_open with data set #0 (array('', null), array(''))
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:83
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

3) Kohana_FormTest::test_open with data set #1 (array(null, null), array(''))
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:83
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

4) Kohana_FormTest::test_open with data set #2 (array('foo', null), array('/foo'))
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:83
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

5) Kohana_FormTest::test_open with data set #3 (array('foo', array('get')), array('/foo', 'get'))
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:83
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

6) Kohana_FormTest::test_input with data set #0 ('input', 'foo', 'bar', null, 'input')
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:147
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

7) Kohana_FormTest::test_input with data set #1 ('input', 'foo', null, null, 'input')
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:147
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

8) Kohana_FormTest::test_input with data set #2 ('hidden', 'foo', 'bar', null, 'hidden')
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:147
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

9) Kohana_FormTest::test_input with data set #3 ('password', 'foo', 'bar', null, 'password')
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:147
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

10) Kohana_FormTest::test_check with data set #0 ('checkbox', 'foo', null, false, null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:223
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

11) Kohana_FormTest::test_check with data set #1 ('checkbox', 'foo', null, true, null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:223
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

12) Kohana_FormTest::test_check with data set #2 ('checkbox', 'foo', 'bar', true, null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:223
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

13) Kohana_FormTest::test_check with data set #3 ('radio', 'foo', null, false, null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:223
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

14) Kohana_FormTest::test_check with data set #4 ('radio', 'foo', null, true, null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:223
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

15) Kohana_FormTest::test_check with data set #5 ('radio', 'foo', 'bar', true, null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:223
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

16) Kohana_FormTest::test_text with data set #0 ('textarea', 'foo', 'bar', null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:276
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

17) Kohana_FormTest::test_text with data set #1 ('textarea', 'foo', 'bar', array(20, 20))
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:276
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

18) Kohana_FormTest::test_text with data set #2 ('button', 'foo', 'bar', null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:276
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

19) Kohana_FormTest::test_text with data set #3 ('label', 'foo', 'bar', null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:276
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

20) Kohana_FormTest::test_text with data set #4 ('label', 'foo', null, null)
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:276
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

21) Kohana_FormTest::test_submit with data set #0 ('foo', 'Foobar!', '<input type="submit" name="fo...r!" />')
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:119
/var/www/html/system/tests/kohana/FormTest.php:341
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

22) Kohana_TextTest::test_auto_para_does_not_enclose_html_tags_in_paragraphs with data set #0 (array('div'), '<div>Pick a plum of peppers</div>')
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:147
/var/www/html/system/tests/kohana/TextTest.php:73
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

23) Kohana_TextTest::test_auto_para_does_not_enclose_html_tags_in_paragraphs with data set #1 (array('div'), '<div id="awesome">Tangas</div>')
Error: Call to undefined method PHPUnit_Util_XML::findNodes()

/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:167
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestCase.php:147
/var/www/html/system/tests/kohana/TextTest.php:73
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

--
`

What am I doing wrong?

**Comment by neo22s** [comment]
I think is really related to this https://github.com/koseven/koseven/issues/29

I have not launched the unittests in ages honestly :(

**Comment by piotrgolasz** [comment]
Just for the record
`php -v
PHP 7.1.2-4+deb.sury.org~yakkety+1 (cli) (built: Mar  2 2017 10:40:28) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2-4+deb.sury.org~yakkety+1, Copyright (c) 1999-2017, by Zend Technologies`

`php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
mcrypt
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache`

**Comment by jstrobel** [comment]
I have a quick look into it, there a some function which are deprecated in newer versions of PHPUnit we are using.

If you look at: modules/unittest/classes/Kohana/Unittest/TestCase.php
There a 3 functions with a comment:
	 * TODO:
	 * this should be removed when phpunit-dom-assertions gets released
	 * https://github.com/phpunit/phpunit-dom-assertions
But there a 2 functions in https://github.com/lstrojny/phpunit-dom-assertions which haven't ported not so far: assertTag and assertNotTag and they are used e.g. in TextTest.php

**Comment by jstrobel** [comment]
I found someone who wrote a "patch" and tried it.
[TestCase.php.txt](https://github.com/koseven/koseven/files/835158/TestCase.php.txt)
Haven't commit it because i think it is not the "clean" way to support a newer PHPUnit-Version.
There should be more investigation done, and rewrite some Test-Files.

**Comment by piotrgolasz** [comment]
I already started working on eliminating as many errors as I could - mostly those are just changed function name, changed method name, use namespace and so on....

**Comment by piotrgolasz** [comment]
What phpunit version should we aim at?

**Comment by jstrobel** [comment]
Jens Strobel, [10.03.2017, 22:29]: 
PHPUnit 5.7 is the old stable release series.
It became stable on December 2, 2016.
Support for PHPUnit 5 ends on February 2, 2018.

PHPUnit 6.0 is the current stable release series.
It became stable on February 3, 2017.
Support for PHPUnit 6 ends February 8, 2019...

Should we go with 6?

**Comment by piotrgolasz** [comment]
Ok, gentlemen. I basically got it to 0 errors and 3 failures.
https://github.com/piotrgolasz/koseven/commit/2bbf8d77b361ef3187500c62118ecd2a50360e18

`phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php
PHPUnit 6.0.8 by Sebastian Bergmann and contributors.

.............................................................   61 / 1277 (  4%)
.................................F...........................  122 / 1277 (  9%)
.............................................................  183 / 1277 ( 14%)
.............................................................  244 / 1277 ( 19%)
.............................................................  305 / 1277 ( 23%)
...............SS............................................  366 / 1277 ( 28%)
.............................................................  427 / 1277 ( 33%)
.............................................................  488 / 1277 ( 38%)
.............................................................  549 / 1277 ( 42%)
.............................................................  610 / 1277 ( 47%)
.............................................................  671 / 1277 ( 52%)
.............................................................  732 / 1277 ( 57%)
.............................................................  793 / 1277 ( 62%)
.............................................................  854 / 1277 ( 66%)
.............................................................  915 / 1277 ( 71%)
................................R............................  976 / 1277 ( 76%)
............................................................. 1037 / 1277 ( 81%)
............................................................. 1098 / 1277 ( 85%)
............................................................. 1159 / 1277 ( 90%)
............................................................. 1220 / 1277 ( 95%)
....................................................FF...     1277 / 1277 (100%)

Time: 920 ms, Memory: 12.00MB

There were 3 failures:

1) Kohana_ConfigTest::test_detach_removes_reader_and_returns_this
Failed asserting that an array does not contain Mock_Kohana_Config_Reader_0d7b24c3 Object &000000001c32a22b000000000142aeab (
    '__phpunit_invocationMocker' => null
    '__phpunit_originalObject' => null
    '__phpunit_configurable' => Array &0 (
        0 => 'load'
    )
).

/var/www/html/system/tests/kohana/ConfigTest.php:123
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:52

2) Kohana_Request_Client_ExternalTest::test_execute with data set #0 ('application/json', '{"foo": "bar", "snafu": "stfu"}', array(), array('application/json', '{"foo": "bar", "snafu": "stfu"}'))
Failed asserting that null is an instance of class "Response".

/var/www/html/system/tests/kohana/request/client/ExternalTest.php:185
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:52

3) Kohana_Request_Client_ExternalTest::test_execute with data set #1 ('application/json', '{"foo": "bar", "snafu": "stfu"}', array('bar', 'stfu'), array('application/x-www-form-urlenc...=utf-8', 'foo=bar&snafu=stfu'))
Failed asserting that null is an instance of class "Response".

/var/www/html/system/tests/kohana/request/client/ExternalTest.php:185
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:52

FAILURES!
Tests: 1277, Assertions: 2814, Failures: 3, Skipped: 2, Risky: 1.
`

**Comment by piotrgolasz** [comment]
Down to one single failure, but this one is a biggie. Does anyone have any idea why is this assertion failing?

`phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php
PHPUnit 6.0.8 by Sebastian Bergmann and contributors.

.............................................................   61 / 1275 (  4%)
.................................F...........................  122 / 1275 (  9%)
.............................................................  183 / 1275 ( 14%)
.............................................................  244 / 1275 ( 19%)
.............................................................  305 / 1275 ( 23%)
...............SS............................................  366 / 1275 ( 28%)
.............................................................  427 / 1275 ( 33%)
.............................................................  488 / 1275 ( 38%)
.............................................................  549 / 1275 ( 43%)
.............................................................  610 / 1275 ( 47%)
.............................................................  671 / 1275 ( 52%)
.............................................................  732 / 1275 ( 57%)
.............................................................  793 / 1275 ( 62%)
.............................................................  854 / 1275 ( 66%)
.............................................................  915 / 1275 ( 71%)
................................R............................  976 / 1275 ( 76%)
............................................................. 1037 / 1275 ( 81%)
............................................................. 1098 / 1275 ( 86%)
............................................................. 1159 / 1275 ( 90%)
............................................................. 1220 / 1275 ( 95%)
.......................................................       1275 / 1275 (100%)

Time: 874 ms, Memory: 12.00MB

There was 1 failure:

1) Kohana_ConfigTest::test_detach_removes_reader_and_returns_this
Failed asserting that an array does not contain Mock_Kohana_Config_Reader_93b2bbf2 Object &000000006132f67d0000000009d2a4a4 (
    '__phpunit_invocationMocker' => null
    '__phpunit_originalObject' => null
    '__phpunit_configurable' => Array &0 (
        0 => 'load'
    )
).

/var/www/html/system/tests/kohana/ConfigTest.php:123
/var/www/html/modules/unittest/classes/Kohana/Unittest/TestSuite.php:52

FAILURES!
Tests: 1275, Assertions: 2812, Failures: 1, Skipped: 2, Risky: 1.`
