### ISSUE TITLE
Memcached

### ISSUE THREAD

**Issue by neo22s** [koseven/koseven#65]
Memcache driver is not developed since 2012 and Kohana only has implementation for that driver, should work for memcached but it does not...

This module does https://github.com/gimpe/kohana-memcached

**Comment by neo22s** [comment]
The module has an error, does not sanitize the ID's. Easy to fix.

**Comment by adamcopley** [comment]
Good to just add the files from the gimpe repo right into the cache module and apply fix? Also add config file as cache.memcached.php so it can be optionally used instead of current cache config file?

**Comment by neo22s** [comment]
Actually the config file has an issue it uses a constant and if you do not have memcached driver installed will crash.

https://github.com/gimpe/kohana-memcached/blob/master/config/cache.php#L58

Just add the files and I will do later a PR to sanitize the ID's ;)

**Comment by piotrgolasz** [comment]
Is this issue related to https://github.com/koseven/koseven/pull/74 ?

**Comment by neo22s** [comment]
closed at https://github.com/koseven/koseven/pull/74
