### ISSUE TITLE
ORM: filter columns in as_array and add as_object

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#7]
I think it's a good idea to support the `as_object` function for ORM modules; it has the same behavior as the `as_array` function but outputs an object.
This object can be used in REST interfaces or for ajax requests.

Because some of the columns should remain private I think it's a good idea to allow the ORM model to mark some columns as private (using a ORM property), these will be excluded from the result when calling `as_array` (and `as_object`).
The interface should be backwards compatible so older code will not break.

A pull request can be found [here](https://github.com/koseven/koseven/pull/1).

**Comment by neo22s** [comment]
How could we add some tests?

**Comment by svenbw** [comment]
Neither the database module itself nor the ORM module has testing support. It might be a good idea to add some test (but it will be difficult to cover all cases).
Add another enhancement?
