### ISSUE TITLE
no build.xml file for phing test

### ISSUE THREAD

**Issue by adamcopley** [koseven/koseven#72]
```
$ ./vendor/bin/phing test
Buildfile: build.xml does not exist!
```

Is there a copy of this somewhere not in the repo, or are we currently not running tests on koseven?

**Comment by neo22s** [comment]
https://travis-ci.org/koseven/koseven

**Comment by piotrgolasz** [comment]
@adamcopley We're running tests using phpunit, so
`phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php`
is the winner
