### ISSUE TITLE
Insulation system files: Breaks Kohana on some hosting providers

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#86]
By moving the system files to a separate directory it will be impossible to use Kohana on some hosting providers (the ones who only allow FTP access to the root directory).

Shouldn't we support both options? Trough install.php, configuration option, ...

**Comment by uBizzy** [comment]
You can achieve that with htaccess and an index.php file on your root directory.

**Comment by svenbw** [comment]
Yes: but index.php needs to be modified for the application path (and moved). And the `<?php defined('SYSPATH') or die('No direct script access.');` header is removed from each file. Which makes things less secure in that setup.

**Comment by uBizzy** [comment]
You're right. I was just making a "work around" to get it done. You may also define a different path for each system folder. This way you'll have a "new layer" of security.

Once more, this is not a solution, it's just a "work around".

**Comment by svenbw** [comment]
I like a good work around from time to time, but I think we should implement a "proper" secure solution.

**Comment by knbv** [comment]
What is this hosting that forbids FTP access to child categories of the root directory?

**Comment by knbv** [comment]
What is this hosting that forbids FTP access to child categories of the root directory?

It's hard to call it hosting

**Comment by knbv** [comment]
What is this hosting that forbids FTP access to the child directories of the root directory?

It's hard to call it hosting

Many frameworks do not publish system files in the root directory, and this does not prevent them from being popular.

**Comment by knbv** [comment]
The previous method for protecting files is obsolete, so we removed it

**Comment by svenbw** [comment]
It's called cheap hosting, but some frameworks have everything in one directory and they are also popular (Wordpress).
There are also threads to modify/hack those popular frameworks to work in a single directory.

I understand the reasons why, but it's just a matter of being flexible.

**Comment by neo22s** [comment]
I was really aware of this and I pointed it out but after thinking about it.... if you have the security on htaccess and if we do some docs about how to install in same folder. Should be no issue ;)

**Comment by uBizzy** [comment]
@neo22s , you're right. I told that previously on this conversation, but this still not a solution by it self. On the other side, with a great documentation, step by step, this may be the "simple solution" for those who need this "feature". I may help with it is we go ahead.

**Comment by neo22s** [comment]
yes some docs are fine ;)
