### ISSUE TITLE
Problem with ErrorException

### ISSUE THREAD

**Issue by krassswr** [koseven/koseven#87]
The Error was in my DB::select statement, but instead of showing normal informative Kohana Error I get this error message. It seems that we need to work more on Exception class compatibility with php 7.

`ErrorException [ Fatal Error ]: Uncaught TypeError: Argument 1 passed to Kohana_Exception::handler() must be an instance of Exception, instance of Error given in /XXX/application/classes/Kohana/Exception.php:84 Stack trace: #0 [internal function]: Kohana_Exception::handler(Object(Error)) #1 {main} thrown`

**Comment by neo22s** [comment]
Hello,

If you are extending the Kohana_Kohana_Exception, all functions that received parameter Exception $e have been replaced to just $e. If you are extending the class verify you have the same.

You can read how to migrate here:
https://github.com/koseven/koseven#migrate-kohana-33x-to-koseven-337

**Comment by krassswr** [comment]
Thank you I found the problem in my application.

**Comment by piotrgolasz** [comment]
Good! If problem will occur again (for different reason obv), you can reopen this issue.
