### ISSUE TITLE
Multiple language: howto doc(?)

### ISSUE THREAD

**Issue by svenbw** [koseven/koseven#90]
# Introduction
Unfortunately there is more than one one language in the world. And it’s a challenge to support this in a framework. For my first project that required language selection I had to read into the details. More recently I bumped again into an issue so I thought it might be a good thing to write it out.
Should we add this to the documentation?

# Which language?
First it should be detected (so one can serve the correct language when the visitor visits a page), the visitor should be able to switch the language trough a link or by the selection in his profile.
The language preference of a visitor is specified in the browser and is sent to the server in the accept-language header entry of the request.
Kohana can retrieve the preferred language using the `HTTP::request_headers()->preferred_language($supported_languages)` where `$supported_languages` is a list of languages supported by the application.

# Language selection by routing
_(Thanks to @neo22s for pointing this out)_
To handle the language in the framework it is possible to specify a language parameter in the Route sets:
```
  Route::set('page', '(<language>/)pages(/<seotitle>).html', array('language' => $allowed_languages))
    ->defaults(
      'controller' => 'pages',
      'action' => 'index',
      'language' => 'en'
    );
```
The language can then be easily retrieved using the language param from the request.

# Language selection trough a module
There are modules (e.g. kohana-multilang) that overload the request and routing system of Kohana. There the language is stripped from the request (by the subclass) before it is passed to the base request class. Language support can then be applied (or removed) without changing the bootstrap.php routing rules.
Typically the current language can then be retrieved using a specific call on the request object.

# Language to use
How to store the language for the visitor?
When the visitor visits the site for the first time one needs to determinate preferred language using the browser preference. This selection will probably by the most suitable language selection.
If the language in not available one can use the default.
If the visitors switches the language he’s preferred language is probably different than the one configured in his browser so one needs to store this on the browser by using a cookie (this assures that when the visitor returns he will get the website in the language he prefers).
In both configurations (by routing or module) the first thing to do is to redirect the visitor to the proper url (for Dutch visiting www.example.com would redirect to www.example.com/nl. www.example.com would return the English version).
So not that if the language was switched (using a menu option) the next time the visitor visits the root of the domain (www.example.com) the cookie will overrule the browser preference.

# Language switch menu
_(Thanks to @knbv for pointing this out)_
On most sites switching can be done by a pulldown menu. Switching the language should leave the visitor at the same page as before.
```
// Get the name of the active route
$route = Route::name(Request::current()->route());

// Get the applied route parameters
$params['controller'] = Request::current()->controller();
$params['action'] = Request::current()->action();
$params = array_merge($params, Request::current()->param());

// Create the translated URL for the current route (route setup)
$params['language'] = $language_name;
Route::url($route_name, $params);

// OR: Create the translated URL for the current route (module setup)
Route::url($route_name, $params, NULL, $language_name)
```

**Comment by neo22s** [comment]
Hello!

I think is pretty much everything I can share more code, is not big secret.

We can create a wiki with this same text :P

**Comment by svenbw** [comment]
Okay I'm slow ;-) So let's do a wiki for other slow Kohana users.

I did some test by returning the route name in the `Request::process` code, which omits the array_search in `Route::name`, doing this speeds up finding the route name by +/-70%.
I can create a PR for it which would allow something like `Request()::current()->route_name()` but if it's only for translations I don't think it has a big advantage...

**Comment by neo22s** [comment]
https://gist.github.com/neo22s/d81857a29abf982d6e5e7f372b3adb66

**Comment by piotrgolasz** [comment]
Translations are done by __() function, You have to set correct I18n::lang()

**Comment by jstrobel** [comment]
Wiki or https://docs.koseven.ga (a "best practice" category?) ?
What do you think? Or both? 
docs.koseven.ga for "static" core functions and wiki for dynamic things like "best practice" and examples?

**Comment by neo22s** [comment]
the docs are generated on the fly from latest release.... will be better that is generated static and then uploaded to github. And yeah probably same subdomain with the wiki?

But for now lets put it just in koseven.ga as markdown probably?

**Comment by jstrobel** [comment]
Or we change the template of docs.koseven.ga and put on the left next to "user guide" as "wiki" with a link to github?

**Comment by neo22s** [comment]
for me all is fine, just not much time

**Comment by svenbw** [comment]
Let's use the Github wiki; allows easy editing.

**Comment by jstrobel** [comment]
Yes editing in the wiki is easy and fine. Let's use that. What i mean is just that we have some links to all places where we store docs. I will add them.

**Comment by jstrobel** [comment]
Links added and some first github wiki page improvments.
