### ISSUE TITLE
What's happening?

### ISSUE THREAD

**Issue by tangerine** [koseven/koseven#91]
Hi neo22s.
I posted a question for you on Kohana's Discourse three weeks ago.
Your "Telegram group" links don't work.

Please let me know where you are in the correspondence with Shadowhand.
Thanks.

**Comment by neo22s** [comment]
https://telegram.me/koseven it works of course theres members and today there was a new member. ;)

I am not actively checking discourse we are focused on Koseven, I will take a look now.

We are waiting to give us domain name so we can host the site.

regards

**Comment by tangerine** [comment]
Your "telegram" link responds with this:

"The address wasn’t understood

Firefox doesn’t know how to open this address, because one of the following protocols (tg) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address."

**Comment by neo22s** [comment]
You need telegram

**Comment by satara** [comment]
To me, the address only worked in Chrome (I am using Mac). In safari and firefox I get the same error as tangerine.

**Comment by tangerine** [comment]
Thank you satara, that was helpful.
