### ISSUE TITLE
PSR-2 compliant?

### ISSUE THREAD

**Issue by lox** [koseven/koseven#92]
Thoughts on updating the codebase to be PSR-2 compliant?

**Comment by piotrgolasz** [comment]
This would be BC.

**Comment by lox** [comment]
Backwards compatible? Or breaking change? 

Why would it be a breaking change?

**Comment by piotrgolasz** [comment]
Breaking change. Kohana uses proprietary file system called "Cascading File System". In this file loading scheme we first look after files in APP folder, then MODULES, then SYSTEM. PSR-2 specifies namespaces, which only allows loading classes with one particular namespace.

**Comment by lox** [comment]
Yup, fair point. Perhaps adopting everything except the 2-3 breaking rules would still be a step forward?

**Comment by lox** [comment]
Would at least make it easier for patches to be contributed by developers who are used to PSR-2 formatting.

**Comment by piotrgolasz** [comment]
Tbh I don't see point in implementing a standard partially (ie. not fully). Looks to me like implementing changes just for sake of implementing, rather then improving the software. It's not defined in our milestones list, afaik original Kohana devs tried something like this in their 4.0 branch. However, as I mentioned before this would require lots of coding and testing which noone is willing to do. You are however more than welcome to code this feature on your own, and then create a PR ;)

**Comment by neo22s** [comment]
@piotrgolasz I agree, I don't have the time to migrate all my apps to a new PSR. If I needed to do that I will move to laravel probably. Thanks @lox any contribution or suggestion is always good ;)

**Comment by lox** [comment]
I think there is a lot of value in having consistency around formatting in a codebase, even if it falls short of the de-facto standard PSR-2. It would be a considerable forward step to be able to automatically check the consistency of the formatting in this codebase.

That said, sounds like the aim of koseven is just basically lifesupport for dead projects? If so, not worth the effort.

**Comment by jstrobel** [comment]
@lox I would say its more lifesupport of very good working projects ;) But i think, like @neo22s and @piotrgolasz we are working on an "non-PSR-2-Standard" because of time and efford.

**Comment by lox** [comment]
Might be worth capturing them in a phpcs.xml format at any rate?

**Comment by neo22s** [comment]
@lox we do have coding standards and try to follow. https://docs.koseven.ga/guide/kohana/conventions

Dead projects?? why will you say that? :O my projects are quite active... actually yclas has been downloaded almost 1M times already since first release... more than 13K sites are using koseven somehow.

**Comment by lox** [comment]
I was just going off:

> If I needed to do that I will move to laravel probably

No offence intended :)
