### ISSUE TITLE
Password validation with min_length rule

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#93]
In my controller I have **valid_profile** function where was
`$valid->rule('password','max_length', array(':value', 50));`
`$valid->rule('password','min_length', array(':value', 6));`
`$valid->rule('password_confirm','matches',array(':validation', 'password', 'password_confirm'));`

If in view form I try to send **5** chars, my validate work, and tell me to write min. **6** chars, but if I write **7** chars, my project output error
![image](https://cloud.githubusercontent.com/assets/7046596/25745891/144c8ef8-31b2-11e7-9ada-547bc31920e5.png)

Then I try to write 8 or more chars, and **POST** is work great.
Next I see KO module **User** and find **get_password_validation()** functions where **min_length** set **8**.

My question is: If I set **min_length** = **6**, why I have error...?

**Comment by Pantela777** [comment]
Set to my side min. 8 symbol too, but maybe have any ideas how to fix this bug.

**Comment by piotrgolasz** [comment]
Hi,
this is not a bug. If you look closer at https://github.com/koseven/koseven/blob/devel/modules/orm/classes/Kohana/ORM/Validation/Exception.php you will see that it has a method errors, which will return all your validation errors.

```
try{
// your code
}catch(Validation_Exception $e){
var_dump($e->errors());
}
```

**Comment by Pantela777** [comment]
This understan, but if I have custom validation rules **min_length = 6**, why project try to check **min_length = 8** chars? Also I write about if try to write **7** chars, project output error message too, why? My custom validation is can't catch and core KO validation can't catch too...


>Also please make sure that you are validating user input, and not hashed password

Of course I check user write chars

**Comment by piotrgolasz** [comment]
What do you get from var_dump($e->errors()); ?

**Comment by Pantela777** [comment]
> var_dump($e->errors()); ?

Where insert this code? To my controller? It output `ErrorException [ Notice ]: Undefined variable: e`
In **Exception.php** which code line?

Thx.

**P.S.** I can to set at my valid-side min. 8 chars, and bug is fixed, but I want to understand why I have this problem...

**Comment by Pantela777** [comment]
#95 ...
