### ISSUE TITLE
ORM_Validation_Exception [ 0 ]: Failed to validate array

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#95]
Have registration page in project, but want's without password field (why? because website admin send recovery link to approve users, and then user with recovery password functions set password).
When try to reg. user output error **ORM_Validation_Exception [ 0 ]: Failed to validate array**

**My Controller:**

    if (isset($_POST['submit']))
    {
      $valid_user['check'] = true;

      $valid_user = ORM::factory('user')->valid_register($_POST);

      if ($valid_user['check'])
      {
            $user_id = ORM::factory('user')->add_new($_POST);

            // Redirect
            $this->redirect(Route::get('register_final')->uri());
      }
      else
      {
            if (isset($valid_user['errors'])) $this->errors = array_merge($this->errors,$valid_user['errors']);

            $block_center->errors = $valid_user['errors'];
      }
    }

**My Model:**

    public function valid_register($data)
    {
        $data = $this->my_filters($data);

        $valid = Validation::factory($data);

        $valid->rule('username','not_empty');
        $valid->rule('username','max_length', array(':value', 64));
        $valid->rule('username','min_length', array(':value', 2));

        $valid->rule('passport_number','not_empty');
        $valid->rule('passport_number','exact_length', array(':value', 11));

        $valid->rule('city','not_empty');

        $valid->rule('mobile','not_empty');
        $valid->rule('mobile','exact_length', array(':value', 9));

        $valid->rule('email','not_empty');
        $valid->rule('email','max_length', array(':value', 50));
        $valid->rule('email','email');
        $valid->rule('email',array($this, 'unique'), array('email', ':value'));
        // $valid->rule('user_confirm_email','matches',array(':validation', 'email', 'user_confirm_email'));

        // $valid->rule('password','not_empty');
        // $valid->rule('password','max_length', array(':value', 64));
        // $valid->rule('password','min_length', array(':value', 8));
        // $valid->rule('password_confirm','matches',array(':validation', 'password', 'password_confirm'));

        $valid->rule('agree','not_empty');

        if ($valid->check())
        {
            $result['check'] = true;
            return $result;
        }
        else
        {
            $result['check'] = false;
            $result['errors'] = $valid->errors('validation');
            return $result;
        }
    }

Any ideas...?
This problem can't see when project was on KO 3.2...

**Comment by neo22s** [comment]
Model User has any rules? example https://github.com/yclas/yclas/blob/master/oc/classes/model/user.php#L63

**Comment by Pantela777** [comment]
I am new in KO, sorry...
I write my user model, where have **$valid->rule()...** it's not enough? Or you are mean another file? system KO file?

**Comment by neo22s** [comment]
I use rules in the model using the rules function.

Then in the remember password looks like this:
https://github.com/yclas/yclas/blob/master/oc/classes/controller/panel/auth.php#L153

**Comment by Pantela777** [comment]
I must change my rule validation which was in model, with this?
Exp. if I have `$valid->rule('username','not_empty');` it was `'username' => array(array('not_empty')),` ?
Can you show me sample how I can do it in my model...? :( Please...

My remember password is works great... at this moment didn't change it... if it's not required...
Also, I must change all my valid rule with this style? :( I have a many validation rules :(

**Comment by piotrgolasz** [comment]
I use different ORM (Jelly) instead of the one provided with Koseven, but if you put the code into the model, then you will have the same validation (for example if you allow users to register themselves and/or add users from administrative panel)

Here some code:
```
public function action_add()
	{
		$this->template->content = View::factory('core/backend/users/add.tpl')
				->bind('errors', $errors);

		if ($this->request->method() == Request::POST)
		{
			try
			{
				$extra_validation = Model_User::get_password_validation($this->request->post());

				$item = Jelly::factory('user')
						->set(array_merge($this->request->post(), $_FILES))
						->save($extra_validation);

				NewTracker::newtrack('Added new user');

				Hint::set(Hint::SUCCESS, Kohana::message('hint', 'backend.common.success.add'));

				$this->request->redirect(Route::url($this->_current_route, array('controller' => $this->request->controller(), 'token' => Security::token())));
			}
			catch (Jelly_Validation_Exception $e)
			{
				$errors = $e->errors('', TRUE);
			}
		}
	}
```

**Comment by svenbw** [comment]
This is an example that checks name, firstname, email, username and password.
```
public function rules()
{
  return array(
    'name' => array(
      array('not_empty'),
      array('max_length', array(':value', 200))
    ),
    'firstname' => array(
      array('not_empty'),
      array('max_length', array(':value', 200))
    ),
    'email' => array(
      array('not_empty'),
      array('email'),
      array('max_length', array(':value', 200))
    ),
    'username' => array(
      array('not_empty'),
      array(array($this, 'unique'), array('username', ':value'))
    ),
    'password' => array(
      array('not_empty')
    )
  );
}`
```

You have to include catch the `ORM_Validation_Exception` when creating the new user.

**Comment by Pantela777** [comment]
@piotrgolasz 
Thx, but I can't ti change in my project all query, because of one mistake... Maybe parallel can use new ORM module too, but at this moment need to run project with KoSeven with currently code, with min. changes... Because I hope to quickly fix all bugs...

@svenbw 
Can you change me my all functions with this rules? https://github.com/koseven/koseven/issues/95#issue-229327547 you see I have very different rules, which works great with KO 3.2 :(

I just need one work example for one bug, then bugs, I try to change...

Also can I move for temp time KO 3.2 module? Because need to run project...

Thx.

P.S. Sorry for many question, sorry for many hope request.

**Comment by svenbw** [comment]
Here you go...
```
public function rules()
{
  return array(
    'username' => array(
      array('not_empty'),
      array('max_length', array(':value', 64)),
      array('min_length', array(':value', 2))
    ),
    'passport_number' => array(
      array('not_empty'),
      array('exact_length', array(':value', 11))
    ),
    'city' => array(
      array('not_empty'),
    ),
    'username' => array(
      array('not_empty'),
      array(array($this, 'unique'), array('username', ':value'))
    ),
    'mobile' => array(
      array('not_empty'),
      array('exact_length', array(':value', 9))
    ),
    // ...
  );
}`

```

**Comment by Pantela777** [comment]
This I understand, but I have **$valid** variable where then I check **$valid->check()** and output result...

Also you can see my methods is **valid_register($data)**, where $data is my form POST information... you write me **rules()**... I'm a little confused ...

**Comment by piotrgolasz** [comment]
```
if (isset($_POST['submit']))
{
  $valid_user['check'] = true;

  $valid_user = ORM::factory('user')->valid_register($_POST);

  if ($valid_user['check'])
  {
        try{
            $user_id = ORM::factory('user')->add_new($_POST);
            // Redirect
            $this->redirect(Route::get('register_final')->uri());
        }
        catch(Validation_Exception $ex)
        {
         $block_center->errors = $ex->errors();
        }
  }
  else
  {
        if (isset($valid_user['errors'])) $this->errors = array_merge($this->errors,$valid_user['errors']);

        $block_center->errors = $valid_user['errors'];
  }
}```

**Comment by Pantela777** [comment]
I try this to another Controller **Profile edit**, but can't output error. Try to move valid_profile() in **try/catch** not output result...
**Remember**: See this error if password field is < **8 symbol** (exp. **6 symbol**). Can't understand why... If default rule is 8 symbol, I think my project must to show me error info.

https://cloud.githubusercontent.com/assets/7046596/26411983/698bb2b2-40b8-11e7-9219-f34764466ea5.png

```
        if (isset($_POST['save']))
        {
            $valid = $this->_model_user->valid_profile($_POST,$user_id);
            if ($valid['check'])
            {
                try{
                $this->_model_user->save_profile($user_id,$_POST);
                $block_center->data = $_POST;
                $block_center->status = true;
                $block_center->message = __('profile_save_ok');
                }
                catch(Validation_Exception $ex)
                {
                 $block_center->errors = $ex->errors();
                }
            }
            else
            {
                if (isset($valid['errors'])) $this->errors = array_merge($this->errors,$valid['errors']);
                $block_center->data = $_POST;
                $block_center->status = false;
                $block_center->errors = $this->errors;
            }
        }
```

**Comment by piotrgolasz** [comment]
My bad should be
```catch(ORM_Validation_Exception)```

**Comment by Pantela777** [comment]
Not work...
![image](https://cloud.githubusercontent.com/assets/7046596/26462291/3042f504-4191-11e7-88b7-a639d5012f12.png)

**Comment by piotrgolasz** [comment]
The answer is above.
