### ISSUE TITLE
Fix DB build query (Database_Exception [ 1055 ])

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#96]
Have next problem with move project to KS, with DB query.

    public function get_all_clients($filter = null, $limit = null, $offset = null)
    {
        $res = DB::select('id', 'status', 'email', 'username', 'passport_number', 'birthday', array($this->_table_name_roles_users.'.role_id','roles'))
            ->from($this->_table_name)
            ->join($this->_table_name_roles_users,'left')
            ->on($this->_table_name_roles_users.'.user_id','=',$this->_table_name.'.id');

            // ID
            (isset($filter['id']) && $filter['id'] != '') ? $res = $res->where($this->_table_name.'.id','=',$filter['id']) : '';

            // Username
            (isset($filter['username']) && $filter['username'] != '') ? $res = $res->and_where('username','LIKE',DB::expr("'%".$filter['username']."%'")) : '';

            // Personal ID
            (isset($filter['passport_number']) && $filter['passport_number'] != '') ? $res = $res->and_where('passport_number','LIKE',DB::expr("'%".$filter['passport_number']."%'")) : '';

            // E-mail
            (isset($filter['email']) && $filter['email'] != '') ? $res = $res->and_where('email','LIKE',DB::expr("'%".$filter['email']."%'")) : '';

            // Status
            (isset($filter['status'])) ? $res = $res->and_where($this->_table_name.'.status','=',$filter['status']) : '';

            $res = $res->and_where($this->_table_name_roles_users.'.role_id','!=',2);
            $res = $res->and_where($this->_table_name_roles_users.'.role_id','!=',3);

            $res = $res->group_by($this->_table_name.'.id')
            ->order_by('id', 'DESC');

        if ($limit) $res = $res->limit($limit);
        if ($offset) $res = $res->offset($offset);

        $res = $res->execute()->as_array();

        if (!empty($res))
        {
            return $res;
        }
        return null;
    }

Output next error: **Database_Exception [ 1055 ]**:
> Database_Exception [ 1055 ]: Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'creditcar.roles_users.role_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [ SELECT `id`, `status`, `email`, `username`, `passport_number`, `birthday`, `roles_users`.`role_id` AS `roles` FROM `users` LEFT JOIN `roles_users` ON (`roles_users`.`user_id` = `users`.`id`) WHERE `roles_users`.`role_id` != 2 AND `roles_users`.`role_id` != 3 GROUP BY `users`.`id` ORDER BY `id` DESC LIMIT 25 ]

How I can change my build query...?

**Comment by svenbw** [comment]
I think you need to modify your database: Take a look at [MySQL Handling of GROUP BY](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html)

**Comment by Pantela777** [comment]
Thx., but I need modify database or build query...? One solution I see to set MySQL option **only_full_group_by**, but maybe share hosting is didn't set me this option, because I want to fix this bug to my side...

How I can change fix my build query... Can't understand...

**Comment by neo22s** [comment]
In the database config you can set up the option ;)

**Comment by Pantela777** [comment]
I yes, but maybe share hosting not, because want to fix query without this option...

**Comment by neo22s** [comment]
I mean in kohana. See
https://github.com/yclas/yclas/blob/master/install/samples/database.php

Sqlmode

**Comment by Pantela777** [comment]
Thx. bug is fixed with `'variables' => array('sql_mode'=>'')`
