### ISSUE TITLE
Page loop with 404 error

### ISSUE THREAD

**Issue by Pantela777** [koseven/koseven#98]
Move project to share hosting (Apache with PHP 7.0).
After more test, I think my project can't call controller, and then loop with 404 error, because if I have **/application/classes/HTTP** folder, page is not open "**ERR_TOO_MANY_REDIRECTS**", but if I delete folder can see this error.
![image](https://cloud.githubusercontent.com/assets/7046596/26203781/a0b794c4-3bed-11e7-9bcb-60c3188eb2fb.png)

Try to **system/classes/Kohana/Controller.php** write **die('Test');** page also didn't output.

Where can find problem...

Thx.

P.S. Remember I move KO 3.2 to KoSeven, also project is work great on localhost. Also clear KoSeven project **Hello work** is run well, I think is not share hosting problem.
Install file just notice about **PECL HTTP Enabled**, but localhost is notice too, but project work.
![image](https://cloud.githubusercontent.com/assets/7046596/26203978/4d3a2afe-3bee-11e7-94d1-262bf27cf690.png)

**Comment by neo22s** [comment]
In local you have the same version?

I mean I have for sure more than 854 customers using koseven. So should be working good, also many others using shared hosting... mmm

This seems a permissions issue or similar, does log, cache folder have permissions?

**Comment by neo22s** [comment]
Also did you follow the migration from 3.2 to 3.3?

**Comment by Pantela777** [comment]
**Local**: Apache 2.4.23 + PHP 7.0.10
**Host**: Apache 2.2.31 + PHP 7.0.10

Yes, I understand problem is, at my side, but can't understand how to catch it...

Have all permissions, 
> Install file just notice about PECL HTTP Enabled, but localhost is notice too, but project work.

I think all migration rule is done, because at local is didn't.

**Comment by Pantela777** [comment]
I find problem... My all route was with Lowcase DIR name
`Route::set('default','(<controller>(/<action>(/<id>)))')`
`	->defaults(array(`
`		'directory'	=> 'pages/main',`
`		'controller'	=> 'main',`
`		'action'		=> 'index'`
`	));`

After change with UpCase, project is run:
`Route::set('default','(<controller>(/<action>(/<id>)))')`
`	->defaults(array(`
`		'directory'	=> 'Pages/Main',`
`		'controller'	=> 'main',`
`		'action'		=> 'index'`
`	));

Thx. All.
